// 简历事实与面试稿中的方法建议分开保存；演练分工、示例计数不作为个人经历。
const metadata = { visibility: "public", status: "active", verification: "self_attested", lastUpdated: "2026-10-07" } as const;

export const didiSources = [
  { ...metadata, id: "S15", title: "滴滴 AI 产品实习简历事实摘要（2026-10）", sourceType: "self_report", public: true, lastChecked: "2026-10-07", relatedProject: "didi-internship", projectStatus: "in_progress", supportsClaimIds: ["C39", "C40", "C41", "C42", "C43"], supports: "候选人最新版简历确认滴滴任职、DiVA 和机票比价 Skill 的职责与阶段成果。", limitations: "成果为候选人自述；未取得原始验收和工时台账，不补写统计周期、样本量、导师分工或最终采集技术路线。" },
  { ...metadata, id: "S16", title: "滴滴面试稿方法摘要（已区分事实与演练）", sourceType: "document", public: true, lastChecked: "2026-10-07", supportsClaimIds: ["C44"], supports: "补充素材交付、AI 与规则分工、航班可比性、指标解释和异常处理的方法。", limitations: "仅公开整理后的方法，不公开原稿。演练中的导师安排、回流取数路线、批次计时和首审计数不能作为已发生事件；原稿引用的外部本地材料未在本轮独立核验。" },
] as const;

export const didiClaims = [
  { ...metadata, id: "C39", claimType: "experience", evidenceBasis: "user_statement", relatedProject: "didi-internship", statement: "2026 年 9 月至今在滴滴 ABC 智能一组担任 AI 产品经理实习生，面向内部业务团队推进 AI 与自动化工作流。", candidateContribution: "负责职责范围内的需求梳理、产品流程设计和效果验证。", aiAssistance: "AI 和自动化工具参与流程执行，不代替本人产品判断。", sourceIds: ["S1", "S15"], supportsClaimIds: [], limitations: "不补写未确认的导师姓名、团队规模或独立负责范围。" },
  { ...metadata, id: "C40", claimType: "project", evidenceBasis: "user_statement", relatedProject: "didi-diva", statement: "主导 DiVA AI 营销素材生产工作台的产品设计，梳理重复制作、尺寸适配与反复修改问题，组织主视觉生成、元素复用、多广告位适配、人工审核和校样导出流程。", candidateContribution: "需求分析、产品设计、验收标准和业务应用推进；主导产品设计不等于独立完成全部工程。", aiAssistance: "AI 提供视觉生成能力，人工保留关键内容与交付判断。", sourceIds: ["S1", "S15"], supportsClaimIds: [], limitations: "未确认具体图像模型、完整审批系统、全局同步和版本回滚能力。" },
  { ...metadata, id: "C41", claimType: "project", evidenceBasis: "user_statement", relatedProject: "didi-diva", statement: "DiVA 应用于机酒国庆营销活动，覆盖 11 个已验收广告位，累计交付 60+ 份业务采用素材，单批交付耗时由 2 小时降至 40 分钟，首次验收通过率为 80%。", candidateContribution: "推动工作台应用与素材交付；数字属于项目整体结果，不归因于某个单独改动。", aiAssistance: "生成和复用帮助素材制作，业务仍参与审核与采用判断。", sourceIds: ["S1", "S15"], supportsClaimIds: [], limitations: "业务采用不等于所有素材已投放；不推导点击率、转化、营收。没有确认首审分母、计时批次数、统计周期和逐项广告位名单。" },
  { ...metadata, id: "C42", claimType: "project", evidenceBasis: "user_statement", relatedProject: "didi-flight-compare", statement: "机票竞品比价 Skill 将数据清洗、同期采集、航班匹配和报告导出组织成可复用流程，定义覆盖率、价差与低价率，帮助业务识别供给和价格短板。", candidateContribution: "拆解跨平台查价与匹配流程，定义指标及业务输出，推动工作流搭建。", aiAssistance: "自动化工具处理重复查询与整理，不代表训练新模型或让模型自由编造价格。", sourceIds: ["S1", "S15"], supportsClaimIds: [], limitations: "最终数据源与采集接入方式待确认，不宣称已完成数仓回流接入、全自动同步或所有异常修复。" },
  { ...metadata, id: "C43", claimType: "project", evidenceBasis: "user_statement", relatedProject: "didi-flight-compare", statement: "机票竞品比价 Skill 完成 80 组航线分析，人工耗时降低 75%，输出供给缺口与高价航班清单，支持业务确定优化优先级。", candidateContribution: "将数据处理结果转成可以继续核查和排序的业务清单。", aiAssistance: "自动化减少重复工作，人工仍需核对异常与结论。", sourceIds: ["S1", "S15"], supportsClaimIds: [], limitations: "80 组不自动等于 80 个不同城市对；缺少工时基数时不换算节省小时或金额；不代表机器运行时间下降、价格下降或订单增长。" },
  { ...metadata, id: "C44", claimType: "skill", evidenceBasis: "source_view", statement: "滴滴面试稿提供工作流设计、可比性检查和效果验证的处理方法，可用于解释本人产品判断或回答假设题。", candidateContribution: "可以说明设计理由和处理思路；未确认的步骤用条件式或未来式表达。", aiAssistance: "面试稿中的理想流程是分析工具，不构成个人事件证据。", sourceIds: ["S16"], supportsClaimIds: [], limitations: "不得把方法改写成已执行的实验、真实失败事件、导师安排或原始统计记录。" },
] as const;

const common = { ...metadata, projectStatus: "in_progress", aiAssistance: "模型和自动化工具参与执行，产品判断与验收由本人负责。" } as const;
export const didiKnowledge = [
  { ...common, id: "K54", title: "滴滴实习与当前工作", relatedProject: "didi-internship", evidenceKind: "duty", keywords: ["滴滴", "didi", "ABC", "目前", "现在", "最新实习", "工作内容"], content: "2026 年 9 月至今，我在滴滴 ABC 智能一组担任 AI 产品经理实习生。工作围绕内部业务提效，主要包括 DiVA AI 营销素材生产工作台和机票竞品比价 Skill。前者把主视觉、复用、适配和人工审核组织成素材交付流程；后者把清洗、同期采集、航班匹配和报告转成可复用分析流程。百度文心一言实习为 2026 年 6 月至 9 月，百川智能为 2026 年 4 月至 6 月。", candidateContribution: "负责对应项目的需求梳理、产品流程与业务输出。", limitations: "两个项目分别回答，不将素材交付指标用于航班分析。", claimIds: ["C39", "C40", "C42", "C13", "C17"], supportsClaimIds: ["C39", "C40", "C42", "C13", "C17"], sourceIds: ["S1", "S15", "S11", "S12"] },
  { ...common, id: "K55", title: "DiVA 素材生产的需求与本人贡献", relatedProject: "didi-diva", evidenceKind: "duty", keywords: ["DiVA", "营销素材", "主视觉", "元素复用", "广告位", "需求", "职责", "设计"], content: "我在滴滴主导 DiVA 的产品设计，服务内部运营素材生产。同一活动需要多种广告位规格，用户会反复制作、适配尺寸和修改内容。我将主视觉生成、元素复用、多广告位适配、人工审核和校样导出串起来，并推动用于机酒国庆营销活动。我的产品判断是把交付单位从一张生成图片扩展到一次活动所需的多规格素材，让需求和验收围绕业务交付组织。", candidateContribution: "梳理用户流程、识别痛点、明确功能与验收标准，主导产品流程设计和应用推进。", limitations: "不扩展为独立完成全部代码，不补写导师安排、具体模型或未确认的功能。", claimIds: ["C40", "C41"], supportsClaimIds: ["C40", "C41"], sourceIds: ["S1", "S15"] },
  { ...common, id: "K56", title: "DiVA 阶段成果与统计边界", relatedProject: "didi-diva", evidenceKind: "confirmed_event", keywords: ["DiVA", "成果", "11", "60", "40分钟", "80%", "验收", "投放", "转化"], content: "在机酒国庆营销活动中，DiVA 覆盖 11 个已验收广告位，累计交付 60+ 份业务采用素材，单批素材交付由 2 小时缩短到 40 分钟，首次验收通过率达到 80%。这些结果体现交付效率、质量和业务采用。广告位是位置规格，素材是交付物，二者不能混为同一数量。业务采用也不能直接解释为已全部投放或提高点击转化。", candidateContribution: "推动工作台的业务应用与交付，结果按项目整体口径表述。", limitations: "没有原始首审分母、批次计时或统计周期，不将演算示例补成真实台账，不把全部提效归因到某项改动。", claimIds: ["C41"], supportsClaimIds: ["C41"], sourceIds: ["S1", "S15"] },
  { ...common, id: "K57", title: "DiVA 的产品取舍与验证思路", relatedProject: "didi-diva", evidenceKind: "method", keywords: ["DiVA", "为什么", "模板", "规则", "人工审核", "编辑", "返工", "优先级", "验证"], content: "解释 DiVA 的设计时，我会先区分视觉探索与精确交付：AI 适合主视觉与部分元素处理，尺寸、关键文案和布局则需要可检查的规则及人工确认。多广告位适配不能只改宽高，还要检查主体比例、可读性和业务信息。面对反馈，我会先确认是否阻断交付，再看频率、替代方案和改动成本。验证要走完修改、校样和导出过程。这里是处理思路，不代表这些检查已经全部自动化，也不是某次真实返工故事。", candidateContribution: "说明与现有职责相符的产品判断和后续验证方法。", limitations: "不声称已上线完整模板引擎、审批系统、自动评分或全局回滚；未确认的细节只以方法回答。", claimIds: ["C40", "C44"], supportsClaimIds: ["C40", "C44"], sourceIds: ["S15", "S16"] },
  { ...common, id: "K58", title: "机票竞品比价 Skill 的职责与业务流程", relatedProject: "didi-flight-compare", evidenceKind: "duty", keywords: ["比价", "Skill", "航班", "航线", "竞品分析", "匹配", "流程", "职责"], content: "我在滴滴推进的机票竞品比价 Skill 面向供给和价格竞争力分析。我拆解跨平台查价与航班匹配流程，将数据清洗、同期采集、匹配和报告导出组织成可复用 Skill，定义覆盖率、价差与低价率。业务拿到的是供给缺口和高价航班清单，能继续核查并确定优化优先级。它的价值是把重复查询转成有业务口径的分析，不是只得到一个笼统的价格数字。", candidateContribution: "需求拆解、业务指标定义、工作流搭建与报告输出设计。", limitations: "最终采用页面采集还是搜索回流尚未确认，不推断具体数据权限、架构或全自动执行。", claimIds: ["C42", "C43"], supportsClaimIds: ["C42", "C43"], sourceIds: ["S1", "S15"] },
  { ...common, id: "K59", title: "比价 Skill 的阶段成果", relatedProject: "didi-flight-compare", evidenceKind: "confirmed_event", keywords: ["比价", "Skill", "80组", "75%", "成果", "耗时", "工时", "收益"], content: "比价 Skill 完成 80 组航线分析，人工耗时降低 75%，输出供给缺口与高价航班清单，支持业务确定优化优先级。75% 对应人工工作时间，不是机器耗时或整个业务成本；80 组分析不自动等于 80 个不同城市对。现阶段能说明查询整理提效和分析交付，不能因此声称已经降低票价、改善订单或营收。", candidateContribution: "将查询整理流程转成可复用分析和业务清单。", limitations: "没有确认旧工时基数、任务去重原始台账与统计周期，不补写节省小时、现金金额或端到端成功率。", claimIds: ["C43"], supportsClaimIds: ["C43"], sourceIds: ["S1", "S15"] },
  { ...common, id: "K60", title: "比价的可比性与指标解释方法", relatedProject: "didi-flight-compare", evidenceKind: "method", keywords: ["比价", "同期", "覆盖率", "低价率", "价差", "分母", "共享航班", "缺失", "价格", "回流"], content: "以滴滴与携程为比较对象解释指标时，我的处理思路是先确认同一出发日期、航班身份、机场、舱等与价格条件，再做比较；同时确认采集时间和完整性，避免把漏采当作供给缺失。覆盖率回答一方航班有多少能在另一方找到，方向决定分母；价差要约定减数方向；严格低价率不把同价计为更低。缺价不能填零，不可比记录应保留原因。这里的比较对象用于说明方法，不代表已确认数据接入路线。若后续调整数据源，应保持任务、时间和来源可关联；这是方法建议，不能说已完成搜索回流接入或自动同步。", candidateContribution: "解释指标含义、可比性检查和异常处理判断。", limitations: "原稿中的具体匹配字段、时间窗口和最终采集路线未获独立确认，不冒充已上线实现。演算例子只说明公式。", claimIds: ["C42", "C44"], supportsClaimIds: ["C42", "C44"], sourceIds: ["S15", "S16"] },
  { ...common, id: "K61", title: "滴滴项目未确认信息的回答范围", relatedProject: "didi-internship", evidenceKind: "method", keywords: ["滴滴", "导师", "分工", "样本量", "统计周期", "数据源", "演练", "真实经历"], content: "滴滴成果以简历已写明的任职、职责和结果为准。面试稿中的导师指导、具体推进次序、部分验证安排及搜索回流路线属于演练设定，不能补成真实经历。遇到未记录的个人事件或原始计数时，先说明当前不能准确确认，再讲可以说明的职责或验证思路。岗位方法题可以正常展开，不能为了完整而虚构台账。", candidateContribution: "区分本人确认的产出和方法推演。", limitations: "不使用演练批次、首审分母、旧工时示例解释个人成果；不公开原稿和内部材料。", claimIds: ["C39", "C44"], supportsClaimIds: ["C39", "C44"], sourceIds: ["S15", "S16"] },
] as const;
