// 按 2026-09-07 提供的简历与三份面试材料整理；示例数字与待验证方案不作为个人成果。
const publicEvidence = {
  visibility: "public", status: "active", verification: "self_attested", lastUpdated: "2026-09-07",
} as const;

export const interviewSources = [
  { ...publicEvidence, id: "S14", title: "个人能力汇总（2026-09-03，已校准摘要）", sourceType: "document", public: true, lastChecked: "2026-09-07", supportsClaimIds: ["C6", "C9", "C10", "C11", "C29", "C30", "C34", "C35", "C36", "C37", "C38"], supports: "补充英语与财会学习、审计、校园协作、AI Coding 方法和个人工具的可公开实践。", limitations: "仅公开整理后的事实摘要，不公开原始文档或联系方式；示例评分表、公司客户规模、未核验 Token 总量不是个人业绩。RAG 状态以 9 月 7 日专题稿为准，ACCA 区分已通过科目与课程学习。" },
] as const;

export const interviewClaims = [
  { ...publicEvidence, id: "C31", claimType: "project", evidenceBasis: "user_statement", relatedProject: "baidu-ai-coding-evaluation", statement: "WebDev E2E Bench V0.2 已扩充到 30 题，覆盖 6 类任务、6 个产品领域和 3 档难度；完成 30/30 Gold 连续三次通过和 60/60 受控错误版本检出。", candidateContribution: "设计任务结构与验收规则，推动离线校准；首轮 16/30 Gold 通过时先修正规则，再做全量复验。", aiAssistance: "工具执行确定性验证，模型辅助生成与检查。", sourceIds: ["S11"], supportsClaimIds: [], limitations: "这是 V0.2 离线任务与评估器验证，不是 6 模型乘 30 题实测；正式多模型结果仍来自 V0.1 的 36 次 Pilot，不能声称主观体验评价完全准确。" },
  { ...publicEvidence, id: "C32", claimType: "experience", evidenceBasis: "user_statement", relatedProject: "baidu-ai-coding-evaluation", statement: "在百度文心一言团队参与大模型业务场景批量评测、统一标注、版本对比、Bad Case 归因和策略复测；重点推进 WebDev E2E Bench 专项。", candidateContribution: "定义评价维度、比较优势与退化场景，提出 Prompt、检索、调用流程等策略建议，协同算法和研发复测质量、Token 与响应效率。", aiAssistance: "模型是评测对象，工具辅助批量执行和结果整理。", sourceIds: ["S1", "S11"], supportsClaimIds: [], limitations: "日常评测的示例评分和幻觉率不能作为实测数字；WebDev 具备支持文心版本对照的方法，尚未接入文心现网版本替换决策。" },
  { ...publicEvidence, id: "C33", claimType: "experience", evidenceBasis: "user_statement", relatedProject: "rag-knowledge-base", statement: "百川实习中调研并梳理十余家潜在医疗客户的需求样本，覆盖医院及医联体、卫健部门、药企与医疗科研机构，归纳知识库管理、幻觉控制、答案溯源与针对性配置需求。", candidateContribution: "将共性需求转成文档入库、检索问答、来源核验和失败状态，将差异需求收敛为助手配置。", aiAssistance: "模型辅助公开 Demo 实现，不作为客户事实来源。", sourceIds: ["S1", "S12"], supportsClaimIds: [], limitations: "十余家是潜在需求样本，不是签约、上线或独立访谈客户数；亲访、旁听、转述和材料研究的具体人数及比例未记录，不编造访谈原话、客户名单或客户验收。" },
  { ...publicEvidence, id: "C34", claimType: "experience", evidenceBasis: "user_statement", statement: "具有学院活动策划、跨部门协调和班级活动组织经历；担任德勤校园大使时参与秋招行程统筹，并独立主持一场 Tax 线秋招面试流程。", candidateContribution: "统筹面试者行程、衔接面试官与候选人、推进校招传播；学院实践中组织体育活动并协调多方执行。", aiAssistance: "无。", sourceIds: ["S14"], supportsClaimIds: [], limitations: "校园组织和现场协调不等于企业人员管理；不把满意度或覆盖人数作为未经核验的业务成效，不补造现场冲突、导师原话或正式招聘决策权。" },
  { ...publicEvidence, id: "C35", claimType: "project", evidenceBasis: "user_statement", relatedProject: "resume-autofill", statement: "Resume Autofill AI 是 Chrome/Edge 简历辅助填写工具，覆盖简历解析、表单扫描、字段语义映射、置信度分级、人工确认和一键撤销。", candidateContribution: "设计填写流程、敏感字段拦截、失败降级和可撤销交互，组织扩展、控制台与 API 的共享类型。", aiAssistance: "AI Coding 辅助实现，模型用于解析和语义映射。", sourceIds: ["S14"], supportsClaimIds: [], limitations: "不声称支持所有招聘网站，不自动替用户提交申请；没有公开用户规模或投递成功率。" },
  { ...publicEvidence, id: "C36", claimType: "project", evidenceBasis: "user_statement", relatedProject: "harnesslab", statement: "HarnessLab（当前作品集名称 AgentScope）以代码 diff 或片段为输入，形成结构化风险发现、评分和审计报告，并提供 Trace、Eval Card、历史记录与报告导出。", candidateContribution: "设计 Mock/DeepSeek 双 Provider、输入输出 Schema 校验、可观察链路与核心流程测试。", aiAssistance: "模型辅助代码分析，AI Coding 工具辅助工程实现。", sourceIds: ["S14", "S10"], supportsClaimIds: [], limitations: "代码审查建议需要人工判断，不是证明代码绝对安全的认证，也不代表生产漏洞检出率。" },
  { ...publicEvidence, id: "C37", claimType: "project", evidenceBasis: "user_statement", relatedProject: "career-knowledge", statement: "基于 Obsidian、Codex 和 Agent Skills 组织本地求职知识流程，贯通资料摄入、知识提炼、简历与面试准备、反馈回流，并使用来源、SHA-256、证据分级和版本管理保持可追溯。", candidateContribution: "设计知识结构、可复用 Skill、来源验证与质量检查，把重复准备工作沉淀为可复用流程。", aiAssistance: "Agent 辅助提炼与整理，候选人审核事实和公开范围。", sourceIds: ["S14"], supportsClaimIds: [], limitations: "自动提炼不等于自动确认为事实；个人资料和原始内容不会因此授权公开，也不声称是企业级知识平台。" },
  { ...publicEvidence, id: "C38", claimType: "skill", evidenceBasis: "user_statement", statement: "持续使用 ChatGPT、DeepSeek、Kimi、Claude Code 和 Codex 进行资料研究、原型验证和 AI Coding，结合 SQL、Python 与统计基础理解数据、模型评测和产品约束。", candidateContribution: "负责问题定义、任务拆解、上下文与验收标准，检查代码、日志和测试结果并判断取舍。", aiAssistance: "AI 参与实现与调试，不能把所有代码视为纯手写，也不能以生成量代替个人能力。", sourceIds: ["S14", "S1"], supportsClaimIds: [], limitations: "学习 Transformer、注意力、RAG 与 Harness 原理不等于从事底层模型训练；不使用无法复核的累计 Token 总量证明能力。" },
] as const;

const baidu = { ...publicEvidence, relatedProject: "baidu-ai-coding-evaluation", projectStatus: "in_progress", aiAssistance: "模型与工具辅助执行，候选人负责问题定义、产品判断和验收。", sourceIds: ["S11"] } as const;
const rag = { ...publicEvidence, relatedProject: "rag-knowledge-base", projectStatus: "in_progress", aiAssistance: "模型用于检索问答或 Judge；研发负责工程实现，候选人负责产品规则和验证。", sourceIds: ["S12"] } as const;

export const interviewKnowledge = [
  { ...baidu, id: "K40", title: "文心日常业务评测与 WebDev 专项的关系", keywords: ["文心", "文心一言", "日常工作", "业务场景", "批量测试", "版本对比", "策略迭代", "正确性", "指令遵循"], content: "百度实习有两条相互支撑的工作线：日常业务评测围绕正确性、相关性、完整性、指令遵循和幻觉风险，批量测试不同模型与策略版本，统一标注后比较提升项、退化项和高频问题；WebDev E2E Bench 则把同一方法深入到网页交付场景，补充功能、视觉、交互和工程证据。我的价值是把评分转成问题优先级、策略建议和复测结论。", candidateContribution: "参与业务评测与策略协作，重点推进 WebDev 专项的任务、指标、流程和验证；跟踪质量、Token 和响应效率。", limitations: "不引用讲解用评分表数字，不把通用归因方法都说成已经实施的优化，也不声称 WebDev 已用于文心现网版本替换。", claimIds: ["C13", "C32"], supportsClaimIds: ["C13", "C32"] },
  { ...baidu, id: "K41", title: "WebDev V0.1 Pilot 与 V0.2 任务集合", keywords: ["v0.2", "v0.1", "30题", "任务集合", "题库", "六个产品领域", "三档难度", "难度", "数据集"], content: "V0.1 每类选一题，完成 6 模型×6 任务×1 次正式运行，共 36 次 Pilot。V0.2 每类扩充到 5 题，共 30 题，覆盖 SaaS 后台、电商、协作效率、内容社区、数据分析、服务运营六个领域；easy、medium、hard 各 10 题，按 Dev 12、Validation 8、Test 10 划分。难度由交互步骤、状态数量、数据依赖、错误分支和修改约束决定。V0.2 已完成离线规则验证，尚未完成六模型对全部 30 题的付费重跑。", candidateContribution: "定义用户目标、Starter、公开与隐藏检查、Gold、Rubric 和版本信息，让任务可执行、可校准并支持后续场景比较。", limitations: "30 题是任务建设量，不是新增模型实测矩阵；原 Pilot 分数不能外推到 V0.2。", claimIds: ["C14", "C15", "C31"], supportsClaimIds: ["C14", "C15", "C31"] },
  { ...baidu, id: "K42", title: "V0.2 先校准评估器再扩测", keywords: ["校准", "gold", "16/30", "30/30", "60/60", "受控错误", "误报", "先验证评估器"], content: "V0.2 首轮只有 16/30 Gold 通过，暴露的是测试状态、断言与兼容性问题。我先推动修正规则再全量复验，最终 30/30 Gold 连续三次通过，30 题各自的明显和近似错误版本共 60 个均被拦截。这个经历体现我的判断：先确认尺子有效，再扩大模型评测，避免把评估器故障归因给模型。主观体验仍需人工校准，这些数字不代表主观判断百分之百准确。", candidateContribution: "识别评估规则问题、推动校准与复验，把可重复的任务质量作为扩测前提。", limitations: "仅为 V0.2 离线验证；不新增模型排名、商业收益或多人盲评结论。", claimIds: ["C31", "C22"], supportsClaimIds: ["C31", "C22"] },
  { ...baidu, id: "K43", title: "评测如何支持文心版本决策", keywords: ["版本替换", "新版本", "小版本", "业务价值", "为什么做", "创新", "竞品", "决策", "排行榜"], content: "WebDev 解决效果难完整判断、低分难解释、结果难行动的问题，直接服务 AI 产品经理、模型负责人和 Agent 研发。差异在于把产品验收、评估器校准、根因分析和迭代决策连起来；端到端与人工评价并非首创。若用于文心版本升级，我会固定任务、Agent、预算和评分，先查核心流程与严重回退，再权衡场景收益、Token、成本和时延，形成全量替换、分场景路由、继续灰度或暂缓的建议。目前这是基于离线体系提出的应用思路，尚未接入文心现网决策。", candidateContribution: "把可视化控制台围绕模型比较、失败证据与问题详情组织，缩短从分数到判断的路径。", limitations: "不把版本决策设想、潜在一次生成成功率或满意度提升说成已验证业务结果。", claimIds: ["C14", "C31", "C32"], supportsClaimIds: ["C14", "C31", "C32"] },
  { ...rag, id: "K44", title: "百川十余家潜在客户需求分析", keywords: ["十余家", "客户调研", "需求分析", "潜在客户", "访谈", "药企", "卫健", "用户研究"], content: "我调研并梳理的是十余家潜在医疗客户需求样本，涵盖医院及医联体、卫健部门、药企和科研机构。共性问题包括私有知识分散、更新和管理困难、模型幻觉、答案无法溯源，以及不同场景需要不同配置。我将这些问题转成知识库管理、检索问答、来源核验和助手配置需求。十余家不等于已签约或上线客户，也不等于全部由我独立访谈；具体亲访、旁听、转述和材料研究的比例没有可公开的分项数字。", candidateContribution: "梳理业务任务与需求，把共性能力和差异配置分开，与技术团队对齐可验证的产品范围。", limitations: "不冒领公司合作医院、银川等案例，不编造客户名称、访谈原话、采购金额和上线验收。", claimIds: ["C17", "C19", "C33"], supportsClaimIds: ["C17", "C19", "C33"] },
  { ...rag, id: "K45", title: "医疗客户共性底座与针对性配置", keywords: ["针对性配置", "多助手", "多租户", "共性需求", "定制", "医院与药企", "配置边界"], content: "共性底座承载文档处理、知识库、检索、生成与来源返回；差异用助手绑定的知识库、Prompt、温度、Top-K、Rerank 和短期记忆参数表达。我用这种方式平衡不同客户的回答规范和复用成本。多助手是业务配置，多租户是客户级授权与数据隔离，不能相互替代。当前只有基础配置与短期记忆；助手版本保存仍是 Mock，完整版本治理、配置审批和生产级多租户属于后续设计。", candidateContribution: "定义配置入口、默认值、异常分支与验收边界，推动算法研发联调。", limitations: "不把配置页面称为完整生产能力，不声称长期记忆、完整 Agent、版本持久化或完整行业模板已经落地。", claimIds: ["C19", "C20", "C33"], supportsClaimIds: ["C19", "C20", "C33"] },
  { ...rag, id: "K46", title: "RAG 三轮 QA 的执行口径与实验限制", keywords: ["30条", "30次", "三轮", "3轮", "独立样本", "配置快照", "陷阱题", "error"], content: "3 轮累计 30 条准确地说是三份报告各 10 次 QA 执行；每轮 7 条单跳、2 条多跳、1 条不可回答陷阱题。error 是陷阱题的内部类别，测试无证据时是否拒答，并非系统报错。三轮可能重复，未完整保留固定题集与 Rerank、Prompt 配置快照，因此能够说明多轮验证和问题发现，不能归因某策略带来了确定提升。后续我会固定数据与配置、增加独立保留集，再比较 Dense-only 与 Dense+Rerank。", candidateContribution: "搭建生成或导入、人工编辑、批量问答、四维评分和 Markdown 报告的评测流程。", limitations: "后续消融是处理思路，不能说已完成受控 A/B、版本回归门禁或医院线上质量验证。", claimIds: ["C19", "C21", "C26", "C27"], supportsClaimIds: ["C19", "C21", "C26", "C27"] },
  { ...rag, id: "K47", title: "RAG 从召回排序到生成的诊断", keywords: ["召回排序生成", "归因", "召回问题", "排序问题", "生成问题", "bad case", "优化依据"], content: "我用三轮评测和低分样本发现、分析了 RAG 的薄弱场景。进一步定位时，我的处理思路是先确认问题、参考答案和金标证据；关键证据不在初始 Top-K，查分块、向量和查询；在候选里却没进最终上下文，查 Rerank 与截断；证据已经进入模型而答案仍遗漏、曲解或扩写，查 Prompt 与生成。一轮多跳 2 条均分 4.38 对比单跳 9.71，是风险信号。已经确认的是问题发现和分层分析，固定对照与扩大回归仍需补齐。", candidateContribution: "将模糊效果问题拆成有证据的归因假设，为 Rerank 与 Prompt 优化提供依据。", limitations: "当前用报告和日志人工分析，没有专门 Bad Case 平台；不编造各类错误比例或已经验证的优化提升。", claimIds: ["C19", "C26", "C27"], supportsClaimIds: ["C19", "C26", "C27"] },
  { ...rag, id: "K48", title: "RAG 忠实度准确性与引用的区别", keywords: ["faithfulness", "accuracy", "ground truth", "幻觉率", "9.8", "引用正确率", "忠实度", "准确性"], content: "当前四维是 Faithfulness、Relevancy、Context Precision、Accuracy。忠实度看是否被检索上下文支持，准确性在有 Ground Truth 时看答案是否正确；旧证据可能让回答忠实却不准确。Judge 的 9.8 分不能换算成幻觉率 2%，连续评分与错误条数占比是不同口径。没有金标时应标记准确性不可评。引用标记存在也不等于结论被支持，引用正确率、Context Recall、拒答正确率应单独验证，尚不属于当前四维实现。", candidateContribution: "定义指标用途与判分边界，结合人工审核理解分维结果。", limitations: "不把小样本 Judge 高分称为线上准确率、消除幻觉或客户验收；完整 PDF 页码高亮与一键定位仍需补强。", claimIds: ["C20", "C21", "C26", "C27"], supportsClaimIds: ["C20", "C21", "C26", "C27"] },
  { ...publicEvidence, id: "K49", title: "校园与招聘现场的沟通协作", keywords: ["校园", "学生工作", "组织活动", "沟通协调", "团队协作", "主持", "Tax", "校园大使"], content: "学院实践中，我参与活动策划、体育活动和跨部门协调；德勤校园大使经历中，我统筹秋招面试者行程，独立主持一场 Tax 线面试流程，衔接面试官与候选人，并参与校招宣传。它让我在固定时间、多方信息和现场变化下练习任务拆解与沟通推进。迁移到产品工作，我会先确认各方目标、交接节点和验收条件，再把分歧转成能讨论的事实。", candidateContribution: "负责职责范围内的组织、沟通和现场流程，不代替正式面试官做录用判断。", aiAssistance: "无。", limitations: "不新增未记录的冲突故事、同事原话或商业管理成果。", claimIds: ["C11", "C34"], supportsClaimIds: ["C11", "C34"], sourceIds: ["S14"] },
  { ...publicEvidence, id: "K50", title: "Resume Autofill AI 可控的简历辅助填写", relatedProject: "resume-autofill", projectStatus: "in_progress", keywords: ["resume autofill", "简历速填", "网申", "表单映射", "置信度", "一键撤销"], content: "Resume Autofill AI 把重复网申拆成简历解析、网页表单扫描、字段语义映射、置信度分级、人工确认与一键撤销。它支持 Chrome/Edge MV3，扩展、Web 控制台、API 和共享类型协同工作。我的产品重点是把辅助填写做得可控：敏感字段拦截、映射不确定时交给人确认、API 或模型异常时降级，并保留撤销。", candidateContribution: "负责用户流程、输入输出结构、风险控制与原型验收。", aiAssistance: "模型辅助解析和映射，AI Coding 辅助开发。", limitations: "不自动提交申请，不声称支持所有网站或提升录用率；材料中的测试数量属于当时快照。", claimIds: ["C35"], supportsClaimIds: ["C35"], sourceIds: ["S14"] },
  { ...publicEvidence, id: "K51", title: "HarnessLab 代码审计工作台", relatedProject: "harnesslab", projectStatus: "in_progress", keywords: ["harnesslab", "agentscope", "代码审计", "diff", "eval card", "trace timeline"], content: "HarnessLab 在当前作品集中以 AgentScope 展示，围绕代码 diff 或 file snippet 生成结构化风险发现、风险评分与审计报告。Mock/DeepSeek 双 Provider 支持演示和真实调用，Zod 检查请求与模型输出；Trace Timeline、Eval Card、历史记录与 Markdown/JSON 导出帮助使用者检查过程和结果。我的判断是，审查工具的价值还取决于结论能否被理解、定位和人工复核。", candidateContribution: "设计可观察审查流程、数据结构、失败处理与核心测试。", aiAssistance: "AI 参与代码分析和实现，最终审查判断由使用者负责。", limitations: "不保证发现所有漏洞，不把演示或测试数量当成生产安全认证。", claimIds: ["C36"], supportsClaimIds: ["C36"], sourceIds: ["S14", "S10"] },
  { ...publicEvidence, id: "K52", title: "个人知识库与反馈回流", relatedProject: "career-knowledge", projectStatus: "in_progress", keywords: ["obsidian", "自生长", "个人知识库", "知识治理", "skills", "来源哈希", "反馈回流"], content: "我的本地求职知识流程连接资料摄入、知识提炼、简历生成、面试准备和反馈回流。来源路径、SHA-256、证据分级和版本管理让每次更新可追溯；Agent Skill 将重复工作变成可复用流程。产品上的关键是区分原始资料、整理后的知识和已确认事实，自动提炼后仍由我审核，再决定能否进入公开数字分身。", candidateContribution: "组织知识结构、审核流程和自动检查，让反馈形成下一轮材料改进。", aiAssistance: "Agent 辅助整理，不自动确认个人事实。", limitations: "不公开本机路径或私人资料，不声称完整企业级知识治理。", claimIds: ["C37"], supportsClaimIds: ["C37"], sourceIds: ["S14"] },
  { ...publicEvidence, id: "K53", title: "AI Coding 中本人的判断与学习方法", keywords: ["claude code", "codex", "vibe coding", "AI写的", "AI编程", "你自己的能力", "学习", "压力", "不会技术"], content: "我持续使用 Claude Code、Codex 和多种大模型进行原型开发与资料研究，也用 SQL、Python 和统计基础检查数据与结果。我的工作不是只输入一句需求：先拆清用户目标、技术约束和验收条件，给 AI 明确上下文，再通过代码、日志、测试和实际交互判断是否完成。不懂的部分从当前问题补最小必要原理，结合文档、技术讨论和小验证形成自己的判断。统计、审计、百川医疗 RAG 与百度评测逐步沉淀了这套持续学习和推进方法。", candidateContribution: "负责问题选择、产品取舍、过程纠偏与最终验收；生成失败时定位原因并迭代。", aiAssistance: "AI 辅助代码、调试和资料整理；不把全部实现归为本人纯手写。", limitations: "不使用未经复核的累计 Token 量证明水平，不把原理学习说成底层训练经验，也不新增未记录的压力事件。", claimIds: ["C2", "C9", "C13", "C17", "C38"], supportsClaimIds: ["C2", "C9", "C13", "C17", "C38"], sourceIds: ["S1", "S11", "S12", "S14"] },
] as const;
