const updated = "2026-09-07";
const publicActive = { visibility: "public", status: "active", lastUpdated: updated } as const;

export const strengthContent = [
  { title: "模型评测与归因", description: "结合统计学、百川医疗 RAG 与百度实习，能用指标、评测集和 Bad Case 归因推动 AI 产品迭代。" },
  { title: "审计与业务理解", description: "具备财务审计和 IT 审计经历，理解流程、风险、证据和企业数据边界。" },
  { title: "AI 产品工程落地", description: "从百川医疗 RAG、百度 Evaluator 到 Ask Me 与 DeepFlow，能把需求、模型能力和评测标准转成可运行、可验收链路。" },
] as const;

export const projectAliases = {
  "rag-knowledge-base": ["rag", "知识库", "企业级rag", "医疗rag", "医疗知识助手", "百川", "百川智能", "rag knowledge base", "代表项目"],
  deepflow: ["deepflow", "多agent", "multi-agent", "研究工作台", "深度研究"],
  "thirty-minute-brain": ["thirty-minute brain", "thirty minute brain", "30分钟大脑", "上下文恢复"],
  "local-first-tools": ["本地优先", "read later", "downloads butler", "效率工具"],
  "audit-tools": ["德勤 it 审计", "it 审计", "审计工具", "归档助手", "日志抽查", "audit assistant"],
  "ask-me": ["ask me", "数字分身", "求职agent", "career agent", "本项目"],
  "baidu-ai-coding-evaluation": ["百度", "文心", "文心一言", "baidu", "webdev", "v0.1", "v0.2", "qwen", "ai coding", "evaluator agent", "模型评测", "七维指标", "硬门槛", "gate", "dashboard样例"],
  "resume-autofill": ["resume autofill", "简历速填", "网申速填", "表单映射"],
  harnesslab: ["harnesslab", "agentscope", "代码审计", "eval card", "trace timeline"],
  "career-knowledge": ["个人知识流程", "智能自生长知识库", "obsidian", "agent skills", "求职知识库"],
} as const;

export const knowledgeContent = [
  { ...publicActive, id: "K1", title: "候选人定位", keywords: ["介绍", "60秒", "背景", "优势", "张倬玮", "定位", "成长主线"], content: "张倬玮是东北大学应用统计学 2027 届学生，求职方向为 AI 产品经理。主线不是突然转行：统计训练形成样本、指标和结论边界意识，审计经历补充企业流程、证据与风险视角；百川医疗 RAG 将这些能力带入需求、方案和验证的 0—1 实践，百度文心一言实习再推进到业务评测、端到端评测体系和 Bad Case 归因。Ask Me、DeepFlow 等作品持续验证问题定义、AI Coding 和产品闭环能力。", verification: "self_attested", candidateContribution: "候选人整理并确认简历、实习和作品的公开叙事顺序。", aiAssistance: "AI 用于结构化表达，不作为个人事实来源。", limitations: "最新版简历以百川与百度为主线；审计作为补充能力证据，项目结果按各自版本和边界说明。", claimIds: ["C1", "C2", "C6", "C9", "C17", "C13", "C28", "C29", "C32", "C38"], supportsClaimIds: ["C1", "C2", "C6", "C9", "C17", "C13", "C28", "C29", "C32", "C38"], sourceIds: ["S1", "S11", "S12", "S14"] },
  { ...publicActive, id: "K2", title: "AI 产品岗位匹配", keywords: ["匹配", "岗位", "ai产品经理", "能力", "短板", "缺口", "核实", "为什么"], content: "核心匹配点是应用统计学带来的数据与评测意识、德勤形成的企业流程和风险理解、百川医疗 RAG 形成的需求到可信问答闭环、百度形成的多模型评测与 Bad Case 归因，以及 Ask Me、DeepFlow 证明的自主产品定义和快速验证能力。", verification: "self_attested", candidateContribution: "候选人参与需求拆解、产品取舍、评测设计、跨角色协作与验收，并持续完成公开 Agent 产品。", aiAssistance: "AI 编程工具参与公开原型实现，候选人负责需求、验证和事实边界。", limitations: "这是岗位证据分析，不是录用结论；具体贡献仍需面试核实，不虚构生产规模、商业结果或独立 Owner 身份。", claimIds: ["C2", "C3", "C4", "C6", "C12", "C13", "C17", "C19", "C28"], supportsClaimIds: ["C2", "C3", "C4", "C6", "C12", "C13", "C17", "C19", "C28"], sourceIds: ["S1", "S2", "S3", "S4", "S11", "S12"] },
  { ...publicActive, id: "K3", title: "教育与技能", keywords: ["教育", "学校", "东北大学", "专业", "统计", "技能", "证书", "英语", "acca", "奖项"], content: "就读于东北大学应用统计学专业，预计 2027 年毕业。统计训练让我习惯从样本、指标、实验和结论边界出发做判断；掌握 SQL 与 Python 数据分析，并通过 RAG、模型评测、AI Coding 和 Agent 原型把方法用于产品验证。个人能力汇总记录 CET-4 619、CET-6 520；ACCA 已通过 BT、MA、FA、FR、PM 五门，另学习过 LW、TX，不表述为完成全部资格。", verification: "self_attested", candidateContribution: "候选人提供并授权公开。", aiAssistance: "无。", limitations: "已通过与已学习科目必须区分；熟悉 AI 应用不等于底层模型训练或纯工程专家。", claimIds: ["C1", "C2", "C30", "C38"], supportsClaimIds: ["C1", "C2", "C30", "C38"], sourceIds: ["S1", "S14"] },
  { ...publicActive, id: "K4", title: "百川智能医疗 RAG 知识助手", keywords: ["rag", "医疗rag", "百川", "百川智能", "知识库", "检索", "dense retrieval", "rerank", "milvus", "代表项目", "项目"], relatedProject: "rag-knowledge-base", content: "该项目是百川智能实习的主要产出，面向医疗私有文档的检索、问答与来源核验。公开仓库是脱敏重构，已展示知识入库、稠密向量召回与 Rerank、来源片段、短期记忆、多助手基础配置和自动评测。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "候选人参与需求与 MVP 梳理、功能和配置边界设计、检索问答协作、QA 数据与评测闭环。", aiAssistance: "公开 Demo 使用外部模型和 AI 编程工具辅助实现，不代表百川内部模型或代码。", limitations: "不披露客户、内部模型、生产代码和敏感数据；未完整实现 BM25 混合检索、长期记忆、完整 Agent、持久化版本对比、专门 Bad Case 平台和生产级 RBAC。", claimIds: ["C3", "C17", "C18", "C19", "C20"], supportsClaimIds: ["C3", "C17", "C18", "C19", "C20"], sourceIds: ["S3", "S12"] },
  { ...publicActive, id: "K5", title: "DeepFlow 多 Agent 研究工作台", keywords: ["deepflow", "agent", "多agent", "研究", "planner", "researcher", "报告", "mvp", "hybrid", "agent trace", "成果导出"], relatedProject: "deepflow", content: "DeepFlow 从 0 到 1 打通需求澄清、计划确认、资料检索、分析生成和成果导出的研究闭环。Coordinator、Planner、Researcher、Coder 和 Reporter 围绕明确输入输出分工，并结合私域 RAG、Hybrid 检索、引用溯源、结构化输出与 Agent Trace 提升结果可信度和过程可控性。", projectStatus: "in_progress", verification: "externally_verified", candidateContribution: "候选人负责研究流程、Agent 分工、人审节点、观测字段与报告资产链路设计。", aiAssistance: "模型承担研究生成，AI 编程工具辅助工程实现。", limitations: "真实用户、生产并发、权限审计、工具状态持久化、时延和成本尚未形成独立验证。", claimIds: ["C4"], supportsClaimIds: ["C4"], sourceIds: ["S1", "S4"] },
  { ...publicActive, id: "K6", title: "本地优先效率工具", keywords: ["thirty", "brain", "read later", "downloads", "本地", "桌面", "浏览器", "效率工具", "tauri"], relatedProject: "local-first-tools", content: "公开项目包括 Thirty-Minute Brain、Read-Later Regret 和 Downloads Butler，分别解决短期上下文恢复、信息债管理和下载文件夹整理问题。", projectStatus: "completed", verification: "externally_verified", candidateContribution: "完成产品定义、安全规则、数据模型与原型实现。", aiAssistance: "AI 编程工具参与实现和测试。", limitations: "目前缺少公开的用户规模、留存和长期价值数据。", claimIds: ["C5"], supportsClaimIds: ["C5"], sourceIds: ["S1", "S5", "S6", "S7"] },
  { ...publicActive, id: "K7", title: "审计业务工具", keywords: ["审计工具", "归档", "日志", "底稿", "ocr", "streamlit", "it审计"], relatedProject: "audit-tools", content: "将审计资料整理和 IT 日志抽查场景转化为两个公开工具，覆盖字段抽取、归档建议、异常规则检查和审计关注点生成。", projectStatus: "completed", verification: "externally_verified", candidateContribution: "负责场景抽象、规则设计、原型实现与测试。", aiAssistance: "OCR、LLM 与 AI 编程工具参与实现。", limitations: "不公开真实客户或企业数据，提效结果尚无第三方测量。", claimIds: ["C7"], supportsClaimIds: ["C7"], sourceIds: ["S1", "S8", "S9"] },
  { ...publicActive, id: "K8", title: "德勤 IT 审计实习", keywords: ["德勤", "it审计", "底稿", "日志核查", "实习", "20份", "脱敏", "prompt"], content: "2026 年 1 月至 4 月参与德勤 IT 审计实习，接触操作系统与 APP 控制相关资料的编制、复核和证据核验；补充材料记录复核 20 余份相关文档。还使用 Prompt 辅助数据脱敏，并把日志抽查与资料归档问题延伸为两个公开 AI 工具。", verification: "self_attested", candidateContribution: "候选人提供并确认任职时间、职责和流程改进方式。", aiAssistance: "Prompt、OCR 与 LLM 用于脱敏和公开工具原型。", limitations: "旧材料中的合并数量和效率倍数不作为当前默认口径；不回答客户名称、底稿内容或企业机密。", claimIds: ["C6", "C7", "C9"], supportsClaimIds: ["C6", "C7", "C9"], sourceIds: ["S13", "S14", "S8", "S9"] },
  { ...publicActive, id: "K9", title: "容诚财务审计实习", keywords: ["容诚", "财务审计", "底稿", "函证", "盘点", "实习"], content: "2025 年 1 月至 3 月参与容诚财务审计实习，公开职责描述涉及底稿、函证与盘点。", verification: "self_attested", candidateContribution: "候选人提供并确认任职时间与职责描述。", aiAssistance: "无。", limitations: "该经历不是最新版简历主线；不回答客户名称、底稿内容或企业机密。", claimIds: ["C6", "C10"], supportsClaimIds: ["C6", "C10"], sourceIds: ["S13"] },
  { ...publicActive, id: "K10", title: "德勤校园大使", keywords: ["德勤", "校园大使", "校招", "主持", "Tax", "行程统筹"], content: "曾担任德勤校园大使，参与秋招行程统筹与校招推广，并独立主持一场 Tax 线秋招面试流程，衔接面试官与候选人。", verification: "self_attested", candidateContribution: "负责职责范围内的信息同步、流程组织与现场推进。", aiAssistance: "无。", limitations: "不表述为正式录用决策权、企业人员管理或未经记录的现场冲突。", claimIds: ["C6", "C11", "C34"], supportsClaimIds: ["C6", "C11", "C34"], sourceIds: ["S13", "S14"] },
  { ...publicActive, id: "K11", title: "能力边界", keywords: ["短板", "不足", "边界", "缺口", "风险", "待核实"], content: "当前公开证据的主要缺口是大规模商业化 AI 产品、真实用户增长与留存、长期跨职能团队管理，以及公开项目在生产环境中的稳定性数据。", verification: "self_attested", candidateContribution: "候选人主动说明当前能力限制。", aiAssistance: "无。", limitations: "能力边界会随实习和项目进展更新。", claimIds: ["C8"], supportsClaimIds: ["C8"], sourceIds: ["S1", "S10"] },
  { ...publicActive, id: "K12", title: "Ask Me 求职数字分身", keywords: ["ask me", "数字分身", "求职agent", "career agent", "本项目", "招聘", "106", "48"], relatedProject: "ask-me", content: "Ask Me 针对传统简历无法继续追问、项目贡献难核验的问题，围绕“快速了解—深入追问—项目核验—查看简历或联系”设计招聘方路径；支持推荐问题、开放提问、多轮指代和动态追问，并用 Claim-Source、风险分级与事实审校平衡面试表现力和可信度。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "负责产品洞察、用户路径、PRD、信息架构、证据模型、回答边界和工程验收。", aiAssistance: "AI 编程 Agent 参与代码生成、资料整理和测试。", limitations: "最新版简历记录阶段性 106 项自动化测试和 48 个 AI 面试用例；代码持续扩充回归，阶段快照不等于当前测试总数，也不证明真人招聘转化。", claimIds: ["C12", "C28"], supportsClaimIds: ["C12", "C28"], sourceIds: ["S1", "S2"] },
  { ...publicActive, id: "K22", title: "百度文心一言 AI 产品经理实习", keywords: ["百度", "文心", "文心一言", "baidu", "实习", "ai产品经理", "模型评测", "策略优化", "bad case", "webdev"], relatedProject: "baidu-ai-coding-evaluation", content: "2026 年 6 月至今在百度文心一言团队担任 AI 产品经理实习生。工作有两条主线：日常业务评测围绕正确性、相关性、指令遵循等维度批量比较模型和策略版本，识别优势、退化与高频 Bad Case；WebDev E2E Bench 专项则围绕网页交付建立任务、指标、失败证据和可视化分析。共同目标是把分数转成可解释的问题、策略建议和复测判断。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "参与业务评测与策略协作，重点负责 WebDev 专项的任务、指标、证据、流程和验收，协同算法研发复测。", aiAssistance: "模型和自动化工具是评测对象与执行工具，产品判断和结果边界由候选人负责。", limitations: "不公开冻结版本和内部数据，不声称独立负责模型训练、全部工程实现或现网版本替换。", claimIds: ["C13", "C14", "C15", "C31", "C32"], supportsClaimIds: ["C13", "C14", "C15", "C31", "C32"], sourceIds: ["S1", "S11"] },
  { ...publicActive, id: "K23", title: "AI Coding 七维评测与 Gate", keywords: ["ai coding", "七维", "指标", "权重", "gate", "硬门槛", "功能正确性", "视觉", "交互", "响应式", "可访问性", "代码质量", "六类任务"], relatedProject: "baidu-ai-coding-evaluation", content: "WebDev E2E Bench 覆盖页面生成、功能实现、组件、页面重设计、轻全栈和 Bugfix+UX 六类任务；从用户能否获得可运行、可交互应用出发，设置功能、可用性、视觉、交互、响应式、可访问性和代码质量七维，并用 Gate 保护构建、核心流程和页面可达性。", projectStatus: "completed", verification: "self_attested", candidateContribution: "参与任务、指标、权重与 Gate 规则设计，并通过 Pilot 与人工评分校准可解释性。", aiAssistance: "确定性工具负责硬检查，LLM Judge 处理开放体验维度，人工负责校准。", limitations: "权重与门槛属于当前 Pilot 规则，不是行业统一标准。", claimIds: ["C14", "C15"], supportsClaimIds: ["C14", "C15"], sourceIds: ["S11"] },
  { ...publicActive, id: "K24", title: "Evaluator Agent 与正式 Pilot", keywords: ["evaluator agent", "评测器", "pilot", "36次", "6个模型", "6类任务", "18份盲评", "playwright", "axe-core", "结构化报告"], relatedProject: "baidu-ai-coding-evaluation", content: "Evaluator Agent 以 Task Spec、候选项目、运行配置和 Rubric 为输入，用确定性工作流完成安装、构建、探活、核心流程、三视口、可访问性和证据采集，再由双 Judge 处理开放体验判断并输出七维结果与报告。正式 Pilot 覆盖 6 个模型、6 类任务和 36 次运行，并完成 18 份单人盲评校准。", projectStatus: "completed", verification: "self_attested", candidateContribution: "参与 Benchmark 调研、任务与流程设计、MVP 实现验证、Pilot 执行、人工盲评、结果分析和交付材料整理。", aiAssistance: "Python、Playwright、axe-core 与日志提供确定性证据，LLM Judge 负责开放维度评分。", limitations: "每个模型任务组合仅运行一次，盲评由一人且抽样不均；只支持当前 Pilot 的场景判断，不代表生产平台或行业排名。", claimIds: ["C14", "C15", "C23"], supportsClaimIds: ["C14", "C15", "C23"], sourceIds: ["S11"] },
  { ...publicActive, id: "K25", title: "自动评测可信度与当前边界", keywords: ["可信", "一致性", "误报", "漏报", "gold", "judge", "校准", "稳定性", "spearman", "人工"], relatedProject: "baidu-ai-coding-evaluation", content: "当前校准集上，6/6 个 Gold 样例通过、10/10 个确定性缺陷被检出、重复自动检查一致性为 100%，主观缺陷方向敏感度为 5/6，漏掉了较弱的信息层级问题。Auto-Judge Spearman 为 0.6191，Judge-Human 为 0.4599；这些结果说明链路具备初步判别力，但人工样本窄且不均衡，不能把 Judge 当绝对真值。", projectStatus: "completed", verification: "self_attested", candidateContribution: "参与校准样例、重复检查、人工评分和一致性分析，明确评测器也需要被评测。", aiAssistance: "LLM Judge 与确定性工具共同输出结果，人工提供 Gold 与争议判断。", limitations: "校准数字只适用于当前样本；Auto-Human 相关性受窄分布与不均匀抽样影响，仅作诊断，不报告为通用准确率。", claimIds: ["C22"], supportsClaimIds: ["C22"], sourceIds: ["S11"] },
  { ...publicActive, id: "K26", title: "Coding Benchmark 调研", keywords: ["benchmark", "humaneval", "swe-bench", "web-bench", "webdevjudge", "fullstack bench", "13项", "行业研究"], relatedProject: "baidu-ai-coding-evaluation", content: "调研 13 项 Coding Benchmark，并按单函数或算法、仓库级修复、Web 或全栈项目、评测器可靠性四类整理。核心结论是公开 Benchmark 可以提供任务构造、可执行测试和环境复现方法，但真实 AI Coding 产品还要补充视觉、交互、用户可用性与业务边界。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "整理各 Benchmark 的任务、数据、指标、环境与局限，并提炼可迁移到业务评测的部分。", aiAssistance: "AI 可辅助资料整理，最终分类和业务取舍由候选人完成。", limitations: "不把 Benchmark 排行榜或论文结论当作本人项目成果；具体阅读深度以面试说明为准。", claimIds: ["C16"], supportsClaimIds: ["C16"], sourceIds: ["S1", "S11"] },
  { ...publicActive, id: "K27", title: "百川智能 AI 产品实习", keywords: ["百川", "百川智能", "实习", "医疗", "ai产品", "经历顺序", "工作内容", "2026.04", "2026.06", "十余家"], relatedProject: "rag-knowledge-base", content: "2026 年 4 月至 6 月在百川智能参与 AI 产品经理实习，主要产出是医疗 RAG 知识库问答项目。我围绕十余家潜在医疗客户需求样本梳理知识库管理、幻觉控制、答案溯源与差异配置，再与算法研发协作将需求收敛为文档入库、检索问答、来源返回、助手配置和三轮 QA 验证闭环。", projectStatus: "completed", verification: "self_attested", candidateContribution: "参与需求研究与产品架构，重点定义主链路、功能规则、配置和异常边界、评测流程与验收标准。", aiAssistance: "模型用于问答与评测，AI 编程工具参与公开 Demo 脱敏重构。", limitations: "十余家是潜在需求样本，不是签约上线或本人独立访谈客户数；不公开客户身份、内部模型、生产代码或声称完成客户交付。", claimIds: ["C17", "C18", "C19", "C33"], supportsClaimIds: ["C17", "C18", "C19", "C33"], sourceIds: ["S1", "S12"] },
  { ...publicActive, id: "K28", title: "医疗 RAG 产品架构与 MVP", keywords: ["医疗rag", "四层架构", "文档处理", "知识库管理", "问答层", "评测层", "mvp"], relatedProject: "rag-knowledge-base", content: "产品按用户任务拆为文档处理、知识库管理、检索问答和评测四层。P0 是知识入库、检索问答、来源返回和失败状态，先构成最短可信闭环，再扩展复杂配置。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "参与定义用户入口、流程状态、异常分支、配置边界、优先级和验收标准，并与算法、研发对齐。", aiAssistance: "模型承担问答与部分评测，产品职责不被模型替代。", limitations: "不把类名、接口或检索算法的实现归为个人独立开发；具体交付物只在能够现场出示时说明。", claimIds: ["C19"], supportsClaimIds: ["C19"], sourceIds: ["S12"] },
  { ...publicActive, id: "K29", title: "医疗 RAG 检索与来源链路", keywords: ["医疗rag", "dense", "稠密向量", "rerank", "gte-rerank", "来源片段", "引用溯源", "top-k", "检索"], relatedProject: "rag-knowledge-base", content: "当前主链路是文档解析、切片和 Embedding 后写入 Milvus；提问时先做稠密向量召回，再用 Rerank 精排，将证据片段与短期上下文交给模型生成答案并返回来源片段，形成基础引用溯源。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "参与召回遗漏和排序错误场景梳理、检索参数与降级边界、对照指标和联调验收。", aiAssistance: "检索和生成由模型与工程组件执行，候选人负责产品规则与质量判断。", limitations: "当前不是 BM25 混合检索；PDF 页码高亮和一键定位原文尚未完整实现，来源片段不能被描述为彻底消除幻觉。", claimIds: ["C19", "C20"], supportsClaimIds: ["C19", "C20"], sourceIds: ["S12"] },
  { ...publicActive, id: "K30", title: "医疗 RAG 多助手与短期记忆", keywords: ["多助手", "assistant", "短期记忆", "redis", "session", "ttl", "滑动窗口", "prompt"], relatedProject: "rag-knowledge-base", content: "多助手允许按场景配置知识库、系统 Prompt、温度、检索参数和记忆参数；Redis 短期记忆按 session 隔离最近消息，用滑动窗口和 TTL 支持指代消解与连续追问。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "参与多助手配置边界、会话隔离、上下文长度和异常状态的产品设计与验收。", aiAssistance: "模型使用配置与短期上下文生成回答。", limitations: "当前可确认助手基础配置和短期记忆；版本持久化、长期记忆和完整 Agent 执行尚未完整落地。", claimIds: ["C19", "C20"], supportsClaimIds: ["C19", "C20"], sourceIds: ["S12"] },
  { ...publicActive, id: "K31", title: "医疗 RAG 四维评测闭环", keywords: ["rag评测", "faithfulness", "relevancy", "context precision", "accuracy", "qa数据集", "llm-as-judge", "报告", "30次"], relatedProject: "rag-knowledge-base", content: "当前支持 QA 数据生成或导入、人工编辑、批量运行 RAG、四维 LLM-as-Judge 打分与报告输出。已完成三轮、累计 30 次 QA 执行，每轮 7 个单跳、2 个多跳和 1 个不可回答陷阱题；四维为 Faithfulness、Relevancy、Context Precision 和 Accuracy。", projectStatus: "completed", verification: "self_attested", candidateContribution: "参与 QA 数据和评测流程、指标含义、报告输出、结果复核与人工校准边界的产品设计。", aiAssistance: "LLM-as-Judge 输出 0—10 分与理由，需固定模型、Prompt、温度和数据集版本。", limitations: "30 次是三份报告各 10 次运行，不等于 30 个独立真实医疗问题；Judge 不是绝对真值，引用正确率、Context Recall、拒答正确率、版本比较和回归门禁仍需补强。", claimIds: ["C19", "C20", "C21", "C26"], supportsClaimIds: ["C19", "C20", "C21", "C26"], sourceIds: ["S12"] },
  { ...publicActive, id: "K32", title: "AI Coding Pilot 结果与场景判断", keywords: ["83.71", "83.30", "deepseek", "codex", "模型对比", "场景推荐", "共同弱项"], relatedProject: "baidu-ai-coding-evaluation", content: "当前 Pilot 中 DeepSeek 83.71、ChatGPT/Codex 83.30，置信区间重叠，可判断为同一领先梯队而不是稳定唯一赢家。任务层面，ChatGPT/Codex 在页面生成更好，ERNIE 在重设计更好，DeepSeek 在组件、轻全栈和 Bugfix+UX 更强；共同弱项集中在多状态交互、错误恢复、需求契约、可访问性和移动端细节。", projectStatus: "completed", verification: "self_attested", candidateContribution: "参与把总体分数拆成任务类型、共同风险和场景化选型建议。", aiAssistance: "评测器生成分项结果和证据。", limitations: "结论仅适用于本次冻结版本、任务集和一次运行，不是行业权威排行榜。", claimIds: ["C23"], supportsClaimIds: ["C23"], sourceIds: ["S11"] },
  { ...publicActive, id: "K33", title: "Qwen 写入协议诊断 A/B", keywords: ["qwen", "16.04", "69.07", "53.03", "254765", "74447", "token", "协议", "写入限制", "诊断a/b"], relatedProject: "baidu-ai-coding-evaluation", content: "Qwen 在 Ticket CRUD 任务中出现协议型失败。固定模型、任务和总预算，仅增加 6000 字符写入限制、追加写入和写后校验后，得分由 16.04 提升到 69.07，输入 Token 由 254,765 降至 74,447。这个案例说明低分不一定只是模型能力，也可能来自工具协议与产品约束。", projectStatus: "completed", verification: "self_attested", candidateContribution: "参与识别协议型根因、设计受控诊断和复核分项变化。", aiAssistance: "模型执行生成，评测器提供证据。", limitations: "这是正式结果后的单任务诊断，不进入榜单，不能外推为模型普遍提升或充分因果证明。", claimIds: ["C24"], supportsClaimIds: ["C24"], sourceIds: ["S11"] },
  { ...publicActive, id: "K34", title: "AI Coding 评测流程效率估算", keywords: ["42分钟", "12分钟", "15分钟", "4分钟", "71.4", "73.3", "效率", "提效"], relatedProject: "baidu-ai-coding-evaluation", content: "以已有 Web 项目进入评测到形成结论为口径，人工主动操作时间由 42 分钟估算降至 12 分钟，报告整理由 15 分钟降至 4 分钟。价值来自自动执行、自动采证和结构化报告，而不是简单减少人工判断。", projectStatus: "completed", verification: "self_attested", candidateContribution: "参与评测流程拆解、自动采证和报告结构设计。", aiAssistance: "自动化工具与 Judge 承担部分执行和汇总。", limitations: "这是项目内流程估算，不包含模型生成时间，不是线上 A/B、生产效率或 ROI。", claimIds: ["C25"], supportsClaimIds: ["C25"], sourceIds: ["S11"] },
  { ...publicActive, id: "K35", title: "医疗 RAG 评测结果", keywords: ["7.55", "8.62", "9.50", "9.80", "7.40", "8.10", "7.80", "9.70", "p95", "评测结果"], relatedProject: "rag-knowledge-base", content: "三轮累计 30 次 QA 执行中，综合分为 7.55—8.62，Faithfulness 为 9.50—9.80，Relevancy 为 7.40—8.10，Context Precision 为 7.80—9.70，P95 完整响应为 4.30—8.57 秒。它证明评测链路能运行并发现弱场景，而不是证明线上准确率或客户验收。", projectStatus: "completed", verification: "self_attested", candidateContribution: "参与批量运行、指标复核、报告整理和结论边界判断。", aiAssistance: "LLM-as-Judge 输出分数与理由。", limitations: "样本小、问题包含自动生成、Judge 存在偏差；不外推为生产性能或真实医疗效果。", claimIds: ["C26", "C27"], supportsClaimIds: ["C26", "C27"], sourceIds: ["S12"] },
  { ...publicActive, id: "K36", title: "医疗 RAG 多跳问题风险", keywords: ["多跳", "single-hop", "multi-hop", "9.71", "4.38", "问题分解", "证据组合", "bad case"], relatedProject: "rag-knowledge-base", content: "一轮评测中单跳均分为 9.71，多跳均分为 4.38。产品上应把它视为高优先级风险信号：先检查 Judge、数据和检索，再验证问题分解、子问题召回、跨证据组合与最终生成，并将代表性样例固化为回归集。", projectStatus: "completed", verification: "self_attested", candidateContribution: "参与把多跳低分拆成数据、检索、证据组合和生成等可验证环节。", aiAssistance: "Judge 提供初步分数与理由。", limitations: "多跳样本仅 2 个，只能证明发现并分析了风险，不能声称某项优化已使结果提升。", claimIds: ["C27"], supportsClaimIds: ["C27"], sourceIds: ["S12"] },
  { ...publicActive, id: "K37", title: "简历主线与项目能力递进", keywords: ["经历串联", "项目串联", "成长路径", "项目组合", "作品集", "为什么做这些项目"], content: "项目并非孤立堆叠：德勤的底稿、日志和脱敏场景训练流程与风险意识，并延伸出审计工具；百川把这套证据意识迁移到医疗 RAG 的检索、来源和评测闭环；百度进一步把质量判断升级为多模型 E2E Benchmark、Evaluator 和 Bad Case 归因；Ask Me 将可信回答用于招聘决策，DeepFlow 将可控执行用于复杂研究；Resume Autofill AI、个人知识库、HarnessLab、Read-Later Regret 和 Downloads Butler 则验证求职效率、知识管理、代码审计、信息债与文件整理等具体问题。", verification: "self_attested", candidateContribution: "候选人持续从真实流程问题出发，完成需求定义、原型推进和质量验收。", aiAssistance: "AI Coding 与 Agent 工具提高实现速度，候选人负责问题选择、产品取舍和最终验收。", limitations: "不同项目成熟度不同；项目组合证明持续学习与快速验证，不等于每个项目都有真实用户规模或商业结果。", claimIds: ["C4", "C5", "C7", "C9", "C12", "C13", "C17", "C28", "C29"], supportsClaimIds: ["C4", "C5", "C7", "C9", "C12", "C13", "C17", "C28", "C29"], sourceIds: ["S1", "S2", "S3", "S4", "S8", "S9", "S10", "S11", "S12"] },
  { ...publicActive, id: "K38", title: "Ask Me 回答策略与评测", keywords: ["ask me", "风险分级", "高频问题", "事实问题", "方法问题", "自动化测试", "面试用例", "106", "48"], relatedProject: "ask-me", content: "Ask Me 按问题风险分级：高频问题走稳定快速通道，事实敏感题接受二次审校，低风险方法题实时生成；同时保留推荐问题、多轮追问、项目指代、事实来源和专业边界承接。最新版简历记录阶段性 106 项自动化测试和 48 个 AI 面试用例，当前代码继续增加开放题、流式和安全回归。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "负责回答策略、风险边界、测试设计和持续验收。", aiAssistance: "模型生成回答，AI Coding 工具辅助实现与测试。", limitations: "106 是简历形成时的阶段快照，不等于当前测试总数；自动化与 AI 面试用例不能替代真人招聘者验证。", claimIds: ["C12", "C28"], supportsClaimIds: ["C12", "C28"], sourceIds: ["S1", "S2"] },
  { ...publicActive, id: "K39", title: "AI 项目作品集", keywords: ["作品集", "其他项目", "resume autofill", "网申速填", "智能自生长知识库", "harnesslab", "agentscope", "代码审计", "read-later", "downloads butler"], content: "作品集除 Ask Me 与 DeepFlow 外，还包括 Resume Autofill AI、个人智能自生长知识流程、AgentScope（HarnessLab）和本地效率工具。它们分别验证可控网申填写、来源可追溯的求职知识、结构化代码风险审查和本地信息整理。共同方法是从明确摩擦出发，先定义输入、边界、失败状态和验收，再用 AI Coding 快速验证闭环。", verification: "self_attested", candidateContribution: "负责问题选择、产品定义、任务拆解、交互与安全边界和原型验收。", aiAssistance: "AI Coding 与 Agent 工具参与实现，候选人检查代码、日志与测试并负责最终判断。", limitations: "不以代码生成量代替个人能力；未公开逐项用户规模、商业结果和长期稳定性。", claimIds: ["C29", "C35", "C36", "C37", "C38"], supportsClaimIds: ["C29", "C35", "C36", "C37", "C38"], sourceIds: ["S1", "S10", "S14"] },
] as const;

export const suggestedQuestionContent = [
  "60 秒了解张倬玮。",
  "他与 AI 产品经理岗位的匹配证据是什么？",
  "哪个公开项目最能代表他的 AI 产品能力？",
  "他的主要短板和待核实问题是什么？",
] as const;
