const updated = "2026-08-13";
const publicActive = { visibility: "public", status: "active", lastUpdated: updated } as const;

export const strengthContent = [
  { title: "模型评测与归因", description: "结合统计学、百川医疗 RAG 与百度实习，能用指标、评测集和 Bad Case 归因推动 AI 产品迭代。" },
  { title: "审计与业务理解", description: "具备财务审计和 IT 审计经历，理解流程、风险、证据和企业数据边界。" },
  { title: "AI 产品工程落地", description: "参与百川医疗 RAG 与 Evaluator Agent MVP，把需求、模型能力和评测标准转成可运行、可验收链路。" },
] as const;

export const projectAliases = {
  "rag-knowledge-base": ["rag", "知识库", "企业级rag", "医疗rag", "医疗知识助手", "百川", "百川智能", "rag knowledge base", "代表项目"],
  deepflow: ["deepflow", "多agent", "multi-agent", "研究工作台", "深度研究"],
  "thirty-minute-brain": ["thirty-minute brain", "thirty minute brain", "30分钟大脑", "上下文恢复"],
  "local-first-tools": ["本地优先", "read later", "downloads butler", "效率工具"],
  "audit-tools": ["审计工具", "归档助手", "日志抽查", "audit assistant"],
  "ask-me": ["ask me", "数字分身", "求职agent", "本项目"],
  "baidu-ai-coding-evaluation": ["百度", "baidu", "ai coding", "evaluator agent", "模型评测", "七维指标", "硬门槛", "gate", "dashboard样例"],
} as const;

export const knowledgeContent = [
  { ...publicActive, id: "K1", title: "候选人定位", keywords: ["介绍", "60秒", "背景", "优势", "张倬玮", "定位"], content: "张倬玮是东北大学应用统计学 2027 届学生，目标方向为 AI 产品经理。成长主线依次连接统计学、财务与 IT 审计、百川智能医疗 RAG、百度模型评测和持续的 Agent 产品实践。", verification: "self_attested", candidateContribution: "候选人整理并确认公开定位与经历顺序。", aiAssistance: "AI 用于结构化表达，不作为个人事实来源。", limitations: "教育和经历信息来自候选人维护文档；百川实习精确日期未在本轮确认。", claimIds: ["C1", "C2", "C6", "C17"], supportsClaimIds: ["C1", "C2", "C6", "C17"], sourceIds: ["S1", "S12"] },
  { ...publicActive, id: "K2", title: "AI 产品岗位匹配", keywords: ["匹配", "岗位", "ai产品经理", "能力", "短板", "缺口", "核实", "为什么"], content: "核心匹配点是应用统计学带来的数据评测意识、审计形成的企业流程与风险理解、百川医疗 RAG 形成的需求到可信问答闭环，以及百度实习形成的模型评测与 Bad Case 归因能力。", verification: "self_attested", candidateContribution: "候选人参与需求拆解、产品取舍、评测设计、跨角色协作与验收。", aiAssistance: "AI 编程工具参与公开原型实现，候选人负责需求、验证和事实边界。", limitations: "这是岗位证据分析，不是录用结论；具体贡献范围仍需面试核实，不虚构生产规模、商业结果或独立 Owner 身份。", claimIds: ["C2", "C3", "C6", "C13", "C17", "C19"], supportsClaimIds: ["C2", "C3", "C6", "C13", "C17", "C19"], sourceIds: ["S1", "S3", "S11", "S12"] },
  { ...publicActive, id: "K3", title: "教育与技能", keywords: ["教育", "学校", "东北大学", "专业", "统计", "技能", "证书", "英语", "acca"], content: "就读于东北大学应用统计学专业，预计 2027 年毕业。技能覆盖 SQL、Python、FastAPI、Milvus、RAGAS、Prompt 与工作流设计；CET-4 619、CET-6 520，并完成部分 ACCA 科目。", verification: "self_attested", candidateContribution: "候选人提供并授权公开。", aiAssistance: "无。", limitations: "课程、成绩和证书应以正式材料核实。", claimIds: ["C1", "C2"], supportsClaimIds: ["C1", "C2"], sourceIds: ["S1"] },
  { ...publicActive, id: "K4", title: "百川智能医疗 RAG 知识助手", keywords: ["rag", "医疗rag", "百川", "百川智能", "知识库", "检索", "dense retrieval", "rerank", "milvus", "代表项目", "项目"], relatedProject: "rag-knowledge-base", content: "该项目是百川智能实习的主要产出，面向医疗私有文档的检索、问答与来源核验。公开仓库是脱敏重构，已展示知识入库、稠密向量召回与 Rerank、来源片段、短期记忆、多助手基础配置和自动评测。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "候选人参与需求与 MVP 梳理、功能和配置边界设计、检索问答协作、QA 数据与评测闭环。", aiAssistance: "公开 Demo 使用外部模型和 AI 编程工具辅助实现，不代表百川内部模型或代码。", limitations: "不披露客户、内部模型、生产代码和敏感数据；未完整实现 BM25 混合检索、长期记忆、完整 Agent、持久化版本对比、专门 Bad Case 平台和生产级 RBAC。", claimIds: ["C3", "C17", "C18", "C19", "C20"], supportsClaimIds: ["C3", "C17", "C18", "C19", "C20"], sourceIds: ["S3", "S12"] },
  { ...publicActive, id: "K5", title: "DeepFlow 多 Agent 研究工作台", keywords: ["deepflow", "agent", "多agent", "研究", "planner", "researcher", "报告", "mvp"], relatedProject: "deepflow", content: "DeepFlow 通过 Coordinator、Planner、Researcher、Coder 和 Reporter 等角色组织研究计划、资料检索、分析和报告生成，已形成一条可演示 MVP 链路。", projectStatus: "in_progress", verification: "externally_verified", candidateContribution: "候选人负责 Agent 分工、人审节点、观测字段与报告资产链路设计。", aiAssistance: "模型承担研究生成，AI 编程工具辅助工程实现。", limitations: "真实用户、生产并发、权限审计、工具状态持久化、时延与成本尚未形成独立验证。", claimIds: ["C4"], supportsClaimIds: ["C4"], sourceIds: ["S1", "S4"] },
  { ...publicActive, id: "K6", title: "本地优先效率工具", keywords: ["thirty", "brain", "read later", "downloads", "本地", "桌面", "浏览器", "效率工具", "tauri"], relatedProject: "local-first-tools", content: "公开项目包括 Thirty-Minute Brain、Read-Later Regret 和 Downloads Butler，分别解决短期上下文恢复、信息债管理和下载文件夹整理问题。", projectStatus: "completed", verification: "externally_verified", candidateContribution: "完成产品定义、安全规则、数据模型与原型实现。", aiAssistance: "AI 编程工具参与实现和测试。", limitations: "目前缺少公开的用户规模、留存和长期价值数据。", claimIds: ["C5"], supportsClaimIds: ["C5"], sourceIds: ["S1", "S5", "S6", "S7"] },
  { ...publicActive, id: "K7", title: "审计业务工具", keywords: ["审计工具", "归档", "日志", "底稿", "ocr", "streamlit", "it审计"], relatedProject: "audit-tools", content: "将审计资料整理和 IT 日志抽查场景转化为两个公开工具，覆盖字段抽取、归档建议、异常规则检查和审计关注点生成。", projectStatus: "completed", verification: "externally_verified", candidateContribution: "负责场景抽象、规则设计、原型实现与测试。", aiAssistance: "OCR、LLM 与 AI 编程工具参与实现。", limitations: "不公开真实客户或企业数据，提效结果尚无第三方测量。", claimIds: ["C7"], supportsClaimIds: ["C7"], sourceIds: ["S1", "S8", "S9"] },
  { ...publicActive, id: "K8", title: "德勤 IT 审计实习", keywords: ["德勤", "it审计", "ipe", "日志核查", "实习"], content: "2026 年 1 月至 4 月参与德勤 IT 审计实习，公开职责描述涉及 IPE 与日志核查。", verification: "self_attested", candidateContribution: "候选人提供并确认任职时间与职责描述。", aiAssistance: "无。", limitations: "不回答客户名称、底稿内容或企业机密；任职信息需正式材料核实。", claimIds: ["C6", "C9"], supportsClaimIds: ["C6", "C9"], sourceIds: ["S1"] },
  { ...publicActive, id: "K9", title: "容诚财务审计实习", keywords: ["容诚", "财务审计", "底稿", "函证", "盘点", "实习"], content: "2025 年 1 月至 3 月参与容诚财务审计实习，公开职责描述涉及底稿、函证与盘点。", verification: "self_attested", candidateContribution: "候选人提供并确认任职时间与职责描述。", aiAssistance: "无。", limitations: "不回答客户名称、底稿内容或企业机密；任职信息需正式材料核实。", claimIds: ["C6", "C10"], supportsClaimIds: ["C6", "C10"], sourceIds: ["S1"] },
  { ...publicActive, id: "K10", title: "德勤校园大使", keywords: ["德勤", "校园大使", "校招", "主持", "推广"], content: "曾担任德勤校园大使，公开职责描述包括流程主持与校招推广。", verification: "self_attested", candidateContribution: "候选人提供并确认职责描述。", aiAssistance: "无。", limitations: "活动范围与效果需面试核实。", claimIds: ["C6", "C11"], supportsClaimIds: ["C6", "C11"], sourceIds: ["S1"] },
  { ...publicActive, id: "K11", title: "能力边界", keywords: ["短板", "不足", "边界", "缺口", "风险", "待核实"], content: "当前公开证据的主要缺口是大规模商业化 AI 产品、真实用户增长与留存、长期跨职能团队管理，以及公开项目在生产环境中的稳定性数据。", verification: "self_attested", candidateContribution: "候选人主动说明当前能力限制。", aiAssistance: "无。", limitations: "能力边界会随实习和项目进展更新。", claimIds: ["C8"], supportsClaimIds: ["C8"], sourceIds: ["S1", "S10"] },
  { ...publicActive, id: "K12", title: "Ask Me 项目", keywords: ["ask me", "数字分身", "求职agent", "本项目"], relatedProject: "ask-me", content: "Ask Me 是面向 AI 产品经理招聘场景的求职数字分身，通过静态摘要、可追问对话、事实引用和状态管理，帮助招聘方快速获得可验证信息。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "负责需求洞察、PRD、信息架构、Claim-Source 模型、安全边界和工程验收。", aiAssistance: "AI 编程 Agent 参与代码生成、资料整理和测试。", limitations: "仍在持续更新，尚未提供招聘转化或大规模使用数据。", claimIds: ["C12"], supportsClaimIds: ["C12"], sourceIds: ["S2"] },
  { ...publicActive, id: "K22", title: "百度 AI 产品经理实习", keywords: ["百度", "baidu", "实习", "ai产品经理", "模型评测", "策略优化", "bad case", "行业研究"], relatedProject: "baidu-ai-coding-evaluation", content: "随后参与百度 AI 产品经理实习，工作主线包括执行模型或 Agent 版本评测、记录并横向比较结果、整理 Bad Case，以及把问题拆到模型、Prompt、检索、工具或评测器等环节。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "参与版本测试、结果分析、问题归因与评测材料沉淀。", aiAssistance: "模型和自动化工具是评测对象与执行工具，产品判断和结果边界由候选人负责。", limitations: "本轮只确认经历先后顺序，不推断精确起止日期；不公开具体业务线、模型版本、内部数据或保密材料。", claimIds: ["C13"], supportsClaimIds: ["C13"], sourceIds: ["S1", "S11", "S12"] },
  { ...publicActive, id: "K23", title: "AI Coding 七维评测与 Gate", keywords: ["ai coding", "七维", "指标", "权重", "gate", "硬门槛", "功能正确性", "视觉", "交互", "响应式", "可访问性", "代码质量"], relatedProject: "baidu-ai-coding-evaluation", content: "AI Coding Web 评测从用户能否获得可运行、可交互应用出发，设置功能正确性、端到端可用性、视觉美观度、交互体验、响应式适配、可访问性和代码质量七个维度；构建或启动失败、核心流程失败、白屏等情况由 Gate 保护核心可用性。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "参与指标、权重与 Gate 规则设计，并通过样例验证规则能否产生可解释证据。", aiAssistance: "确定性工具负责硬检查，LLM Judge 处理开放体验维度，人工负责校准。", limitations: "现有权重与门槛属于 MVP 规则，不是行业标准，仍需通过多任务 Pilot 和人工评分校准。", claimIds: ["C14"], supportsClaimIds: ["C14"], sourceIds: ["S1", "S11"] },
  { ...publicActive, id: "K24", title: "Evaluator Agent MVP", keywords: ["evaluator agent", "评测器", "mvp", "11阶段", "playwright", "axe-core", "三视口", "结构化报告", "dashboard", "90.9", "99.2", "76.0", "20项测试"], relatedProject: "baidu-ai-coding-evaluation", content: "Evaluator Agent MVP 以 Task Spec、候选项目、运行配置和 Rubric 为输入，依次完成任务解析、项目检查、依赖安装、构建、服务启动、HTTP 探活、浏览器加载、核心功能流、多视口与可访问性检查、Judge 评分归因和报告汇总。Dashboard 单样例得到 Final 90.9、Auto 99.2、Judge 76.0，20 项工程测试通过。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "参与 Benchmark 调研、流程与验收设计、MVP 实现验证、样例测试和交付材料整理。", aiAssistance: "Python、Playwright、axe-core 与日志提供确定性证据，LLM Judge 负责开放维度评分。", limitations: "结果仅证明单样例链路可运行、可留证；不代表生产平台、大规模模型比较或业务指标提升。", claimIds: ["C14", "C15"], supportsClaimIds: ["C14", "C15"], sourceIds: ["S1", "S11"] },
  { ...publicActive, id: "K25", title: "自动评测可信度与当前边界", keywords: ["可信", "一致性", "误报", "漏报", "黄金集", "judge", "校准", "稳定性", "边界", "局限", "重试", "人工"], relatedProject: "baidu-ai-coding-evaluation", content: "当前只能确认工程测试和单样例链路可运行，尚未形成完整的人机一致性、误报漏报、重复运行稳定性、成本和批量模型对比统计。可靠方案是固定 Judge 版本与参数，建立人工黄金集，区分工具失败与候选产品失败，并让冲突或低置信度结果转人工。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "明确评测器本身也需要被评测，并将可靠性校准作为 MVP 后续优先级。", aiAssistance: "LLM Judge 不是绝对真值，需要确定性证据、重复运行和人工仲裁共同约束。", limitations: "没有统计前不报告人机一致率、自动化率、ROI 或模型提升比例。", claimIds: ["C14", "C15"], supportsClaimIds: ["C14", "C15"], sourceIds: ["S11"] },
  { ...publicActive, id: "K26", title: "Coding Benchmark 调研", keywords: ["benchmark", "humaneval", "swe-bench", "web-bench", "webdevjudge", "fullstack bench", "13项", "行业研究"], relatedProject: "baidu-ai-coding-evaluation", content: "调研 13 项 Coding Benchmark，并按单函数或算法、仓库级修复、Web 或全栈项目、评测器可靠性四类整理。核心结论是公开 Benchmark 可以提供任务构造、可执行测试和环境复现方法，但真实 AI Coding 产品还要补充视觉、交互、用户可用性与业务边界。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "整理各 Benchmark 的任务、数据、指标、环境与局限，并提炼可迁移到业务评测的部分。", aiAssistance: "AI 可辅助资料整理，最终分类和业务取舍由候选人完成。", limitations: "不把 Benchmark 排行榜或论文结论当作本人项目成果；具体阅读深度以面试说明为准。", claimIds: ["C16"], supportsClaimIds: ["C16"], sourceIds: ["S1", "S11"] },
  { ...publicActive, id: "K27", title: "百川智能 AI 产品实习", keywords: ["百川", "百川智能", "实习", "医疗", "ai产品", "经历顺序", "工作内容"], relatedProject: "rag-knowledge-base", content: "在德勤 IT 审计之后、百度实习之前，候选人在百川智能 AI 产品部门参与医疗 RAG 实习，主要产出是企业级医疗知识库问答项目。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "本人确认任职顺序、AI 产品部门和医疗 RAG 方向。", aiAssistance: "无。", limitations: "未确认精确起止日期、汇报关系和任职证明信息，不进行推断。", claimIds: ["C17", "C18"], supportsClaimIds: ["C17", "C18"], sourceIds: ["S12"] },
  { ...publicActive, id: "K28", title: "医疗 RAG 产品架构与 MVP", keywords: ["医疗rag", "四层架构", "文档处理", "知识库管理", "问答层", "评测层", "mvp"], relatedProject: "rag-knowledge-base", content: "产品按用户任务拆为文档处理、知识库管理、检索问答和评测四层。P0 是知识入库、检索问答、来源返回和失败状态，先构成最短可信闭环，再扩展复杂配置。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "参与定义用户入口、流程状态、异常分支、配置边界、优先级和验收标准，并与算法、研发对齐。", aiAssistance: "模型承担问答与部分评测，产品职责不被模型替代。", limitations: "不把类名、接口或检索算法的实现归为个人独立开发；具体交付物只在能够现场出示时说明。", claimIds: ["C19"], supportsClaimIds: ["C19"], sourceIds: ["S12"] },
  { ...publicActive, id: "K29", title: "医疗 RAG 检索与来源链路", keywords: ["医疗rag", "dense", "稠密向量", "rerank", "gte-rerank", "来源片段", "top-k", "检索"], relatedProject: "rag-knowledge-base", content: "当前主链路是文档解析、切片和 Embedding 后写入 Milvus；提问时先做稠密向量召回，再用 Rerank 精排，将证据片段与短期上下文交给模型生成答案并返回来源片段。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "参与召回遗漏和排序错误场景梳理、检索参数与降级边界、对照指标和联调验收。", aiAssistance: "检索和生成由模型与工程组件执行，候选人负责产品规则与质量判断。", limitations: "当前不是 BM25 混合检索；PDF 页码高亮和一键定位原文尚未完整实现，来源片段不能被描述为彻底消除幻觉。", claimIds: ["C19", "C20"], supportsClaimIds: ["C19", "C20"], sourceIds: ["S12"] },
  { ...publicActive, id: "K30", title: "医疗 RAG 多助手与短期记忆", keywords: ["多助手", "assistant", "短期记忆", "redis", "session", "ttl", "滑动窗口", "prompt"], relatedProject: "rag-knowledge-base", content: "多助手允许按场景配置知识库、系统 Prompt、温度、检索参数和记忆参数；Redis 短期记忆按 session 隔离最近消息，用滑动窗口和 TTL 支持指代消解与连续追问。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "参与多助手配置边界、会话隔离、上下文长度和异常状态的产品设计与验收。", aiAssistance: "模型使用配置与短期上下文生成回答。", limitations: "当前可确认助手基础配置和短期记忆；版本持久化、长期记忆和完整 Agent 执行尚未完整落地。", claimIds: ["C19", "C20"], supportsClaimIds: ["C19", "C20"], sourceIds: ["S12"] },
  { ...publicActive, id: "K31", title: "医疗 RAG 四维评测闭环", keywords: ["rag评测", "faithfulness", "relevancy", "context precision", "accuracy", "qa数据集", "llm-as-judge", "报告"], relatedProject: "rag-knowledge-base", content: "当前支持 QA 数据生成或导入、人工编辑、批量运行 RAG、四维 LLM-as-Judge 打分与报告输出。四维为 Faithfulness、Relevancy、Context Precision 和 Accuracy，用于回归和趋势发现。", projectStatus: "in_progress", verification: "self_attested", candidateContribution: "参与 QA 数据和评测流程、指标含义、报告输出与人工校准边界的产品设计。", aiAssistance: "LLM-as-Judge 输出 0—10 分与理由，需固定模型、Prompt、温度和数据集版本。", limitations: "Judge 不是绝对真值；引用正确率、Context Recall、拒答正确率、持久化版本比较、回归门禁和专门 Bad Case 平台仍需补强。", claimIds: ["C19", "C20", "C21"], supportsClaimIds: ["C19", "C20", "C21"], sourceIds: ["S12"] },
] as const;

export const suggestedQuestionContent = [
  "60 秒了解张倬玮。",
  "他与 AI 产品经理岗位的匹配证据是什么？",
  "哪个公开项目最能代表他的 AI 产品能力？",
  "他的主要短板和待核实问题是什么？",
] as const;
