import { candidateNarrative } from "./narrative.ts";
import type { AnswerIntent, ResponseShape } from "../lib/types.ts";

const updated = "2026-08-13";
const publicActive = { visibility: "public", status: "active", lastUpdated: updated } as const;

type AnswerInput = {
  id: string;
  question: string;
  standardAnswer: string;
  details?: string[];
  limitations: string;
  claimIds: string[];
  sourceIds: string[];
  matchKeywords: string[];
  matchRequiresProjectContext?: boolean;
  evaluationGoal: string;
  exclusivePoints: string[];
  avoidRepeating: string[];
  responseShape: ResponseShape;
  targetLength: { min: number; max: number };
  preferredStoryIds: string[];
  followUpQuestions: string[];
  closingPurpose: string;
  verification?: "externally_verified" | "self_attested";
  relatedProject?: string;
  intent?: AnswerIntent;
  mustInclude?: string[];
  allowedFacts?: string[];
  allowedNumbers?: string[];
  allowedOrganizations?: string[];
  allowedProjectStatuses?: string[];
  boundaryTriggers?: string[];
  forbiddenDetails?: string[];
};

const answerIntentById: Record<string, AnswerIntent> = {
  A01: "introduction", A02: "role_fit", A03: "representative_project", A04: "project_problem",
  A05: "contribution", A06: "project_overview", A07: "ai_collaboration", A08: "skills",
  A09: "experience_value", A10: "experience", A11: "experience", A12: "project_overview",
  A13: "privacy", A14: "limitation", A15: "challenge", A16: "education",
  A17: "credentials", A18: "project_overview", A19: "result", A20: "hiring_recommendation",
  A21: "experience_value", A22: "experience_value", A23: "skills", A24: "result",
  A25: "experience", A26: "project_overview", A27: "skills", A28: "contribution",
  A29: "project_problem", A30: "limitation", A31: "project_overview", A32: "result",
  A33: "challenge", A34: "result", A35: "experience",
};

const knownOrganizations = ["东北大学", "百川智能", "百度", "德勤", "容诚", "ACCA"];
const defaultBoundaryTriggers = ["短板", "不足", "限制", "风险", "真实数据", "用户规模", "生产状态", "个人贡献", "未完成"];
const defaultForbiddenDetails = [
  "未在资料中出现的任职、日期或组织",
  "未在资料中出现的用户访谈、满意度、增长、效率或业务结果数字",
  "把规划中或待验证的能力描述为已经完成",
  "审计客户、底稿、企业机密或未公开个人信息",
  "未确认的占位经历",
];

function extractNumbers(values: string[]) {
  return [...new Set(values.flatMap((value) => value.match(/\b\d+(?:\.\d+)?%?\b/g) ?? []))];
}

function answer(input: AnswerInput) {
  const facts = [input.standardAnswer, ...(input.details ?? [])];
  const allowedOrganizations = input.allowedOrganizations
    ?? knownOrganizations.filter((organization) => facts.some((fact) => fact.includes(organization)));
  return {
    ...publicActive,
    ...input,
    verification: input.verification ?? "self_attested",
    supportsClaimIds: input.claimIds,
    requiredClaimIds: input.claimIds,
    requiredSourceIds: input.sourceIds,
    factSkeleton: {
      intent: input.intent ?? answerIntentById[input.id] ?? "general",
      thesis: input.standardAnswer.split(/\n\n/)[0],
      mustInclude: input.mustInclude ?? input.exclusivePoints,
      allowedFacts: input.allowedFacts ?? facts,
      allowedNumbers: input.allowedNumbers ?? extractNumbers(facts),
      allowedOrganizations,
      allowedProjectStatuses: input.allowedProjectStatuses ?? facts.filter((fact) => /MVP|原型|规划|验证阶段|已实现|已完成|持续优化/.test(fact)),
      boundaryTriggers: input.boundaryTriggers ?? defaultBoundaryTriggers,
      forbiddenDetails: [...defaultForbiddenDetails, ...(input.forbiddenDetails ?? [])],
    },
  };
}

export const stableAnswerContent = [
  answer({
    id: "A01",
    question: "请用 60 秒介绍张倬玮。",
    matchKeywords: ["60秒", "介绍", "自我介绍", "候选人定位", "简单说说自己"],
    standardAnswer: candidateNarrative.introductions.seconds60,
    details: [
      "身份与方向：东北大学应用统计学 2027 届学生，求职方向是 AI 产品经理。",
      "成长主线：应用统计学、财务与 IT 审计、百川医疗 RAG，再到百度模型评测。",
      "个人特质：持续学习、持之以恒，面对现场任务和反复迭代能够保持节奏。",
      "实习锚点：百川医疗 RAG、百度模型评测与 AI Coding Evaluator Agent MVP。",
    ],
    limitations: "不把单样例 MVP 描述为模型或业务指标提升，也不展开未确认的团队分工。",
    claimIds: ["C1", "C2", "C6", "C13", "C14", "C15", "C17", "C18"],
    sourceIds: ["S1", "S11", "S12"],
    evaluationGoal: "让面试官在一分钟内记住候选人的身份、成长路径、实践能力，以及持续学习、持之以恒和抗压的个人特质。",
    exclusivePoints: ["应用统计学到审计再到 AI 产品的成长主线", "数据评测、企业业务、产品落地", "持续学习、持之以恒和抗压能力"],
    avoidRepeating: ["项目技术栈", "项目完成边界", "完整贡献分工"],
    responseShape: "narrative",
    targetLength: { min: 430, max: 600 },
    preferredStoryIds: [],
    followUpQuestions: ["请介绍一下你的百度 AI 产品经理实习。", "哪个项目最能代表你的 AI 产品能力？", "你为什么适合 AI 产品经理岗位？"],
    closingPurpose: "总结过往经历体现出的持续学习、持之以恒、抗压能力和对结果负责的态度，不表达希望加入某类团队。",
  }),
  answer({
    id: "A02",
    question: "他为什么适合 AI 产品经理岗位？",
    matchKeywords: ["为什么适合", "为什么选择你", "选择你", "岗位匹配", "ai产品经理", "岗位优势", "入职", "团队做什么", "团队带来什么"],
    standardAnswer: "我适合 AI 产品经理岗位，核心不是单纯会使用模型，而是已经在真实业务里练习把需求、模型能力、质量验证和工程落地连起来。\n\n**真实 AI 产品闭环**：百川医疗 RAG 实习中，我参与需求与 MVP 梳理，把医疗私有文档问答拆成知识入库、检索、来源返回、短期记忆和评测，并与算法、研发对齐产品规则和验收边界。随后在百度，我进一步参与模型或 Agent 版本评测、Bad Case 归因，以及 AI Coding 七维指标、Gate 和 Evaluator Agent MVP 验证。\n\n**数据与证据意识**：应用统计学让我重视样本、指标和结论边界；财务与 IT 审计让我理解企业流程中的证据、权限、口径和人工复核。这些能力让我不会只看模型演示效果，而会追问回答是否有依据、结果是否可复现、风险是否被控制。\n\n**跨角色推进**：我能把业务目标翻译成需求、配置、异常状态和评测标准，再把 Bad Case 转成下一轮动作。我的优势不是把自己包装成算法或平台 Owner，而是在业务、模型和工程之间建立共同语言，帮助团队更快判断问题在哪里、方案是否值得继续投入。",
    details: ["百川医疗 RAG 的需求与评测闭环", "百度模型评测与 Bad Case 归因", "统计与审计形成的数据和风险意识", "连接业务、模型与工程"],
    limitations: "不把单样例 MVP 描述为模型效果或业务效率提升，也不夸大个人 Owner 身份。",
    claimIds: ["C2", "C6", "C13", "C14", "C17", "C19"],
    sourceIds: ["S1", "S11", "S12"],
    evaluationGoal: "把已有能力逐项映射到 AI 产品经理的实际工作，而不是重新介绍个人经历。",
    exclusivePoints: ["定义 AI 产品效果", "理解企业场景", "连接业务、模型与工程"],
    avoidRepeating: ["学校和毕业年份", "完整成长主线", "所有项目列表"],
    responseShape: "fit_mapping",
    targetLength: { min: 360, max: 480 },
    preferredStoryIds: ["ST9"],
    followUpQuestions: ["你在百度实习中具体负责什么？", "哪个项目最能代表你的 AI 产品能力？", "你如何评估并改进 AI 产品效果？"],
    closingPurpose: "说明入职后如何帮助团队更快验证产品方向。",
  }),
  answer({
    id: "A03",
    question: "哪个项目最能代表他的 AI 产品能力？",
    matchKeywords: ["代表项目", "最能代表", "ai产品能力", "哪个公开项目最能代表"],
    standardAnswer: "最能代表我 AI 产品能力的是百川智能实习中的 RAG Knowledge Base System。它面向**医疗私有文档可信问答**，核心不是再做一个聊天界面，而是帮助使用者更快从指南、共识、论文等资料中获得有来源、可核验的答案，同时明确它只辅助资料查阅，不替代诊断。\n\n**从需求到四层架构**：我参与把产品拆成文档处理、知识库管理、检索问答和评测四层，并将 P0 收敛为知识入库、检索问答、来源返回和失败状态。这样产品价值、异常分支和验收标准可以与算法、研发逐项对齐。\n\n**从检索到评测闭环**：公开脱敏项目已跑通 Dense Retrieval、Rerank、来源片段、Redis 短期记忆、多助手基础配置，以及 Faithfulness、Relevancy、Context Precision、Accuracy 四维评测。我参与需求与 MVP 梳理、功能和配置边界、QA 数据与评测闭环；AI 工具辅助公开 Demo 的重构，但产品取舍和质量边界由我负责。\n\n我会准确区分事实：公开仓库不是百川生产代码，BM25 混合检索、长期记忆、完整 Agent、持久化版本比较和生产级 RBAC 尚未完整落地，也没有可公开的真实客户效果数据。这个项目体现了我把高风险行业的模糊需求转成可运行、可核验、可迭代产品闭环的能力。",
    details: ["百川医疗私有文档可信问答", "四层产品架构与 P0", "Dense、Rerank、来源和四维评测", "脱敏 Demo 与生产边界"],
    limitations: "公开仓库是百川实习业务场景的脱敏重构，不是公司生产代码；不公开客户、内部模型、生产规模和真实效果。",
    claimIds: ["C3", "C17", "C18", "C19", "C20", "C21"],
    sourceIds: ["S3", "S12"],
    verification: "self_attested",
    relatedProject: "rag-knowledge-base",
    evaluationGoal: "用 RAG 项目证明候选人的问题定义、方案取舍、评测设计与工程落地能力。",
    exclusivePoints: ["医疗私有文档可信问答", "四层架构与评测闭环", "脱敏项目和事实边界"],
    avoidRepeating: ["完整自我介绍", "百度 Evaluator Agent 细节", "未验证的准确率或业务提升"],
    responseShape: "project_arc",
    targetLength: { min: 390, max: 520 },
    preferredStoryIds: ["ST10", "ST1"],
    followUpQuestions: ["你在 RAG 项目中具体负责什么？", "为什么先选择 Dense Retrieval？", "你如何评估 RAG 回答质量？"],
    closingPurpose: "落到问题定义、质量基线、迭代取舍和可核验边界。",
  }),
  answer({
    id: "A04",
    question: "RAG 项目解决了什么问题？",
    matchKeywords: ["rag解决", "rag项目解决", "知识库问题", "服务什么用户", "解决什么问题", "有什么价值"],
    standardAnswer: "我在百川参与的医疗 RAG 产品，解决的是**医疗文档答案难核验**的问题。指南、共识、论文、药品说明书和内部制度等资料分散且持续更新，传统关键词搜索需要反复换词和逐篇查找；直接让模型回答，又可能给出流畅但缺少依据的结论。\n\n**可追溯辅助查阅**：产品先完成文档解析、切片和向量化，再通过 Dense Retrieval 与 Rerank 找到证据片段，将证据和短期上下文交给模型生成回答，并返回来源片段。QA 数据与四维评测继续检查回答是否忠于上下文、是否直接回应问题、召回片段是否相关，以及与参考答案是否一致。\n\n它的价值是降低专业资料查找和依据核验成本，而不是替代医生诊断。公开项目是业务场景的脱敏重构；当前能说明来源片段返回，不能把 PDF 页码高亮、一键定位或生产效果说成已经完成。",
    details: ["专业资料难以快速找到正确内容", "生成结论缺少原文依据", "摄入、检索、生成和评测链路"],
    limitations: "公开仓库证明当前设计与部分实现，不等同于所有规划能力均已运行验证。",
    claimIds: ["C3", "C18", "C20", "C21"], sourceIds: ["S3", "S12"], verification: "self_attested", relatedProject: "rag-knowledge-base",
    evaluationGoal: "讲清用户问题和产品目标，不展开个人贡献或技术选型细节。",
    exclusivePoints: ["资料分散且可信答案难获取", "回答缺少可追溯依据", "降低资料查找和依据核验成本"],
    avoidRepeating: ["个人三项优势", "完整评测方法", "AI 编程分工"],
    responseShape: "direct", targetLength: { min: 280, max: 400 }, preferredStoryIds: [],
    followUpQuestions: ["为什么先选择 Dense Retrieval？", "你如何判断回答是否可靠？", "这个项目目前做到什么阶段？"],
    closingPurpose: "回到用户获取可信答案的成本。",
  }),
  answer({
    id: "A05",
    question: "他在 RAG 项目中的个人贡献是什么？",
    matchKeywords: ["rag贡献", "rag个人贡献", "rag负责", "具体做了什么", "个人具体完成", "你做了什么", "你负责什么", "你的贡献", "如何评测", "用于评测", "ragas", "评测设计"],
    standardAnswer: "我在百川医疗 RAG 项目中的核心贡献，是把业务需求、产品规则和质量验证连成闭环，而不是把所有算法或代码都归到自己名下。\n\n**需求与 MVP**：我参与梳理医疗私有文档问答中的知识库管理、幻觉风险和来源核验需求，把最小闭环收敛为知识入库、检索问答、来源返回和失败状态。\n\n**功能与协作边界**：我参与文档处理、知识库、稠密召回与 Rerank、短期记忆、多助手配置等功能设计，重点定义用户入口、流程状态、配置边界、异常分支和验收标准，并与算法和研发对齐。我的职责不是独立实现检索算法，而是让技术组件服务于清楚的用户任务。\n\n**评测闭环**：我还参与 QA 数据生成或导入、人工编辑、批量运行和 Faithfulness、Relevancy、Context Precision、Accuracy 四维评测与报告，让失败样本能够回到召回、排序或生成环节。公开 Demo 使用外部模型和 AI 工具做脱敏重构，但需求取舍、评测标准和事实边界由我负责。",
    details: ["梳理医疗问答需求与 MVP", "定义功能、配置和异常边界", "与算法研发对齐检索问答", "参与 QA 四维评测闭环"],
    limitations: "不虚构个人独立实现检索算法或全部工程代码，也不披露客户、内部模型和生产资料。",
    claimIds: ["C17", "C18", "C19", "C20", "C21"], sourceIds: ["S12"], relatedProject: "rag-knowledge-base",
    evaluationGoal: "区分产品决策、工程协作和最终责任，回答本人真正做了什么。",
    exclusivePoints: ["产品目标与主链路由本人定义", "迭代顺序和评测由本人设计", "AI 辅助实现但本人负责验收"],
    avoidRepeating: ["重新解释项目背景", "三项候选人优势", "虚构代码占比"],
    responseShape: "contribution", targetLength: { min: 420, max: 560 }, preferredStoryIds: ["ST10", "ST1"],
    followUpQuestions: ["你做过最关键的一次取舍是什么？", "如果检索效果不好，你会如何定位？", "AI 生成的代码你怎么验收？"],
    closingPurpose: "明确本人对产品判断和最终质量负责。",
  }),
  answer({
    id: "A06",
    question: "DeepFlow 是什么？",
    matchKeywords: ["deepflow", "deepflow是什么", "deepflow介绍", "研究工作台"],
    standardAnswer: "DeepFlow 是我围绕**复杂研究任务**设计的多 Agent 工作台。它要解决的问题是：如果把一个开放研究题一次性交给模型，任务很容易在中途跑偏，使用者既不知道它正在做什么，也很难判断最终结论是怎样形成的。\n\n我的产品思路不是简单增加 Agent 数量，而是先把研究过程拆成任务澄清、计划、检索、分析和报告等阶段，再让 Coordinator、Planner、Researcher、Coder 和 Reporter 承担不同职责。对于研究计划和方向调整这类高成本节点，我加入**人工确认**；对于检索和分析过程，则通过事件记录和引用保留可追踪性。\n\n当前 DeepFlow 已经形成从任务澄清到报告输出的**可演示 MVP**。这个项目让我更具体地理解：Agent 产品的价值不只来自自主执行，还来自过程是否可见、关键节点是否可控，以及最终成果能否沉淀为可检查、可继续使用的资产。",
    details: ["复杂研究任务容易失控", "按计划、检索、分析和报告拆分 Agent", "高成本节点加入人工确认", "形成可演示 MVP"],
    limitations: "不声称已经形成真实用户规模、生产并发或长期稳定性数据。",
    claimIds: ["C4"], sourceIds: ["S4"], verification: "externally_verified", relatedProject: "deepflow",
    evaluationGoal: "让面试官理解 DeepFlow 的用户问题、核心机制和产品价值。",
    exclusivePoints: ["开放研究任务容易跑偏", "Agent 分工与人工确认", "研究过程可追踪"],
    avoidRepeating: ["RAG 项目评测链路", "完整个人优势", "所有规划功能"],
    responseShape: "project_arc", targetLength: { min: 330, max: 460 }, preferredStoryIds: ["ST2"],
    followUpQuestions: ["为什么需要人工确认？", "Agent 之间如何协作？", "这个项目最大的挑战是什么？"],
    closingPurpose: "突出 Agent 产品的可控性和成果物沉淀。",
  }),
  answer({
    id: "A07",
    question: "他如何使用 AI 编程工具？",
    matchKeywords: ["ai编程", "如何使用ai", "ai辅助", "ai编程占比", "ai写了多少", "代码是不是ai写的"],
    standardAnswer: "我会直接承认 AI 编程工具深度参与了项目实现，但它没有替我承担**产品责任**。我的分工很明确：我负责定义要解决的问题、拆解任务、选择方案、制定验收标准，并判断结果是否真的可用；AI 主要作为**工程协作者**，帮助生成代码、补测试、定位错误和整理文档。\n\n在具体协作中，我会先把需求、接口和不能破坏的约束写清楚，再让 AI 处理边界明确的实现任务。生成结果出来后，我不会只看“代码能不能运行”，还会检查它是否符合用户流程、有没有引入新的事实或安全风险、是否保持现有接口兼容，以及失败时有没有稳定回退。关键改动必须经过自动测试、Lint、Build 和实际流程验收。\n\n如果结果偏离需求，我会回到问题定义重新拆解，而不是继续让模型盲目修改。我不虚构统一的代码贡献比例，因为不同任务差异很大；但需求判断、方案取舍和**最终质量责任**始终在我。这也是我理解的 AI 原生产品能力：提高实现速度，同时保留人的判断和验收。",
    details: ["AI 深度参与实现但不承担产品责任", "本人负责问题、方案、验收和质量", "通过测试、Lint、Build 与流程检查验收", "不虚构固定贡献比例"],
    limitations: "不同项目的具体代码分工不同，没有统一百分比。",
    claimIds: ["C2", "C3", "C4", "C5", "C7", "C12"], sourceIds: ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9"],
    evaluationGoal: "坦诚说明 AI 参与程度，同时证明本人掌握产品判断和质量控制。",
    exclusivePoints: ["AI 深度参与工程实现", "本人负责需求、取舍和验收", "用工程门禁而非运行结果验收"],
    avoidRepeating: ["重新介绍所有项目", "回避 AI 参与", "虚构代码比例"],
    responseShape: "direct", targetLength: { min: 360, max: 500 }, preferredStoryIds: ["ST3"],
    followUpQuestions: ["举一个 AI 生成结果不符合预期的例子。", "你如何判断原型已经可以交付？", "你和工程师相比的定位是什么？"],
    closingPurpose: "把 AI 协作能力落到产品责任和质量控制。",
  }),
  answer({
    id: "A08",
    question: "他的核心技术能力有哪些？",
    matchKeywords: ["技术能力", "技术栈", "会什么", "技能如何", "sql", "python", "fastapi"],
    standardAnswer: "我的技术能力主要服务于**产品判断和快速验证**，而不是和纯工程师比较底层开发深度。\n\n数据侧，我可以使用 SQL、Python 处理数据、理解指标并检查数据质量；AI 应用侧，我熟悉 RAG、Prompt、工作流、评测集与 RAGAS 等方法，能够把一个模型能力拆成检索、生成、引用和评测环节；工程侧，我能理解 FastAPI、Milvus、前端、异步任务和部署链路，也能借助 AI 编程工具把需求推进成可运行原型。\n\n这种**技术宽度**对产品工作有两个直接价值。第一，我与算法和工程同学沟通时能够理解实现约束，不会提出完全脱离数据和系统条件的需求；第二，我可以在需求阶段提前定义输入、接口、异常状态和验收方式，并亲自验证关键流程。我的定位不是替代工程师，而是把业务问题翻译成团队能够实现、测试和**持续迭代**的产品方案。",
    details: ["SQL 与 Python 数据处理", "RAG、Prompt、工作流和评测", "理解应用工程与部署链路", "把业务问题转成实现和验收要求"],
    limitations: "不把产品工程能力包装为纯工程师的底层技术深度。",
    claimIds: ["C2", "C3", "C4", "C5"], sourceIds: ["S1", "S3", "S4", "S5"],
    evaluationGoal: "说明技术能力如何服务产品工作，而不是罗列技术名词。",
    exclusivePoints: ["数据处理与指标理解", "AI 应用链路理解", "把技术约束转成产品和验收要求"],
    avoidRepeating: ["完整成长经历", "审计职责", "项目完成边界"],
    responseShape: "fit_mapping", targetLength: { min: 320, max: 450 }, preferredStoryIds: [],
    followUpQuestions: ["你如何设计 AI 产品评测？", "你能独立完成什么程度的原型？", "你如何与工程团队协作？"],
    closingPurpose: "明确技术能力在产品团队中的实际用途。",
  }),
  answer({
    id: "A09",
    question: "审计经历如何帮助他做 AI 产品？",
    matchKeywords: ["审计经历", "审计帮助", "业务理解"],
    standardAnswer: "审计经历给我的最大帮助，不是增加一个行业标签，而是让我习惯从真实流程、**证据和风险**出发看产品。做审计时，我需要关注数据从哪里来、经过哪些处理、过程有没有留下证据、异常如何被发现，以及最终结果能否被另一个人复核。\n\n这些习惯可以直接迁移到企业 AI 产品。设计知识库时，我会关注答案是否基于正确内容、引用能否支持结论；设计 Agent 工作流时，我会区分哪些任务可以自动执行、哪些高成本节点必须**人工确认**；处理企业数据时，我会先界定授权、使用范围和输出边界。与此同时，审计现场也让我看到，很多流程问题不在于缺少功能，而在于资料分散、交接成本高、异常确认反复。\n\n因此，相比只从模型能力出发，我会更早判断一个方案在真实业务中是否可用、可控、可复核，以及它是否真的降低一线执行成本。这种**企业流程理解**，是我做 B 端 AI 产品时很重要的差异点。",
    details: ["从真实流程和风险看产品", "关注数据来源、证据、异常和复核", "迁移到引用、人审与权限设计", "提前识别企业落地成本"],
    limitations: "不披露审计客户、底稿和企业机密。",
    claimIds: ["C6", "C7", "C9", "C10"], sourceIds: ["S1", "S8", "S9"],
    evaluationGoal: "证明审计经验如何转化为企业 AI 产品方法。",
    exclusivePoints: ["流程与风险意识", "证据链和可复核性", "企业 AI 的人审与数据边界"],
    avoidRepeating: ["重新介绍学校", "完整项目列表", "任职数字"],
    responseShape: "fit_mapping", targetLength: { min: 340, max: 480 }, preferredStoryIds: ["ST4", "ST6"],
    followUpQuestions: ["举一个审计问题转成产品的例子。", "这如何影响你的 Agent 设计？", "你如何处理企业数据边界？"],
    closingPurpose: "突出企业方案的可用、可控和可复核。",
  }),
  answer({
    id: "A10",
    question: "他的德勤 IT 审计实习做了什么？",
    matchKeywords: ["德勤实习", "it审计实习", "ipe"],
    standardAnswer: "我在 2026 年 1 月至 4 月参与德勤 IT 审计实习，工作主要涉及**IPE 与日志核查**。具体来说，我需要按照既定审计程序核对系统输出和相关资料，检查记录之间是否一致，并在口径不清楚或信息不完整时进一步确认。\n\n这段经历让我比较具体地理解了企业系统中的**数据来源和证据链**。一个结果是否可信，往往不只取决于最后一张报表，还取决于数据从哪里产生、经过哪些处理、谁在什么节点确认，以及异常是否被完整记录。它也让我意识到，企业产品不能只追求功能可用，还要考虑结果是否可追溯、错误能否被及时发现，以及敏感数据应该如何被限制使用。\n\n这些认识后来直接影响了我的 AI 产品设计：知识库需要引用支持，Agent 的关键动作需要人审，模型处理的数据也必须有清晰边界，也就是把**引用支持与人审**直接放进产品流程。",
    details: ["2026 年 1 月至 4 月德勤 IT 审计实习", "IPE 与日志核查", "理解企业系统数据来源和证据链", "迁移到引用、人审和数据边界"],
    limitations: "不披露客户、系统明细、底稿或企业机密。",
    claimIds: ["C9"], sourceIds: ["S1"],
    evaluationGoal: "讲清职责和能力迁移，不把实习包装成 AI 产品任职。",
    exclusivePoints: ["IPE 与日志核查职责", "企业系统数据与证据链", "对 AI 产品可靠性的影响"],
    avoidRepeating: ["财务审计职责", "项目技术栈", "客户和底稿"],
    responseShape: "direct", targetLength: { min: 300, max: 420 }, preferredStoryIds: ["ST6"],
    followUpQuestions: ["IT 审计和财务审计最大的差异是什么？", "这段经历如何影响你的产品设计？", "你如何保护企业敏感数据？"],
    closingPurpose: "落到企业 AI 产品的可靠性意识。",
  }),
  answer({
    id: "A11",
    question: "他的容诚审计实习做了什么？",
    matchKeywords: ["容诚实习", "财务审计实习", "函证盘点"],
    standardAnswer: "我在 2025 年 1 月至 3 月参与容诚财务审计实习，主要接触**底稿、函证和盘点**等基础审计工作。现场工作让我看到，一项看起来简单的流程，背后往往包含资料收集、多人协作、异常确认和结果留痕；真正消耗时间的，也常常不是某个复杂判断，而是信息格式不一致、上下文缺失和反复确认。\n\n这段经历对我做产品最直接的影响，是让我更关注**一线执行成本**。设计企业工具时，我不会只问功能能不能实现，还会考虑资料如何进入系统、用户在哪一步最容易出错、系统应该给出建议还是直接执行、哪些结果必须人工确认，以及操作之后能否留下可复核记录。\n\n它也为我后来把审计资料整理和日志核查抽象成产品原型提供了业务基础：先找到重复而高频的环节，再用规则、OCR 或模型能力降低整理成本，同时保留必要的**人审和数据边界**。",
    details: ["2025 年 1 月至 3 月容诚财务审计实习", "底稿、函证和盘点", "理解现场协作和执行成本", "形成审计工具的业务基础"],
    limitations: "不披露客户、底稿或业务数据。",
    claimIds: ["C10"], sourceIds: ["S1"],
    evaluationGoal: "讲清财务审计的一线业务理解如何迁移到产品。",
    exclusivePoints: ["底稿、函证和盘点职责", "一线执行与协作成本", "审计工具的场景来源"],
    avoidRepeating: ["IT 审计职责", "技术组件", "客户和业务数据"],
    responseShape: "direct", targetLength: { min: 300, max: 430 }, preferredStoryIds: ["ST4"],
    followUpQuestions: ["你从审计中发现了什么产品机会？", "你如何判断一个流程值得被 AI 改造？", "你做过哪些审计工具？"],
    closingPurpose: "落到一线业务理解和产品机会识别。",
  }),
  answer({
    id: "A12",
    question: "他有哪些本地优先产品？",
    matchKeywords: ["本地优先", "效率工具", "桌面产品", "downloadsbutler", "downloadbutler", "thirtyminutebrain", "readlaterregret"],
    standardAnswer: "我做过 Thirty-Minute Brain、Read-Later Regret 和 Downloads Butler 三个本地优先工具，分别处理**上下文恢复**、**信息债管理**和**下载文件整理**。它们不是三个孤立的技术练习，而是同一种产品方法的不同验证：从自己高频遇到的小摩擦出发，先找到最小闭环，再决定是否值得继续扩展。\n\nThirty-Minute Brain 关注的是工作被打断后如何快速恢复上下文；Read-Later Regret 处理“收藏很多、真正消化很少”的信息债；Downloads Butler 则把混乱的下载目录转成可确认的整理建议。三个工具都强调用户控制：数据尽量留在本地，文件移动或自动处理前保留确认，敏感内容不为了便利默认上传。\n\n这些项目让我形成了一个很实用的习惯：先用轻量方案验证高频问题，把隐私、误操作和撤销机制直接写进产品流程，再根据真实使用决定要不要搭建更复杂的平台。",
    details: ["三个本地优先效率工具", "从高频小摩擦出发", "数据留在本地并保留用户控制", "先验证轻量闭环"],
    limitations: "不声称拥有公开用户规模、留存或长期价值数据。",
    claimIds: ["C5"], sourceIds: ["S1", "S5", "S6", "S7"], verification: "externally_verified", relatedProject: "local-first-tools",
    evaluationGoal: "展示从小问题快速验证产品闭环和隐私约束的能力。",
    exclusivePoints: ["三个具体小问题", "本地优先与用户控制", "轻量验证方法"],
    avoidRepeating: ["RAG 评测", "审计职责", "生产规模"],
    responseShape: "project_arc", targetLength: { min: 330, max: 460 }, preferredStoryIds: ["ST5"],
    followUpQuestions: ["为什么选择本地优先？", "哪个工具最值得继续做？", "你如何避免文件工具误操作？"],
    closingPurpose: "体现轻量验证和隐私默认设计。",
  }),
  answer({
    id: "A13",
    question: "他如何处理隐私和企业数据？",
    matchKeywords: ["隐私", "企业数据", "数据边界", "机密"],
    standardAnswer: "我处理隐私和企业数据的原则是：**先确认数据资格**，再讨论模型能做什么。具体设计时，我会依次确认数据来源与授权、完成任务所需的**最小使用范围**、数据在哪里处理、结果会被发送到哪里，以及出现异常后能否追溯和撤回。\n\n在本地优先工具中，我尽量让数据保留在设备内，并在文件移动或自动处理前保留用户确认；在审计相关原型中，我只使用演示数据，不接触真实客户资料；在 Agent 或知识库流程中，则通过人工确认、引用支持和明确的输出边界降低误用风险。如果某项功能必须依赖更敏感的数据，我会先判断能否通过脱敏、范围缩小或本地处理实现，而不是默认把数据交给模型。\n\n对企业 AI 产品来说，隐私不是上线前补充的一页说明，而是需求范围、交互流程、权限和异常处理共同组成的**产品约束**。",
    details: ["先判断数据能否进入系统", "关注授权、范围、位置和输出", "本地优先与演示数据", "隐私作为产品流程"],
    limitations: "不披露审计客户、底稿、企业机密或未公开个人信息。",
    claimIds: ["C7", "C12"], sourceIds: ["S1", "S2", "S8", "S9"],
    evaluationGoal: "说明可操作的隐私产品原则，而不是复述拒答政策。",
    exclusivePoints: ["先判断数据使用资格", "本地优先和演示数据", "隐私进入产品流程"],
    avoidRepeating: ["完整审计经历", "模型技术细节", "安全认证"],
    responseShape: "direct", targetLength: { min: 300, max: 430 }, preferredStoryIds: ["ST5"],
    followUpQuestions: ["Agent 产品中哪些节点需要人工确认？", "你如何处理模型输出风险？", "本地优先有什么取舍？"],
    closingPurpose: "强调隐私是产品设计约束。",
  }),
  answer({
    id: "A14",
    question: "他的主要短板是什么？",
    matchKeywords: ["短板", "不足", "能力缺口"],
    standardAnswer: "我目前最需要补强的，是把原型阶段的产品判断延伸到真实用户、长期运营和跨团队协作中。现阶段我已经能独立完成问题拆解、方案取舍、原型推进和评测迭代，但还缺少在较长周期里持续观察用户行为、生产稳定性和商业结果的完整经历。\n\n**原型不等于产品成功**：如果只停留在原型阶段，容易高估功能完成度，却低估推广成本、协作阻力和长期维护。因此我会主动区分“功能可用”“用户愿意用”和“业务值得持续投入”，不会把一次演示成功直接等同于产品成功。\n\n**用行为和结果验证**：进入真实业务团队后，我希望主动参与用户访谈、指标定义、上线复盘和跨职能推进，让每轮需求都能回到行为与结果上验证。同时我现在就能贡献快速拆解复杂问题、建立最小验证方案和用 Bad Case 推动迭代的能力。这个短板说明我的经验边界，也说明我下一阶段的成长方向非常明确。",
    details: ["真实用户结果积累不足", "长期生产稳定性经验不足", "复杂跨团队推进经验仍需补强", "通过真实业务、指标和复盘补强"],
    limitations: "短板来自当前经历阶段，不等于完全不具备相关能力。",
    claimIds: ["C8"], sourceIds: ["S1", "S10"],
    evaluationGoal: "展现自我认知、影响判断和具体补强行动，不自我否定。",
    exclusivePoints: ["真实用户与长期协作积累不足", "原型完成不等于产品成功", "进入真实团队补强"],
    avoidRepeating: ["再次罗列全部优势", "公开证据措辞", "免责声明"],
    responseShape: "shortcoming", targetLength: { min: 330, max: 460 }, preferredStoryIds: [],
    followUpQuestions: ["你准备如何验证真实用户价值？", "你希望入职后优先补哪项能力？", "你如何看待原型和产品成功的差别？"],
    closingPurpose: "把短板转成明确的成长计划和初级岗位价值。",
  }),
  answer({
    id: "A15",
    question: "请讲一个项目挑战或失败案例。",
    matchKeywords: ["面试核实", "追问", "遇到什么困难", "项目困难", "失败案例", "项目挑战", "挑战", "失败", "最难的取舍"],
    standardAnswer: "医疗 RAG 项目中一个典型挑战，是同时有知识入库、召回、Rerank、来源返回、记忆和评测等多条链路，如果只看功能数量，Bad Case 很难定位到具体环节。\n\n**可解释的检索基线**：我参与把验证顺序拆开，先固定文档处理和 Dense Retrieval，检查证据是否被召回；再单独接入 Rerank，判断前排证据质量是否改善；最后结合回答忠实度、来源支持和四维评测观察生成结果。BM25 继续作为后续对照，而不是和其他变量一起修改。\n\n**单变量验证**：出现问题时分别检查摄入、召回、排序、生成和 Judge，并让 QA 数据与 Bad Case 回到下一轮任务。这个过程让我认识到，AI 产品经理的重要工作不是追求功能越多越好，而是控制变量、管理不确定性，并让团队清楚每次投入究竟验证什么。",
    details: ["多链路并行导致 Bad Case 难定位", "固定 Dense Retrieval 基线", "单独验证 Rerank 和生成", "用 QA 与四维评测回流"],
    limitations: "这是方案取舍与复盘，不虚构线上事故或业务损失。",
    claimIds: ["C3", "C19", "C20", "C21"], sourceIds: ["S3", "S12"], relatedProject: "rag-knowledge-base",
    evaluationGoal: "用真实方案调整证明复盘、控制变量和产品取舍能力。",
    exclusivePoints: ["功能堆叠造成问题定位困难", "建立基线并控制变量", "从功能数量转向质量验收"],
    avoidRepeating: ["泛泛谈产品闭环", "重新介绍 RAG 背景", "虚构线上事故"],
    responseShape: "star", targetLength: { min: 420, max: 560 }, preferredStoryIds: ["ST1", "ST8"],
    followUpQuestions: ["你为什么选择先保留 Dense Retrieval？", "如果再次做这个项目会如何规划？", "DeepFlow 中有类似的取舍吗？"],
    closingPurpose: "落到控制变量和明确取舍的产品能力。",
  }),
  answer({
    id: "A16",
    question: "他的教育背景是什么？",
    matchKeywords: ["教育背景", "学校专业", "东北大学"],
    standardAnswer: "我就读于东北大学应用统计学专业，预计 2027 年毕业。\n\n**指标、样本与误差**：这个背景对我做 AI 产品最直接的帮助，不只是会处理数据，而是让我习惯先明确问题与评价标准，再选择样本、指标和方法，最后关注误差与结论是否可靠。\n\n**评测与迭代分析**：概率统计、数据库和编程相关学习，让我能理解评测结果、数据质量以及技术方案的基本约束。面对模型效果时，我不会只看几个表现好的案例，而会进一步追问样本是否有代表性、指标是否对应真实目标、Bad Case 是否暴露了系统性问题。对我来说，应用统计学不是简历上的专业标签，而是我做 AI 产品评测、需求判断和迭代分析的底层训练。",
    details: ["东北大学应用统计学专业", "预计 2027 年毕业", "形成指标和数据判断习惯"],
    limitations: "教育信息以正式学籍或简历为准。",
    claimIds: ["C1"], sourceIds: ["S1"],
    evaluationGoal: "说明教育背景及其对 AI 产品工作的实际帮助。",
    exclusivePoints: ["应用统计学背景", "指标与数据判断习惯", "评测思维基础"],
    avoidRepeating: ["完整自我介绍", "审计经历", "项目技术栈"],
    responseShape: "direct", targetLength: { min: 240, max: 360 }, preferredStoryIds: [],
    followUpQuestions: ["统计学如何帮助你设计评测？", "你最擅长的数据工具是什么？", "为什么从统计学转向 AI 产品？"],
    closingPurpose: "把专业背景落到评测思维。",
  }),
  answer({
    id: "A17",
    question: "他的英语和证书情况如何？",
    matchKeywords: ["英语", "四六级", "acca", "证书"],
    standardAnswer: "我的 CET-4 成绩是 619，CET-6 是 520，并完成了部分 ACCA 科目学习。对我而言，这些经历的价值不在于单纯罗列证书，而在于它们能直接支持 AI 产品工作。\n\n**英语能力**让我可以直接阅读海外模型文档、开源项目说明、AI 产品案例和工程资料，减少经过二手转述后的信息损耗，也便于持续跟踪模型能力与产品范式的变化。**ACCA 和会计学习**则让我更容易理解财务流程、业务指标、控制要求和企业沟通语言。两者结合后，我能更快建立**技术与业务连接**，这也是我进入企业 AI 场景时的一项基础能力。",
    details: ["CET-4 619", "CET-6 520", "部分 ACCA 科目", "支持阅读技术资料和理解企业业务"],
    limitations: "成绩与科目完成情况以正式材料为准。",
    claimIds: ["C1", "C2"], sourceIds: ["S1"],
    evaluationGoal: "说明英语和证书如何支持工作，不罗列无关荣誉。",
    exclusivePoints: ["英语阅读技术资料", "ACCA 支持企业业务理解"],
    avoidRepeating: ["学校背景", "项目经历", "三项个人优势"],
    responseShape: "direct", targetLength: { min: 230, max: 350 }, preferredStoryIds: [],
    followUpQuestions: ["你通常如何跟踪海外 AI 产品？", "财务知识如何帮助你理解 B 端场景？", "你最近在学习什么？"],
    closingPurpose: "落到技术信息获取和企业语境理解。",
  }),
  answer({
    id: "A18",
    question: "Ask Me 项目体现了什么能力？",
    matchKeywords: ["ask me能力", "数字分身", "本项目能力"],
    standardAnswer: "Ask Me 最能体现的是我如何把一个模糊的求职目标，拆成一套完整的 AI 产品闭环，而不是只做一个聊天页面。传统简历的信息密度有限、不能继续追问，候选人的项目判断和个人贡献也很难在短时间内讲清楚。因此我先从招聘方的决策过程出发，明确产品要帮助对方完成“快速了解—重点追问—判断是否进入下一轮—查看简历或联系”的路径。\n\n**事实门禁与稳定回退**：我把个人经历、项目和 STAR 故事整理为结构化知识，并设计核心问题、上下文指代、事实门禁和稳定回退，让数字分身既敢于表达，也不虚构一问即穿的结果。\n\n**自动评测与模拟面试**：我接入模型、限流、预算、匿名事件和固定简历入口，再通过自动评测和模拟面试持续发现回答重复、过度保守或重点不清的问题。我也会根据不同提问意图重新分配内容，避免每个答案都重复三项优势。这个项目体现的不只是实现能力，更是我从用户决策出发定义产品、平衡表现力与可信度，并持续验收体验的能力。",
    details: ["从招聘决策路径定义产品", "结构化知识、稳定回答和事实门禁", "模型、限流、分析与简历链路", "通过评测持续修正回答体验"],
    limitations: "项目仍需真人招聘者验证实际面试转化价值。",
    claimIds: ["C12"], sourceIds: ["S2"], relatedProject: "ask-me",
    evaluationGoal: "证明从招聘问题到 AI 产品闭环的完整设计能力。",
    exclusivePoints: ["招聘决策路径", "回答、工程和转化三层设计", "根据评测修正产品方向"],
    avoidRepeating: ["完整自我介绍", "RAG 项目细节", "无关技术栈"],
    responseShape: "project_arc", targetLength: { min: 380, max: 520 }, preferredStoryIds: ["ST3", "ST8"],
    followUpQuestions: ["你为什么要做这个项目？", "你如何判断回答质量？", "这个项目目前最大的不足是什么？"],
    closingPurpose: "落到需求洞察、产品取舍和持续验收。",
  }),
  answer({
    id: "A19",
    question: "公开项目是否有真实用户增长数据？",
    matchKeywords: ["用户增长", "用户规模", "真实用户", "用户测试", "满意度", "服务什么用户", "什么用户", "业务价值", "解决什么业务问题", "目前有什么价值", "留存数据", "结果如何", "项目结果", "生产状态"],
    standardAnswer: "目前我的公开项目主要完成了问题定义、核心流程和可演示原型，还没有形成可以公开说明的用户增长、留存、满意度或商业化数据。已经完成并可以展示的，是 RAG 的文档摄入—检索—生成主链路、DeepFlow 的研究工作台 MVP，以及多个本地优先工具从输入到输出的完整使用流程。\n\n**可运行、可检查**：这些成果证明我能够把一个业务观察转成明确方案，完成关键取舍，并把方案推进到可运行、可检查的阶段；但这还不能替代真实市场验证。\n\n**真实行为验证**：我会先选择目标用户和高频任务，让他们在尽量少解释的情况下独立完成流程，再记录任务完成情况、关键阻力、重复使用意愿和 Bad Case。之后根据结果判断是优化核心路径、收缩需求，还是继续投入高级能力。相比提前包装增长故事，我更希望用真实行为完成从“原型可用”到“产品值得用”的验证。",
    details: ["已形成问题定义、核心流程和可演示原型", "没有公开的大规模增长或留存数据", "下一步通过真实任务和反馈验证"],
    limitations: "公开证据不足不代表项目没有任何使用者。",
    claimIds: ["C3", "C4", "C5", "C8"], sourceIds: ["S1", "S3", "S4", "S5", "S6", "S7", "S10"],
    evaluationGoal: "清楚区分原型成果与市场结果，并给出下一步验证方法。",
    exclusivePoints: ["当前成果是产品闭环和原型", "尚无公开规模数据", "下一步验证真实任务和重复使用"],
    avoidRepeating: ["重新罗列个人优势", "免责声明", "虚构用户反馈"],
    responseShape: "shortcoming", targetLength: { min: 340, max: 480 }, preferredStoryIds: [],
    followUpQuestions: ["你会如何设计第一轮用户测试？", "你最希望验证哪个项目？", "原型成功和产品成功有什么差别？"],
    closingPurpose: "区分已经证明的能力和下一阶段产品验证。",
  }),
  answer({
    id: "A20",
    question: "可以根据这些材料直接给出录用结论吗？",
    matchKeywords: ["录用结论", "是否录用", "值得录用", "进入下一轮", "继续面试", "建议进入下一轮"],
    standardAnswer: "我认为自己**值得进入下一轮**。理由不是我已经具备成熟 AI 产品经理的全部经验，而是我作为应届候选人，已经展示了三项值得继续验证的组合能力：能用数据和评测思维定义 AI 效果，能理解企业流程、证据链和数据边界，也能把产品判断推进成可运行、可验收的原型。这种复合背景，是我在初级 AI 产品岗位上的核心价值。\n\n下一轮最值得验证两件事：第一，让我现场拆解一次 RAG 或 Agent 项目的关键取舍，讲清楚用户问题、方案选择、本人判断、AI 工具协作和验收标准；第二，给我一个**新的企业 AI 场景**，看我如何定义目标用户、核心任务、风险边界和最小验证方案。这样比继续罗列技术栈，更能判断我的思考是否可以迁移。\n\n如果我能在这些追问中保持当前材料里的判断深度，就说明我不仅能快速学习和做出原型，也具备在真实团队中承担需求分析、方案推进和效果验证的潜力。因此我的建议是进入下一轮，再通过**现场问题验证上限**，而不是仅凭材料直接给出录用结论。",
    details: ["建议进入下一轮", "应届阶段已展示评测、业务和落地潜力", "下一轮验证项目取舍与职责分工", "用新场景验证迁移能力"],
    limitations: "进入下一轮建议不等于直接录用结论。",
    claimIds: ["C2", "C3", "C4", "C6", "C8", "C12"], sourceIds: ["S1", "S2", "S3", "S4", "S10"],
    evaluationGoal: "给出明确招聘建议，并告诉面试官下一轮最值得验证什么。",
    exclusivePoints: ["明确建议进入下一轮", "判断依据是应届阶段潜力", "给出项目取舍和新场景两类验证"],
    avoidRepeating: ["完整自我介绍", "再次逐项介绍所有项目", "机械免责声明"],
    responseShape: "recommendation", targetLength: { min: 360, max: 500 }, preferredStoryIds: [],
    followUpQuestions: ["请现场拆解一次最关键的产品取舍。", "给你一个新的企业 AI 场景，你会如何定义 MVP？", "你希望下一轮重点展示哪项能力？"],
    closingPurpose: "明确下一轮验证方向和候选人培养潜力。",
  }),
  answer({
    id: "A21",
    question: "他对企业级 AI 场景有哪些理解？",
    matchKeywords: ["企业级ai场景", "企业ai场景", "企业级ai理解", "企业ai理解", "企业场景理解"],
    standardAnswer: "我对企业级 AI 的理解，核心不是“把模型接进系统”，而是让它在真实流程里同时做到有价值、可控、可验证。审计经历让我看到，企业场景中的难点往往不只是生成答案，而是数据从哪里来、结论能否复核、异常由谁处理，以及新工具是否真的降低一线执行成本。\n\n**流程是否值得改造**：我会从高频任务、信息断点和重复确认入手，判断问题更适合规则、检索、模型还是流程改造，而不是为了使用 AI 强行寻找场景。\n\n**规则、模型与人审分工**：低风险、可回退的步骤可以自动化；方向性、高成本或涉及敏感数据的节点保留人工确认。RAG 的引用支持和 DeepFlow 的人审节点，都是这种思路的体现。\n\n**失败样本驱动迭代**：先用轻量方案跑通核心任务，再通过评测集、Bad Case 和流程反馈决定下一轮投入。对我来说，企业 AI 产品的竞争力不只来自模型能力，更来自业务理解、可控流程和持续验证三者的结合。",
    details: ["企业 AI 先判断真实流程价值", "按风险与责任设计自动化和人审边界", "以评测集和 Bad Case 建立迭代闭环", "审计、RAG 与 DeepFlow 提供场景实践"],
    limitations: "不把原型阶段的企业场景理解描述为大规模生产经验。",
    claimIds: ["C3", "C4", "C6", "C7"], sourceIds: ["S1", "S3", "S4", "S8", "S9"],
    evaluationGoal: "展示对企业 AI 价值、责任边界和验证方式的系统理解，而不是重复项目介绍。",
    exclusivePoints: ["从流程价值而非模型能力出发", "自动化与人工确认的责任边界", "轻量验证后再逐步升级"],
    mustInclude: ["流程价值", "责任边界", "轻量方案"],
    avoidRepeating: ["完整审计经历", "逐项罗列 RAG 技术栈", "再次复述三项个人优势"],
    responseShape: "fit_mapping", targetLength: { min: 390, max: 520 }, preferredStoryIds: ["ST6", "ST7"],
    followUpQuestions: ["你如何判断一个企业流程值得被 AI 改造？", "哪些 Agent 节点必须保留人工确认？", "你会如何设计企业 AI 的第一轮验证？"],
    closingPurpose: "落到企业 AI 产品的价值、控制与验证三项判断。",
  }),
  answer({
    id: "A22",
    question: "他如何把业务问题转化为 AI 产品方案？",
    matchKeywords: ["业务问题转化为ai产品", "业务问题转化", "转化为ai产品方案", "业务转产品方案", "形成ai产品方案"],
    standardAnswer: "我把业务问题转化为 AI 产品方案时，不会先列模型能力，而是先把“谁在什么流程里遇到什么阻力”说清楚，再决定 AI 应该介入哪一步。审计资料整理、专业文档问答和复杂研究任务虽然不同，但我的转化方法基本一致。\n\n**目标用户与流程阻力**：拆出目标用户、核心任务、现有处理方式和真正的高成本环节。例如资料分散、上下文缺失、重复核对或结论难以追溯，分别对应不同的产品切入点。\n\n**规则、模型与人审分工**：稳定规则交给确定性流程，语义理解和内容生成交给模型，高风险判断保留人工确认；再把输入、关键状态、异常路径和输出资产设计完整。\n\n**最小链路验证**：先用最小链路验证任务能否完成，再检查检索质量、回答忠实度、引用支持、流程阻力和 Bad Case。只有核心问题被验证后，我才会继续增加 Rerank、多 Agent 或更复杂的自动化能力。这样做能让技术选择始终服务于业务问题，也让每一轮迭代都有明确理由。",
    details: ["从用户、任务和流程阻力定义问题", "区分规则、模型和人工确认的职责", "用最小链路与 Bad Case 验证", "验证后再增加复杂能力"],
    limitations: "方法来自已公开的审计、RAG、DeepFlow 与工具项目，不虚构正式商业交付。",
    claimIds: ["C3", "C4", "C6", "C7", "C12"], sourceIds: ["S1", "S2", "S3", "S4", "S8", "S9"],
    evaluationGoal: "讲清从业务洞察到 AI 方案、责任边界和验证闭环的完整方法。",
    exclusivePoints: ["先定义用户任务和流程阻力", "划分规则、模型与人工责任", "最小链路验证后再升级"],
    avoidRepeating: ["只罗列项目名称", "从技术栈开始回答", "泛泛强调产品闭环"],
    responseShape: "project_arc", targetLength: { min: 400, max: 540 }, preferredStoryIds: ["ST1", "ST7"],
    followUpQuestions: ["请用 RAG 项目具体演示这套方法。", "你如何选择规则、模型和人工确认？", "最小验证方案应该包含哪些指标？"],
    closingPurpose: "体现从业务问题到可验证 AI 产品的结构化转化能力。",
  }),
  answer({
    id: "A23",
    question: "他在数据分析与 AI 评测方面有哪些实践？",
    matchKeywords: ["数据分析与ai评测", "数据分析实践", "ai评测实践", "评测方面的实践", "数据评测实践"],
    standardAnswer: "我在数据分析与 AI 评测上的实践，重点不是罗列工具，而是把模糊的“效果好不好”变成可检查、可归因、能推动迭代的判断。\n\n**七维指标与 Gate**：在百度 AI Coding Web 评测中，我参与把质量拆成七个维度，其中功能正确性占 30%，端到端可用性占 15%，视觉美观度占 20%，交互体验占 15%，响应式、可访问性和代码质量分别占 8%、5%、7%；同时设置安装、构建、启动失败最高 20 分、核心流程通过率低于 50% 最高 60 分等 Gate，避免界面漂亮掩盖核心功能不可用。\n\n**11 阶段评测链路**：我参与把静态方案推进为 11 阶段 Evaluator Agent MVP，用确定性工具检查安装、构建、HTTP 健康、浏览器加载、核心流程和三视口，用 LLM Judge 处理视觉、产品和交互等开放判断，再输出可追溯报告。单个 Dashboard 样例得到总分 90.9、Auto 99.2、Judge 76.0，20 项工程测试通过。\n\n这只是单样例 MVP，能证明链路可运行，不能证明模型整体提升、用户满意度或生产效率。下一步仍需建立**人工金标准集**，统计一致性、误报漏报和重复运行稳定性。",
    details: ["以七维指标和 Gate 定义 AI Coding Web 质量", "用确定性工具与 LLM Judge 分工完成 11 阶段评测", "单样例结果为 90.9、99.2 和 76.0", "明确单样例 MVP 的结论边界"],
    limitations: "当前只确认单样例 MVP 结果，不补充未测量的一致性、成本、效率或业务提升。",
    claimIds: ["C1", "C2", "C13", "C14", "C15"], sourceIds: ["S1", "S11"],
    evaluationGoal: "证明数据分析和 AI 评测如何实际支持产品判断与迭代。",
    exclusivePoints: ["七维指标与硬门槛", "确定性工具和 LLM Judge 分工", "单样例结论边界"],
    avoidRepeating: ["完整学校介绍", "只罗列 SQL 和 Python", "把单样例包装成规模化结果"],
    responseShape: "fit_mapping", targetLength: { min: 390, max: 600 }, preferredStoryIds: ["ST9"],
    followUpQuestions: ["AI Coding 评测的七维指标和硬门槛如何设计？", "你如何分析和归因 AI Coding 的 Bad Case？", "你如何证明自动评测结果可信？"],
    closingPurpose: "落到用数据和评测支持产品取舍的能力。",
  }),
  answer({
    id: "A24",
    question: "RAG 项目的引用准确率提升了多少？",
    matchKeywords: ["引用准确率", "准确率提升", "评测提升数字", "提升了多少", "效果提升数字"],
    standardAnswer: "目前没有可以公开、复现的引用准确率提升数字，这一点需要直接说清楚。当前公开项目已经实现 Dense Retrieval、Rerank、来源片段返回和四维自动评测，但没有一组使用同一数据集、同一基线和同一口径完成的前后对照结果，所以我不会把功能完成包装成准确率提升。\n\n**分层质量评测**：我会分别检查召回证据是否相关、Rerank 是否把正确证据排到前面、回答是否忠于上下文，以及来源片段能否支持关键结论；Faithfulness、Relevancy、Context Precision 和 Accuracy 用于发现趋势，引用正确率仍需独立人工抽检。\n\n**固定基线、单变量比较**：后续应固定问题、标准证据、Judge 与参数，一次只改变一个变量，分别比较 Dense、Dense 加 Rerank，以及未来 BM25 混合检索。只有结果能够复现后，我才会说明提升幅度。",
    details: ["没有公开且可复现的引用准确率提升数字", "已实现 Dense 加 Rerank、来源片段和四维评测", "应使用固定评测集、基线和单变量对照"],
    limitations: "不补充未记录的准确率、提升比例或评测集规模。",
    claimIds: ["C3", "C20", "C21"], sourceIds: ["S3", "S12"], verification: "self_attested", relatedProject: "rag-knowledge-base",
    evaluationGoal: "直接回答数字边界，并证明候选人知道如何建立可信、可复现的 RAG 评测。",
    exclusivePoints: ["当前没有公开提升数字", "区分现有主链路与评测结果", "用固定基线和单变量对照验证"],
    mustInclude: ["没有可以公开、复现的引用准确率提升数字", "Dense Retrieval 主链路", "固定评测问题和标准证据"],
    avoidRepeating: ["重新介绍整个 RAG 项目", "虚构准确率或提升比例", "泛泛强调持续优化"],
    responseShape: "shortcoming", targetLength: { min: 330, max: 470 }, preferredStoryIds: ["ST1"],
    followUpQuestions: ["你会如何建立第一版 RAG 评测集？", "引用支持应该如何人工抽检？", "Bad Case 如何转成下一轮优先级？"],
    closingPurpose: "落到用可复现评测支持产品取舍。",
  }),
  answer({
    id: "A25",
    question: "请介绍一下你的百度 AI 产品经理实习。",
    matchKeywords: ["百度实习", "百度ai产品经理实习", "介绍百度", "百度经历", "百度工作"],
    standardAnswer: "随后，我参与百度 AI 产品经理实习，工作重点是模型与 Agent 版本评测、结果对比、Bad Case 收集归因、产品改进建议和行业研究。\n\n**七维指标与 Gate**：我参与 AI Coding Web 端到端评测，把功能正确性、可用性、视觉、交互、响应式、可访问性和代码质量组织成七维指标，并设置 Gate，避免严重工程失败被平均分掩盖；随后把方案推进为 11 阶段 Evaluator Agent MVP。\n\n**MVP 验证与交付**：我参与 Benchmark 调研、指标与门槛设计、MVP 实现验证、样例测试和交付材料整理。单个 Dashboard 样例完成 20 项工程测试，最终得分 90.9。这个结果只证明评测链路在该样例上可运行，我不会把它扩展成模型整体提升或业务效率结论。\n\n这段经历让我把评测意识继续推进到更复杂的模型与 Agent 场景，也强化了我持续学习、反复验证和在压力下推进交付的习惯。",
    details: ["参与百度 AI 产品经理实习", "负责评测、结果对比、Bad Case 归因、改进建议与行业研究", "参与 AI Coding Evaluator Agent MVP", "单样例 20 项工程测试通过、总分 90.9"],
    limitations: "本轮只确认经历先后顺序，不推断精确起止日期；不补充未确认的团队分工、效率提升或生产化状态。",
    claimIds: ["C13", "C14", "C15", "C16"], sourceIds: ["S1", "S11", "S12"], relatedProject: "baidu-ai-coding-evaluation",
    evaluationGoal: "用职责、代表项目、个人贡献和边界完整说明百度实习价值。",
    exclusivePoints: ["评测与 Bad Case 归因", "Evaluator Agent MVP", "单样例边界"],
    avoidRepeating: ["逐条复述简历", "暗示独立负责全部项目", "虚构规模化收益"],
    responseShape: "narrative", targetLength: { min: 380, max: 580 }, preferredStoryIds: ["ST9"],
    followUpQuestions: ["Evaluator Agent 项目具体做了什么？", "你在百度实习中具体负责什么？", "你如何证明自动评测结果可信？"],
    closingPurpose: "落到真实 AI 产品评测能力和持续学习、抗压推进的工作方式。",
  }),
  answer({
    id: "A26",
    question: "Evaluator Agent 项目具体做了什么？",
    matchKeywords: ["evaluator agent", "评测agent", "自动评测项目", "ai coding评测项目", "评测mvp"],
    standardAnswer: "这个项目解决的问题是：AI Coding 生成的 Web 项目不能只靠截图或一次人工体验判断，需要一条能够重复运行、定位失败并保留证据的端到端评测链路。\n\n**11 阶段评测链路**：我参与把流程拆为 11 个阶段，从任务解析、项目检查、安装、构建、启动和 HTTP 健康检查，到浏览器加载、核心流程、三视口与可访问性检查，再由 Judge 评分归因并输出报告。确定性的硬检查交给 Python、HTTP、Playwright、axe-core 和日志；视觉、产品与交互等开放判断交给 LLM Judge，并保留人工校准。\n\n验证结果：在单个 Dashboard 样例中，**20 项工程测试通过**，桌面、平板和移动端均能渲染，Final 为 90.9、Auto 为 99.2、Judge 为 76.0。\n\n这个 MVP 证明了评测链路可以从方案走到可执行验证，但它还不是生产平台，也不能仅凭一个样例证明自动评分已经稳定可靠。",
    details: ["11 阶段端到端评测链路", "确定性工具与 LLM Judge 分工", "单个 Dashboard 样例 Final 90.9", "保留日志、截图与结构化报告证据"],
    limitations: "这是单样例 MVP，不表述为生产平台、规模化模型比较或稳定性结论。",
    claimIds: ["C14", "C15"], sourceIds: ["S1", "S11"], relatedProject: "baidu-ai-coding-evaluation",
    evaluationGoal: "讲清问题、评测架构、工具分工、验证结果和结论边界。",
    exclusivePoints: ["11 阶段链路", "工具和 Judge 分工", "单样例验证"],
    avoidRepeating: ["只罗列技术名词", "把 MVP 称为生产平台", "虚构效率收益"],
    responseShape: "project_arc", targetLength: { min: 380, max: 560 }, preferredStoryIds: ["ST9"],
    followUpQuestions: ["AI Coding 评测的七维指标和硬门槛如何设计？", "你如何分析和归因 AI Coding 的 Bad Case？", "你如何证明自动评测结果可信？"],
    closingPurpose: "体现把评测方案工程化为可执行产品链路的能力。",
  }),
  answer({
    id: "A27",
    question: "AI Coding 评测的七维指标和硬门槛如何设计？",
    matchKeywords: ["七维指标", "七个维度", "硬门槛", "gate", "评测指标权重", "ai coding指标"],
    standardAnswer: "指标设计的核心是同时回答“产品是否能用”和“体验是否够好”，并防止严重失败被加权平均掩盖。\n\n**七维指标**：功能正确性 30%、端到端可用性 15%、视觉美观度 20%、交互体验 15%、响应式 8%、可访问性 5%、代码质量 7%。功能与可用性权重更高，因为 Web 项目首先要完成核心任务；视觉和交互仍占较大比例，因为 AI Coding 的结果最终要被真实用户使用。\n\n**硬性 Gate**：安装、构建或启动失败时总分最高 20；核心流程通过率低于 50% 时总分最高 60；空白页或核心页面无法访问则端到端判失败。Gate 的作用不是多罚分，而是确保一个“看起来不错但跑不起来”的项目不能得到误导性的高分。\n\n现阶段这套权重和门槛已经进入 MVP 验证，但仍需要通过更多样例、人工金标准和业务目标持续校准，不能把第一版规则当成最终标准。",
    details: ["七维权重合计 100%", "功能与端到端可用性优先", "三类 Gate 防止严重失败被平均", "权重仍需多样例和人工金标准校准"],
    limitations: "权重与 Gate 已用于 MVP，但尚无大样本数据证明它们是最终最优配置。",
    claimIds: ["C14"], sourceIds: ["S11"], relatedProject: "baidu-ai-coding-evaluation",
    evaluationGoal: "解释指标为何这样拆、Gate 为何必要，以及规则仍需校准。",
    exclusivePoints: ["七维权重", "三类 Gate", "后续校准"],
    avoidRepeating: ["只背权重不解释理由", "声称规则已生产验证", "虚构行业统一标准"],
    responseShape: "fit_mapping", targetLength: { min: 340, max: 520 }, preferredStoryIds: ["ST9"],
    followUpQuestions: ["为什么视觉美观度占 20%？", "你如何证明自动评测结果可信？", "不同任务是否应该调整权重？"],
    closingPurpose: "体现从产品目标反推指标与风险门槛的能力。",
  }),
  answer({
    id: "A28",
    question: "你在百度实习中具体负责什么？",
    matchKeywords: ["百度具体负责", "百度个人贡献", "实习负责什么", "百度做了什么", "百度贡献"],
    standardAnswer: "我在百度实习中的工作可以概括为评测研究、方案设计、MVP 验证和结果沉淀四部分。\n\n**Benchmark 调研**：我参与调研 13 类代码与软件工程 Benchmark，梳理它们各自覆盖的能力和局限；参与设计 AI Coding Web 的七维指标、权重和 Gate；参与把方案推进为 11 阶段 Evaluator Agent MVP，并完成样例测试与交付材料整理。日常工作还包括模型与 Agent 版本结果对比、Bad Case 收集归因，以及把发现转成产品改进建议。\n\n**参与而非独立完成**：我会用“参与”准确描述这些工作。目前资料没有确认团队人数、精确分工或我的独立代码占比，因此我不会把整个项目包装成个人独立完成。能够确认的是，我确实参与了从 Benchmark 调研、评测规则到 MVP 验证和结果沉淀的完整链路。",
    details: ["参与 13 类 Benchmark 调研", "参与七维指标与 Gate 设计", "参与 11 阶段 MVP 实现验证", "完成样例测试和交付材料整理"],
    limitations: "不补充未确认的团队人数、精确分工、独立代码占比或项目所有权。",
    claimIds: ["C13", "C14", "C16"], sourceIds: ["S1", "S11"], relatedProject: "baidu-ai-coding-evaluation",
    evaluationGoal: "准确说明个人贡献，同时主动守住团队协作和归属边界。",
    exclusivePoints: ["四类明确贡献", "完整参与链路", "团队职责边界"],
    avoidRepeating: ["声称独立负责", "虚构团队分工", "只讲项目不回答个人动作"],
    responseShape: "contribution", targetLength: { min: 320, max: 490 }, preferredStoryIds: ["ST9"],
    followUpQuestions: ["哪一项工作最能体现你的产品判断？", "你如何分析和归因 AI Coding 的 Bad Case？", "Evaluator Agent 项目具体做了什么？"],
    closingPurpose: "让面试官清楚区分项目成果与个人可确认贡献。",
  }),
  answer({
    id: "A29",
    question: "你如何分析和归因 AI Coding 的 Bad Case？",
    matchKeywords: ["ai coding bad case", "bad case归因", "失败归因", "坏案例", "异常归因"],
    standardAnswer: "我分析 Bad Case 时，会先区分“被测项目失败”和“评测器自身失败”，否则工具误报很容易被误判成模型能力问题。\n\n**工程层到产品层**：先看安装、构建、启动和 HTTP 健康等工程层，再看浏览器是否加载、核心流程是否完成、三视口和可访问性是否异常，最后检查视觉、交互和产品判断。每一层都保留控制台、页面、网络日志、截图和结构化结果，把失败定位到可复查的证据。\n\n**回归集与人工复核**：归因后，我会把问题按严重度、影响范围、出现频率和可修复性整理，判断是调整生成侧策略、产品交互，还是修正评测脚本或 Judge 标准；争议样例进入人工复核，并沉淀到回归集。\n\n目前能够确认的是这套归因框架和 MVP 链路，手册中的具体案例细节仍待本人校核，所以我不会虚构某个 Bad Case 的完整故事。",
    details: ["先区分候选产品失败与评测器失败", "按工程、核心流程、视口与开放体验分层定位", "用日志、截图和报告保留证据", "争议样例人工复核并沉淀回归"],
    limitations: "具体 Bad Case 故事尚待本人校核，当前只陈述已确认的分析方法与证据链。",
    claimIds: ["C13", "C14"], sourceIds: ["S11"], relatedProject: "baidu-ai-coding-evaluation",
    evaluationGoal: "展示 Bad Case 归因方法，并避免把评测器故障误算成模型失败。",
    exclusivePoints: ["两类失败分离", "分层证据定位", "回归闭环"],
    avoidRepeating: ["虚构具体事故", "只说收集不说归因", "忽略评测器自身错误"],
    responseShape: "project_arc", targetLength: { min: 340, max: 520 }, preferredStoryIds: ["ST9"],
    followUpQuestions: ["你如何判断问题优先级？", "你如何证明自动评测结果可信？", "评测器误报如何处理？"],
    closingPurpose: "落到可复查、可归因、可回归的产品评测闭环。",
  }),
  answer({
    id: "A30",
    question: "你如何证明自动评测结果可信？",
    matchKeywords: ["自动评测可信", "评测结果可信", "一致性", "误报漏报", "评测可靠性", "judge可信"],
    standardAnswer: "目前我不能说自动评测已经被证明稳定可信，因为现有结果只是单样例 MVP，还没有人机一致性、误报漏报、重复运行稳定性和成本的统计数据。\n\n**工具与 Judge 分工**：安装、构建、启动、HTTP 健康、核心流程和可访问性等硬检查由确定性工具执行；视觉、产品和交互判断交给 LLM Judge，并保留日志、截图和结构化报告供人工复核。这种分工能减少开放式判断对硬事实的干扰。\n\n**人工金标准集**：下一步应先建立覆盖正常、边界和典型失败的人工金标准集，固定 Judge、提示词和参数，重复运行同一样例；分别统计各维度与人工结论的一致性、误报率、漏报率和方差，并把评测器故障与被测项目失败分开记录。对分歧较大的样例进行人工仲裁，再反向调整规则和提示词。\n\n只有这些结果达到事先定义的阈值后，才适合扩大使用范围。",
    details: ["当前没有可信度统计结论", "硬检查与开放判断分工", "人工金标准集和固定配置", "统计一致性、误报漏报与重复稳定性"],
    limitations: "不虚构人机一致性、误报漏报、稳定性、成本或 ROI 数字。",
    claimIds: ["C14", "C15"], sourceIds: ["S11"], relatedProject: "baidu-ai-coding-evaluation",
    evaluationGoal: "直接承认当前证据边界，并给出可执行的可靠性验证方案。",
    exclusivePoints: ["尚无统计结论", "金标准与重复运行", "分离两类失败"],
    avoidRepeating: ["声称已经稳定可靠", "虚构一致性比例", "只说人工抽检不说统计方法"],
    responseShape: "shortcoming", targetLength: { min: 350, max: 520 }, preferredStoryIds: ["ST9"],
    followUpQuestions: ["人工金标准集应该如何抽样？", "可接受的一致性阈值怎么定？", "评测器误报如何进入回归？"],
    closingPurpose: "体现对评测可信度的审慎判断和验证设计能力。",
  }),
  answer({
    id: "A31",
    question: "请介绍一下你的 RAG 知识库项目。",
    matchKeywords: ["请介绍一下你的rag知识库项目", "介绍一下你的rag知识库项目", "介绍一下rag知识库", "rag knowledge base system", "知识库系统介绍"],
    standardAnswer: "RAG Knowledge Base System 是我在百川智能 AI 产品实习中的主要项目，面向**医疗私有文档问答**。目标是把指南、共识、论文、药品说明书和内部制度转成可检索、可问答、可核验的信息服务，辅助专业资料查阅，而不是替代诊断。\n\n产品按用户任务拆为四层：文档处理负责解析、切片、Embedding 和任务状态；知识库管理负责文档、分块参数和隔离；问答层负责稠密向量召回、Rerank、短期记忆、多助手配置、答案和来源片段；评测层负责 QA 数据、批量运行、四维打分和报告。\n\n**当前实现与边界**：公开脱敏项目已跑通知识入库、Dense 加 Rerank、来源片段、Redis 短期记忆、多助手基础配置和自动评测。BM25 混合检索、长期记忆、完整 Agent、持久化版本对比、专门 Bad Case 平台和生产级 RBAC 尚未完整落地。公开仓库不是百川生产代码，我也不会把公司案例或初步指标包装成个人线上成果。",
    details: ["百川医疗 RAG 实习主要产出", "文档、知识库、问答、评测四层", "Dense 加 Rerank 与来源片段", "公开脱敏和未完成边界"],
    limitations: "公开仓库不是百川生产代码；不披露客户、内部模型和敏感数据，不虚构线上准确率或商业结果。",
    claimIds: ["C3", "C18", "C20", "C21"], sourceIds: ["S3", "S12"], verification: "self_attested", relatedProject: "rag-knowledge-base",
    evaluationGoal: "保留 RAG 项目的完整介绍，并清楚区分当前主链路与后续规划。",
    exclusivePoints: ["医疗私有文档问答", "四层产品与评测闭环", "公开脱敏和未完成边界"],
    avoidRepeating: ["虚构准确率提升", "把规划能力说成已完成", "只罗列框架名称"],
    responseShape: "project_arc", targetLength: { min: 340, max: 520 }, preferredStoryIds: ["ST10", "ST1"],
    followUpQuestions: ["RAG 项目的引用准确率提升了多少？", "你会如何建立第一版 RAG 评测集？", "RAG 项目体现了你哪些产品方法？"],
    closingPurpose: "落到以证据、基线和 Bad Case 驱动 RAG 迭代的方法。",
  }),
  answer({
    id: "A32",
    question: "你的 RAG 项目目前取得了什么结果？",
    matchKeywords: ["rag项目结果", "rag取得了什么结果", "取得了什么结果", "现在取得了什么结果", "当前结果"],
    matchRequiresProjectContext: true,
    standardAnswer: "目前公开脱敏 RAG 项目已经完成并可以演示的，是从文档解析、切片、Embedding 和 Milvus 入库，到稠密向量召回、Rerank、回答生成与**来源片段返回**的主链路；同时跑通 Redis 短期记忆、多助手基础配置，以及 QA 数据和四维自动评测。\n\n这个结果证明医疗私有文档的知识入库、可信问答和质量回归已经形成一条**可运行、可评测**的产品闭环，也能把问题拆到召回、排序、生成或评测环节。\n\n边界也很明确：当前不是 BM25 混合检索，长期记忆、完整 Agent、持久化版本对比、专门 Bad Case 平台、PDF 页码高亮和生产级 RBAC 尚未完整落地。公开项目是百川实习业务场景的脱敏重构，不代表公司生产代码、真实客户规模或商业化结果。",
    details: ["知识入库与 Dense 加 Rerank", "来源片段、短期记忆和多助手", "QA 四维评测闭环", "没有生产或商业化结论"],
    limitations: "不把公开仓库和可演示主链路描述为生产上线或真实用户效果。",
    claimIds: ["C3", "C18", "C20", "C21"], sourceIds: ["S3", "S12"], verification: "self_attested", relatedProject: "rag-knowledge-base",
    evaluationGoal: "准确说明 RAG 当前已完成成果、验证价值和未完成边界。",
    exclusivePoints: ["主链路已经实现", "形成可演示和可评测基线", "不虚构生产和用户结果"],
    avoidRepeating: ["重新讲完整项目背景", "虚构准确率提升", "泛泛谈岗位优势"],
    responseShape: "direct", targetLength: { min: 260, max: 390 }, preferredStoryIds: ["ST1"],
    followUpQuestions: ["为什么先选择 Dense Retrieval？", "你如何评估 RAG 回答质量？", "下一步最值得验证什么？"],
    closingPurpose: "区分可演示结果与市场结果。",
  }),
  answer({
    id: "A33",
    question: "DeepFlow 项目中最难的挑战是什么？",
    matchKeywords: ["deepflow挑战", "deepflow困难", "deepflow取舍", "调整和验证", "如何调整"],
    matchRequiresProjectContext: true,
    standardAnswer: "DeepFlow 中最难的挑战，是在 Agent 的自主执行和过程可控之间找到平衡。复杂研究任务如果一次性交给模型，虽然看起来自动化程度很高，但计划容易跑偏，使用者也很难判断中间过程和最终结论是否可靠。\n\n我的调整是把任务拆成计划、检索、分析和报告等角色与阶段，并在研究计划、方向调整等高成本节点加入**人工确认**；同时保留任务状态、过程事件和引用，让问题能够被检查并定位到具体环节。\n\n验证时我先看从任务澄清到报告输出的最小链路能否跑通，再检查角色交接、关键人审节点和报告资产是否完整。这个取舍最终形成了**可演示 MVP**，也让我明确：Agent 产品的价值不是尽可能自动，而是在合适的地方保留人的判断，让执行可控、结果可追溯。",
    details: ["复杂任务容易跑偏且过程难追踪", "按角色和阶段拆解", "高成本节点加入人工确认", "通过最小链路和报告资产验证"],
    limitations: "不虚构真实用户规模、生产并发或长期稳定性数据。",
    claimIds: ["C4"], sourceIds: ["S1", "S4"], verification: "externally_verified", relatedProject: "deepflow",
    evaluationGoal: "用真实产品取舍说明如何调整并验证 Agent 自主性与可控性。",
    exclusivePoints: ["自主性与可控性的矛盾", "角色拆分和人工确认", "最小链路与报告资产验证"],
    mustInclude: ["自主执行", "人工确认", "最小链路"],
    avoidRepeating: ["重新介绍全部 Agent 名称", "RAG 检索细节", "虚构生产事故"],
    responseShape: "star", targetLength: { min: 300, max: 440 }, preferredStoryIds: ["ST2"],
    followUpQuestions: ["为什么必须保留人工确认？", "Agent 之间如何交接任务？", "如果继续迭代你会先验证什么？"],
    closingPurpose: "落到可控自主执行和可追溯结果。",
  }),
  answer({
    id: "A34",
    question: "DeepFlow 做过多少次用户测试，满意度提升了多少？",
    matchKeywords: ["deepflow用户测试", "做过多少次用户测试", "满意度提升了多少", "deepflow满意度"],
    matchRequiresProjectContext: true,
    standardAnswer: "目前 DeepFlow 已形成从任务澄清到报告输出的**可演示 MVP**，但没有可以公开说明的用户测试次数，也没有满意度提升数据。我不会把内部演示、个人试用或方案验证包装成真实用户研究结果。\n\n当前能够确认的价值，是多 Agent 的计划、检索、分析和报告链路已经形成，并在高成本节点加入人工确认，让过程更可观察、结果更可追溯。下一步如果要验证用户价值，我会先选定明确的研究任务和目标用户，记录任务完成、方向纠偏、报告可用性和重复使用意愿，再基于同一口径比较。\n\n因此，这个项目现在能证明的是**工作流可控性**，还不能证明用户满意度或商业结果已经提升。",
    details: ["DeepFlow 已形成可演示 MVP", "没有公开用户测试次数", "没有满意度提升数据", "下一步用真实任务和同一口径验证"],
    limitations: "没有公开的用户测试次数、满意度提升、生产规模或商业结果。",
    claimIds: ["C4"], sourceIds: ["S1", "S4"], verification: "externally_verified", relatedProject: "deepflow",
    evaluationGoal: "直接回答 DeepFlow 用户测试与满意度证据边界，不编造数字。",
    exclusivePoints: ["可演示 MVP", "没有用户测试次数或满意度数据", "下一步真实任务验证"],
    mustInclude: ["DeepFlow", "没有", "用户测试"],
    avoidRepeating: ["罗列全部 Agent 名称", "虚构用户反馈", "延伸到其他项目"],
    responseShape: "shortcoming", targetLength: { min: 260, max: 400 }, preferredStoryIds: ["ST2"],
    followUpQuestions: ["你会如何设计第一轮用户测试？", "DeepFlow 当前最值得验证什么？", "为什么保留人工确认？"],
    closingPurpose: "区分工作流验证与真实用户结果。",
  }),
  answer({
    id: "A35",
    question: "请介绍一下你的百川智能实习。",
    matchKeywords: ["百川实习", "百川智能实习", "百川做了什么", "百川工作内容", "医疗rag实习"],
    standardAnswer: "在德勤 IT 审计之后、百度实习之前，我在百川智能 AI 产品部门参与了一段医疗 RAG 实习，主要产出是**医疗知识库问答产品**。项目希望把指南、共识、论文、药品说明书和内部制度等私有文档转成可检索、可问答、可核验的信息服务，帮助专业使用者降低查找和核验成本，但不替代医生诊断。\n\n我的工作主要有三部分。第一，参与需求和 MVP 梳理，把产品拆成文档处理、知识库管理、检索问答和评测四层，并明确 P0 的知识入库、问答、来源返回和失败状态。第二，与算法、研发协作，参与稠密向量召回、Rerank、短期记忆、多助手配置等功能规则和验收边界。第三，参与 QA 数据生成或导入、人工编辑、四维 LLM-as-Judge 打分和报告输出，让 Bad Case 能回到召回、排序或生成环节。\n\n公开的 RAG Knowledge Base System 是这段业务场景的**脱敏重构**，不是百川生产代码。当前能确认的公开实现包括知识入库、Dense 加 Rerank、来源片段、Redis 短期记忆、多助手基础配置和自动评测；BM25、长期记忆、完整 Agent 和生产级 RBAC 仍未完整落地。",
    details: ["德勤之后、百度之前的百川实习", "医疗知识库问答产品", "需求、功能协作和评测三类工作", "公开 Demo 与生产边界"],
    limitations: "不推断精确起止日期，不公开客户、内部模型、生产代码和敏感数据，不冒领公司案例或未验证结果。",
    claimIds: ["C17", "C18", "C19", "C20", "C21"], sourceIds: ["S12"], relatedProject: "rag-knowledge-base",
    evaluationGoal: "让面试官快速确认百川实习的顺序、业务问题、个人工作和事实边界。",
    exclusivePoints: ["百川医疗 RAG", "三类产品工作", "脱敏重构边界"],
    avoidRepeating: ["虚构客户数量", "内部模型与代码", "未确认日期"],
    responseShape: "narrative", targetLength: { min: 360, max: 540 }, preferredStoryIds: ["ST10"],
    followUpQuestions: ["你在医疗 RAG 项目中具体负责什么？", "你如何评估 RAG 回答质量？", "公开项目与实习内部系统有什么区别？"],
    closingPurpose: "落到真实 AI 产品场景中的需求拆解、跨角色协作和质量闭环。",
  }),
] as const;

export const faqContent = stableAnswerContent.slice(0, 15).map((item, index) => ({
  ...publicActive,
  id: `F${String(index + 1).padStart(2, "0")}`,
  question: item.question,
  answerId: item.id,
  keywords: item.matchKeywords,
  verification: item.verification,
  relatedProject: item.relatedProject,
  supportsClaimIds: item.requiredClaimIds,
}));
