import { candidateNarrative } from "./narrative.ts";
import type { AnswerIntent, ResponseShape } from "../lib/types.ts";

const updated = "2026-07-18";
const publicActive = { visibility: "public", status: "active", lastUpdated: updated } as const;

type AnswerInput = {
  id: string;
  question: string;
  standardAnswer: string;
  details?: string[];
  limitations: string;
  claimIds: string[];
  sourceIds: string[];
  matchKeywords: string[];
  evaluationGoal: string;
  exclusivePoints: string[];
  avoidRepeating: string[];
  responseShape: ResponseShape;
  targetLength: { min: number; max: number };
  preferredStoryIds: string[];
  followUpQuestions: string[];
  closingPurpose: string;
  verification?: "externally_verified" | "self_attested";
  relatedProject?: string;
  intent?: AnswerIntent;
  mustInclude?: string[];
  allowedFacts?: string[];
  allowedNumbers?: string[];
  allowedOrganizations?: string[];
  allowedProjectStatuses?: string[];
  boundaryTriggers?: string[];
  forbiddenDetails?: string[];
};

const answerIntentById: Record<string, AnswerIntent> = {
  A01: "introduction", A02: "role_fit", A03: "representative_project", A04: "project_problem",
  A05: "contribution", A06: "project_overview", A07: "ai_collaboration", A08: "skills",
  A09: "experience_value", A10: "experience", A11: "experience", A12: "project_overview",
  A13: "privacy", A14: "limitation", A15: "challenge", A16: "education",
  A17: "credentials", A18: "project_overview", A19: "result", A20: "hiring_recommendation",
  A21: "experience_value", A22: "experience_value", A23: "skills", A24: "result",
};

const knownOrganizations = ["东北大学", "德勤", "容诚", "ACCA"];
const defaultBoundaryTriggers = ["短板", "不足", "限制", "风险", "真实数据", "用户规模", "生产状态", "个人贡献", "未完成"];
const defaultForbiddenDetails = [
  "未在资料中出现的任职、日期或组织",
  "未在资料中出现的用户访谈、满意度、增长、效率或业务结果数字",
  "把规划中或待验证的能力描述为已经完成",
  "审计客户、底稿、企业机密或未公开个人信息",
  "未确认的占位经历",
];

function extractNumbers(values: string[]) {
  return [...new Set(values.flatMap((value) => value.match(/\b\d+(?:\.\d+)?%?\b/g) ?? []))];
}

function answer(input: AnswerInput) {
  const facts = [input.standardAnswer, ...(input.details ?? [])];
  const allowedOrganizations = input.allowedOrganizations
    ?? knownOrganizations.filter((organization) => facts.some((fact) => fact.includes(organization)));
  return {
    ...publicActive,
    ...input,
    verification: input.verification ?? "self_attested",
    supportsClaimIds: input.claimIds,
    requiredClaimIds: input.claimIds,
    requiredSourceIds: input.sourceIds,
    factSkeleton: {
      intent: input.intent ?? answerIntentById[input.id] ?? "general",
      thesis: input.standardAnswer.split(/\n\n/)[0],
      mustInclude: input.mustInclude ?? input.exclusivePoints,
      allowedFacts: input.allowedFacts ?? facts,
      allowedNumbers: input.allowedNumbers ?? extractNumbers(facts),
      allowedOrganizations,
      allowedProjectStatuses: input.allowedProjectStatuses ?? facts.filter((fact) => /MVP|原型|规划|验证阶段|已实现|已完成|持续优化/.test(fact)),
      boundaryTriggers: input.boundaryTriggers ?? defaultBoundaryTriggers,
      forbiddenDetails: [...defaultForbiddenDetails, ...(input.forbiddenDetails ?? [])],
    },
  };
}

export const stableAnswerContent = [
  answer({
    id: "A01",
    question: "请用 60 秒介绍张倬玮。",
    matchKeywords: ["60秒", "介绍", "自我介绍", "候选人定位", "简单说说自己"],
    standardAnswer: candidateNarrative.introductions.seconds60,
    details: [
      "身份与方向：东北大学应用统计学 2027 届学生，求职方向是 AI 产品经理。",
      "成长主线：应用统计学训练、财务与 IT 审计业务，再到 AI 产品实践。",
      "差异化：数据评测、企业业务和产品落地三种视角。",
      "项目锚点：RAG Knowledge Base System 与 DeepFlow。",
    ],
    limitations: "不加入未确认的占位经历，也不在自我介绍中主动展开项目规模和未验证结果。",
    claimIds: ["C1", "C2", "C3", "C4", "C6"],
    sourceIds: ["S1", "S3", "S4"],
    evaluationGoal: "让面试官在一分钟内记住候选人的身份、成长路径、三项差异点和求职方向。",
    exclusivePoints: ["应用统计学到审计再到 AI 产品的成长主线", "数据评测、企业业务、产品落地", "AI 应用、知识库或企业工作流方向"],
    avoidRepeating: ["项目技术栈", "项目完成边界", "完整贡献分工"],
    responseShape: "narrative",
    targetLength: { min: 450, max: 560 },
    preferredStoryIds: [],
    followUpQuestions: ["哪个项目最能代表你的 AI 产品能力？", "审计经历如何帮助你做 AI 产品？", "为什么选择你而不是其他应届候选人？"],
    closingPurpose: "明确目标岗位和希望创造的产品价值。",
  }),
  answer({
    id: "A02",
    question: "他为什么适合 AI 产品经理岗位？",
    matchKeywords: ["为什么适合", "为什么选择你", "选择你", "岗位匹配", "ai产品经理", "岗位优势", "入职", "团队做什么", "团队带来什么"],
    standardAnswer: "我适合 AI 产品经理岗位，不是因为单纯会使用大模型，而是因为我的能力能够覆盖 AI 产品从问题判断到落地验证的关键环节。\n\n**定义效果**：应用统计学和项目评测实践让我习惯先把“模型好不好”拆成可以检查的问题，例如检索是否命中正确内容、回答是否忠于上下文、哪些 Bad Case 最值得优先处理。这样做的价值，是让团队的迭代不只依赖主观体验。\n\n**理解场景**：财务审计和 IT 审计经历让我接触过企业流程、风险、证据链和数据边界。我会更早追问数据从哪里来、结果能否复核、哪些环节必须人工确认，以及一个看似聪明的功能是否真的降低了一线执行成本。\n\n**推动落地**：RAG 与 DeepFlow 项目训练了我从需求定义、流程设计和方案取舍推进到可运行原型，并通过测试与评测对最终质量负责。对团队来说，我能在业务目标、模型效果和工程约束之间建立共同语言，帮助大家更快判断一个方向是否值得继续投入。",
    details: ["AI 产品效果定义与评测", "企业流程与数据边界理解", "从产品判断到可运行原型", "在业务、模型和工程之间建立共同语言"],
    limitations: "岗位匹配回答不主动讨论用户规模、生产状态或公开证据缺口。",
    claimIds: ["C2", "C3", "C4", "C6"],
    sourceIds: ["S1", "S3", "S4"],
    evaluationGoal: "把已有能力逐项映射到 AI 产品经理的实际工作，而不是重新介绍个人经历。",
    exclusivePoints: ["定义 AI 产品效果", "理解企业场景", "连接业务、模型与工程"],
    avoidRepeating: ["学校和毕业年份", "完整成长主线", "所有项目列表"],
    responseShape: "fit_mapping",
    targetLength: { min: 360, max: 480 },
    preferredStoryIds: [],
    followUpQuestions: ["你如何评估并改进 AI 产品效果？", "你能为 AI 产品团队承担什么具体工作？", "哪个项目最能证明这些能力？"],
    closingPurpose: "说明入职后如何帮助团队更快验证产品方向。",
  }),
  answer({
    id: "A03",
    question: "哪个项目最能代表他的 AI 产品能力？",
    matchKeywords: ["代表项目", "最能代表", "ai产品能力"],
    standardAnswer: "最能代表我 AI 产品能力的是 RAG Knowledge Base System，因为它体现的不是某一个技术组件，而是我如何把一个模糊的业务问题变成可以持续验证的产品链路。\n\n**问题判断**：我关注的是专业资料虽然很多，但真正需要答案时，用户既难以快速找到正确内容，也很难判断生成结论依据了哪段原文。这里的核心矛盾不是“有没有模型”，而是答案能不能被信任和复用。\n\n**方案取舍**：我先把文档摄入、Dense Retrieval 和回答生成作为主链路，确保最基本的问答闭环可以重复验证；再把混合检索、Rerank、引用溯源和自动评测拆成独立迭代项。这样既避免为了展示技术栈一次堆入所有组件，也能在出现问题时判断它来自摄入、召回还是生成。\n\n**验收思路**：我把检索是否找到正确内容、回答是否忠于上下文、引用能否支持结论，以及 Bad Case 能否转成下一轮任务作为评测重点。这个项目最能体现我从用户问题、产品取舍到效果验收的完整思考，也说明我能在技术可行性和产品价值之间做出明确选择。",
    details: ["专业文档检索与答案溯源问题", "以 Dense Retrieval 为当前主链路", "高级能力拆成独立迭代项", "用检索、回答、引用和 Bad Case 验收"],
    limitations: "项目当前处于持续迭代阶段，不主动声称生产规模或真实用户增长。",
    claimIds: ["C3"],
    sourceIds: ["S1", "S3"],
    verification: "externally_verified",
    relatedProject: "rag-knowledge-base",
    evaluationGoal: "用一个项目证明产品判断、取舍和评测能力。",
    exclusivePoints: ["业务问题而非技术展示", "先主链路后迭代项", "检索与引用评测闭环"],
    avoidRepeating: ["三项个人优势", "完整自我介绍", "DeepFlow 详细流程"],
    responseShape: "project_arc",
    targetLength: { min: 390, max: 520 },
    preferredStoryIds: ["ST1"],
    followUpQuestions: ["你在这个项目中具体做了什么？", "最难的产品取舍是什么？", "你如何评估 RAG 回答质量？"],
    closingPurpose: "落到问题定义、方案取舍和评测闭环。",
  }),
  answer({
    id: "A04",
    question: "RAG 项目解决了什么问题？",
    matchKeywords: ["rag解决", "rag项目解决", "知识库问题"],
    standardAnswer: "**用户问题**：这个项目解决的不是“企业没有文档”，而是专业资料很多、真正需要答案时却很难快速找到正确内容，也很难判断生成结论依据了哪段原文。传统关键词搜索要求用户自己不断换词、打开文档和拼接信息；直接让模型回答，又可能得到看似流畅但无法追溯的结论。\n\n**产品目标**：我把它定义为三个连续环节——先让不同文档能够被统一摄入和检索，再让回答严格基于召回内容生成，最后通过引用与评测判断答案是否可靠。当前先用 Dense Retrieval 跑通主链路，再逐步验证混合检索、Rerank 和引用溯源。核心价值不是增加一个聊天入口，而是降低用户获得可信答案、检查依据和继续行动的成本，让回答真正成为专业决策的信息入口。",
    details: ["专业资料难以快速找到正确内容", "生成结论缺少原文依据", "摄入、检索、生成和评测链路"],
    limitations: "公开仓库证明当前设计与部分实现，不等同于所有规划能力均已运行验证。",
    claimIds: ["C3"], sourceIds: ["S1", "S3"], verification: "externally_verified", relatedProject: "rag-knowledge-base",
    evaluationGoal: "讲清用户问题和产品目标，不展开个人贡献或技术选型细节。",
    exclusivePoints: ["资料多但可信答案获取成本高", "回答缺少可追溯依据", "降低可信答案获取成本"],
    avoidRepeating: ["个人三项优势", "完整评测方法", "AI 编程分工"],
    responseShape: "direct", targetLength: { min: 280, max: 400 }, preferredStoryIds: [],
    followUpQuestions: ["为什么先选择 Dense Retrieval？", "你如何判断回答是否可靠？", "这个项目目前做到什么阶段？"],
    closingPurpose: "回到用户获取可信答案的成本。",
  }),
  answer({
    id: "A05",
    question: "他在 RAG 项目中的个人贡献是什么？",
    matchKeywords: ["rag贡献", "rag个人贡献", "rag负责", "具体做了什么", "个人具体完成", "你做了什么", "你负责什么", "你的贡献", "如何评测", "用于评测", "ragas", "评测设计"],
    standardAnswer: "我在 RAG 项目中的核心贡献，不是把所有代码都归到自己名下，而是对产品目标、关键取舍和最终质量负责。\n\n**我做的判断**：我先定义专业文档问答真正需要解决的用户问题，把目标从“做一个能聊天的知识库”收敛到“更快获得有依据的可信答案”。基于这个目标，我确定以文档摄入—检索—生成为主链路，并把引用和评测放在可信度建设中，而不是作为展示功能。\n\n**我做的取舍**：项目早期有混合检索、Rerank、引用和自动评测等多个方向。我没有一次全部推进，而是先用 Dense Retrieval 建立可重复检查的基线，再把高级能力拆成独立实验，这样出现 Bad Case 时才能定位问题来自摄入、召回还是生成。\n\n**我如何验收**：我关注检索内容是否相关、回答是否忠于上下文、引用能否支持结论，并使用 RAGAS 等方法组织评测，让失败样本能够转成下一轮任务。AI 编程工具帮助我实现、调试和整理文档，但需求定义、迭代顺序、测试设计和最终验收由我负责。我的价值在于让工程实现始终服务于一个清楚的产品判断。",
    details: ["定义专业文档问答目标", "确定主链路和迭代顺序", "设计检索、回答、引用与 Bad Case 验收", "AI 辅助实现，本人负责判断和质量"],
    limitations: "不虚构固定的人工与 AI 代码贡献比例。",
    claimIds: ["C3"], sourceIds: ["S1", "S3"], relatedProject: "rag-knowledge-base",
    evaluationGoal: "区分产品决策、工程协作和最终责任，回答本人真正做了什么。",
    exclusivePoints: ["产品目标与主链路由本人定义", "迭代顺序和评测由本人设计", "AI 辅助实现但本人负责验收"],
    avoidRepeating: ["重新解释项目背景", "三项候选人优势", "虚构代码占比"],
    responseShape: "contribution", targetLength: { min: 420, max: 560 }, preferredStoryIds: ["ST1", "ST3"],
    followUpQuestions: ["你做过最关键的一次取舍是什么？", "如果检索效果不好，你会如何定位？", "AI 生成的代码你怎么验收？"],
    closingPurpose: "明确本人对产品判断和最终质量负责。",
  }),
  answer({
    id: "A06",
    question: "DeepFlow 是什么？",
    matchKeywords: ["deepflow", "deepflow是什么", "deepflow介绍", "研究工作台"],
    standardAnswer: "DeepFlow 是我围绕**复杂研究任务**设计的多 Agent 工作台。它要解决的问题是：如果把一个开放研究题一次性交给模型，任务很容易在中途跑偏，使用者既不知道它正在做什么，也很难判断最终结论是怎样形成的。\n\n我的产品思路不是简单增加 Agent 数量，而是先把研究过程拆成任务澄清、计划、检索、分析和报告等阶段，再让 Coordinator、Planner、Researcher、Coder 和 Reporter 承担不同职责。对于研究计划和方向调整这类高成本节点，我加入**人工确认**；对于检索和分析过程，则通过事件记录和引用保留可追踪性。\n\n当前 DeepFlow 已经形成从任务澄清到报告输出的**可演示 MVP**。这个项目让我更具体地理解：Agent 产品的价值不只来自自主执行，还来自过程是否可见、关键节点是否可控，以及最终成果能否沉淀为可检查、可继续使用的资产。",
    details: ["复杂研究任务容易失控", "按计划、检索、分析和报告拆分 Agent", "高成本节点加入人工确认", "形成可演示 MVP"],
    limitations: "不声称已经形成真实用户规模、生产并发或长期稳定性数据。",
    claimIds: ["C4"], sourceIds: ["S4"], verification: "externally_verified", relatedProject: "deepflow",
    evaluationGoal: "让面试官理解 DeepFlow 的用户问题、核心机制和产品价值。",
    exclusivePoints: ["开放研究任务容易跑偏", "Agent 分工与人工确认", "研究过程可追踪"],
    avoidRepeating: ["RAG 项目评测链路", "完整个人优势", "所有规划功能"],
    responseShape: "project_arc", targetLength: { min: 330, max: 460 }, preferredStoryIds: ["ST2"],
    followUpQuestions: ["为什么需要人工确认？", "Agent 之间如何协作？", "这个项目最大的挑战是什么？"],
    closingPurpose: "突出 Agent 产品的可控性和成果物沉淀。",
  }),
  answer({
    id: "A07",
    question: "他如何使用 AI 编程工具？",
    matchKeywords: ["ai编程", "如何使用ai", "ai辅助", "ai编程占比", "ai写了多少", "代码是不是ai写的"],
    standardAnswer: "我会直接承认 AI 编程工具深度参与了项目实现，但它没有替我承担**产品责任**。我的分工很明确：我负责定义要解决的问题、拆解任务、选择方案、制定验收标准，并判断结果是否真的可用；AI 主要作为**工程协作者**，帮助生成代码、补测试、定位错误和整理文档。\n\n在具体协作中，我会先把需求、接口和不能破坏的约束写清楚，再让 AI 处理边界明确的实现任务。生成结果出来后，我不会只看“代码能不能运行”，还会检查它是否符合用户流程、有没有引入新的事实或安全风险、是否保持现有接口兼容，以及失败时有没有稳定回退。关键改动必须经过自动测试、Lint、Build 和实际流程验收。\n\n如果结果偏离需求，我会回到问题定义重新拆解，而不是继续让模型盲目修改。我不虚构统一的代码贡献比例，因为不同任务差异很大；但需求判断、方案取舍和**最终质量责任**始终在我。这也是我理解的 AI 原生产品能力：提高实现速度，同时保留人的判断和验收。",
    details: ["AI 深度参与实现但不承担产品责任", "本人负责问题、方案、验收和质量", "通过测试、Lint、Build 与流程检查验收", "不虚构固定贡献比例"],
    limitations: "不同项目的具体代码分工不同，没有统一百分比。",
    claimIds: ["C2", "C3", "C4", "C5", "C7", "C12"], sourceIds: ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9"],
    evaluationGoal: "坦诚说明 AI 参与程度，同时证明本人掌握产品判断和质量控制。",
    exclusivePoints: ["AI 深度参与工程实现", "本人负责需求、取舍和验收", "用工程门禁而非运行结果验收"],
    avoidRepeating: ["重新介绍所有项目", "回避 AI 参与", "虚构代码比例"],
    responseShape: "direct", targetLength: { min: 360, max: 500 }, preferredStoryIds: ["ST3"],
    followUpQuestions: ["举一个 AI 生成结果不符合预期的例子。", "你如何判断原型已经可以交付？", "你和工程师相比的定位是什么？"],
    closingPurpose: "把 AI 协作能力落到产品责任和质量控制。",
  }),
  answer({
    id: "A08",
    question: "他的核心技术能力有哪些？",
    matchKeywords: ["技术能力", "技术栈", "会什么", "技能如何", "sql", "python", "fastapi"],
    standardAnswer: "我的技术能力主要服务于**产品判断和快速验证**，而不是和纯工程师比较底层开发深度。\n\n数据侧，我可以使用 SQL、Python 处理数据、理解指标并检查数据质量；AI 应用侧，我熟悉 RAG、Prompt、工作流、评测集与 RAGAS 等方法，能够把一个模型能力拆成检索、生成、引用和评测环节；工程侧，我能理解 FastAPI、Milvus、前端、异步任务和部署链路，也能借助 AI 编程工具把需求推进成可运行原型。\n\n这种**技术宽度**对产品工作有两个直接价值。第一，我与算法和工程同学沟通时能够理解实现约束，不会提出完全脱离数据和系统条件的需求；第二，我可以在需求阶段提前定义输入、接口、异常状态和验收方式，并亲自验证关键流程。我的定位不是替代工程师，而是把业务问题翻译成团队能够实现、测试和**持续迭代**的产品方案。",
    details: ["SQL 与 Python 数据处理", "RAG、Prompt、工作流和评测", "理解应用工程与部署链路", "把业务问题转成实现和验收要求"],
    limitations: "不把产品工程能力包装为纯工程师的底层技术深度。",
    claimIds: ["C2", "C3", "C4", "C5"], sourceIds: ["S1", "S3", "S4", "S5"],
    evaluationGoal: "说明技术能力如何服务产品工作，而不是罗列技术名词。",
    exclusivePoints: ["数据处理与指标理解", "AI 应用链路理解", "把技术约束转成产品和验收要求"],
    avoidRepeating: ["完整成长经历", "审计职责", "项目完成边界"],
    responseShape: "fit_mapping", targetLength: { min: 320, max: 450 }, preferredStoryIds: [],
    followUpQuestions: ["你如何设计 AI 产品评测？", "你能独立完成什么程度的原型？", "你如何与工程团队协作？"],
    closingPurpose: "明确技术能力在产品团队中的实际用途。",
  }),
  answer({
    id: "A09",
    question: "审计经历如何帮助他做 AI 产品？",
    matchKeywords: ["审计经历", "审计帮助", "业务理解"],
    standardAnswer: "审计经历给我的最大帮助，不是增加一个行业标签，而是让我习惯从真实流程、**证据和风险**出发看产品。做审计时，我需要关注数据从哪里来、经过哪些处理、过程有没有留下证据、异常如何被发现，以及最终结果能否被另一个人复核。\n\n这些习惯可以直接迁移到企业 AI 产品。设计知识库时，我会关注答案是否基于正确内容、引用能否支持结论；设计 Agent 工作流时，我会区分哪些任务可以自动执行、哪些高成本节点必须**人工确认**；处理企业数据时，我会先界定授权、使用范围和输出边界。与此同时，审计现场也让我看到，很多流程问题不在于缺少功能，而在于资料分散、交接成本高、异常确认反复。\n\n因此，相比只从模型能力出发，我会更早判断一个方案在真实业务中是否可用、可控、可复核，以及它是否真的降低一线执行成本。这种**企业流程理解**，是我做 B 端 AI 产品时很重要的差异点。",
    details: ["从真实流程和风险看产品", "关注数据来源、证据、异常和复核", "迁移到引用、人审与权限设计", "提前识别企业落地成本"],
    limitations: "不披露审计客户、底稿和企业机密。",
    claimIds: ["C6", "C7", "C9", "C10"], sourceIds: ["S1", "S8", "S9"],
    evaluationGoal: "证明审计经验如何转化为企业 AI 产品方法。",
    exclusivePoints: ["流程与风险意识", "证据链和可复核性", "企业 AI 的人审与数据边界"],
    avoidRepeating: ["重新介绍学校", "完整项目列表", "任职数字"],
    responseShape: "fit_mapping", targetLength: { min: 340, max: 480 }, preferredStoryIds: ["ST4", "ST6"],
    followUpQuestions: ["举一个审计问题转成产品的例子。", "这如何影响你的 Agent 设计？", "你如何处理企业数据边界？"],
    closingPurpose: "突出企业方案的可用、可控和可复核。",
  }),
  answer({
    id: "A10",
    question: "他的德勤 IT 审计实习做了什么？",
    matchKeywords: ["德勤实习", "it审计实习", "ipe"],
    standardAnswer: "我在 2026 年 1 月至 4 月参与德勤 IT 审计实习，工作主要涉及**IPE 与日志核查**。具体来说，我需要按照既定审计程序核对系统输出和相关资料，检查记录之间是否一致，并在口径不清楚或信息不完整时进一步确认。\n\n这段经历让我比较具体地理解了企业系统中的**数据来源和证据链**。一个结果是否可信，往往不只取决于最后一张报表，还取决于数据从哪里产生、经过哪些处理、谁在什么节点确认，以及异常是否被完整记录。它也让我意识到，企业产品不能只追求功能可用，还要考虑结果是否可追溯、错误能否被及时发现，以及敏感数据应该如何被限制使用。\n\n这些认识后来直接影响了我的 AI 产品设计：知识库需要引用支持，Agent 的关键动作需要人审，模型处理的数据也必须有清晰边界，也就是把**引用支持与人审**直接放进产品流程。",
    details: ["2026 年 1 月至 4 月德勤 IT 审计实习", "IPE 与日志核查", "理解企业系统数据来源和证据链", "迁移到引用、人审和数据边界"],
    limitations: "不披露客户、系统明细、底稿或企业机密。",
    claimIds: ["C9"], sourceIds: ["S1"],
    evaluationGoal: "讲清职责和能力迁移，不把实习包装成 AI 产品任职。",
    exclusivePoints: ["IPE 与日志核查职责", "企业系统数据与证据链", "对 AI 产品可靠性的影响"],
    avoidRepeating: ["财务审计职责", "项目技术栈", "客户和底稿"],
    responseShape: "direct", targetLength: { min: 300, max: 420 }, preferredStoryIds: ["ST6"],
    followUpQuestions: ["IT 审计和财务审计最大的差异是什么？", "这段经历如何影响你的产品设计？", "你如何保护企业敏感数据？"],
    closingPurpose: "落到企业 AI 产品的可靠性意识。",
  }),
  answer({
    id: "A11",
    question: "他的容诚审计实习做了什么？",
    matchKeywords: ["容诚实习", "财务审计实习", "函证盘点"],
    standardAnswer: "我在 2025 年 1 月至 3 月参与容诚财务审计实习，主要接触**底稿、函证和盘点**等基础审计工作。现场工作让我看到，一项看起来简单的流程，背后往往包含资料收集、多人协作、异常确认和结果留痕；真正消耗时间的，也常常不是某个复杂判断，而是信息格式不一致、上下文缺失和反复确认。\n\n这段经历对我做产品最直接的影响，是让我更关注**一线执行成本**。设计企业工具时，我不会只问功能能不能实现，还会考虑资料如何进入系统、用户在哪一步最容易出错、系统应该给出建议还是直接执行、哪些结果必须人工确认，以及操作之后能否留下可复核记录。\n\n它也为我后来把审计资料整理和日志核查抽象成产品原型提供了业务基础：先找到重复而高频的环节，再用规则、OCR 或模型能力降低整理成本，同时保留必要的**人审和数据边界**。",
    details: ["2025 年 1 月至 3 月容诚财务审计实习", "底稿、函证和盘点", "理解现场协作和执行成本", "形成审计工具的业务基础"],
    limitations: "不披露客户、底稿或业务数据。",
    claimIds: ["C10"], sourceIds: ["S1"],
    evaluationGoal: "讲清财务审计的一线业务理解如何迁移到产品。",
    exclusivePoints: ["底稿、函证和盘点职责", "一线执行与协作成本", "审计工具的场景来源"],
    avoidRepeating: ["IT 审计职责", "技术组件", "客户和业务数据"],
    responseShape: "direct", targetLength: { min: 300, max: 430 }, preferredStoryIds: ["ST4"],
    followUpQuestions: ["你从审计中发现了什么产品机会？", "你如何判断一个流程值得被 AI 改造？", "你做过哪些审计工具？"],
    closingPurpose: "落到一线业务理解和产品机会识别。",
  }),
  answer({
    id: "A12",
    question: "他有哪些本地优先产品？",
    matchKeywords: ["本地优先", "效率工具", "桌面产品", "downloadsbutler", "downloadbutler", "thirtyminutebrain", "readlaterregret"],
    standardAnswer: "我做过 Thirty-Minute Brain、Read-Later Regret 和 Downloads Butler 三个本地优先工具，分别处理**上下文恢复**、**信息债管理**和**下载文件整理**。它们不是三个孤立的技术练习，而是同一种产品方法的不同验证：从自己高频遇到的小摩擦出发，先找到最小闭环，再决定是否值得继续扩展。\n\nThirty-Minute Brain 关注的是工作被打断后如何快速恢复上下文；Read-Later Regret 处理“收藏很多、真正消化很少”的信息债；Downloads Butler 则把混乱的下载目录转成可确认的整理建议。三个工具都强调用户控制：数据尽量留在本地，文件移动或自动处理前保留确认，敏感内容不为了便利默认上传。\n\n这些项目让我形成了一个很实用的习惯：先用轻量方案验证高频问题，把隐私、误操作和撤销机制直接写进产品流程，再根据真实使用决定要不要搭建更复杂的平台。",
    details: ["三个本地优先效率工具", "从高频小摩擦出发", "数据留在本地并保留用户控制", "先验证轻量闭环"],
    limitations: "不声称拥有公开用户规模、留存或长期价值数据。",
    claimIds: ["C5"], sourceIds: ["S1", "S5", "S6", "S7"], verification: "externally_verified", relatedProject: "local-first-tools",
    evaluationGoal: "展示从小问题快速验证产品闭环和隐私约束的能力。",
    exclusivePoints: ["三个具体小问题", "本地优先与用户控制", "轻量验证方法"],
    avoidRepeating: ["RAG 评测", "审计职责", "生产规模"],
    responseShape: "project_arc", targetLength: { min: 330, max: 460 }, preferredStoryIds: ["ST5"],
    followUpQuestions: ["为什么选择本地优先？", "哪个工具最值得继续做？", "你如何避免文件工具误操作？"],
    closingPurpose: "体现轻量验证和隐私默认设计。",
  }),
  answer({
    id: "A13",
    question: "他如何处理隐私和企业数据？",
    matchKeywords: ["隐私", "企业数据", "数据边界", "机密"],
    standardAnswer: "我处理隐私和企业数据的原则是：**先确认数据资格**，再讨论模型能做什么。具体设计时，我会依次确认数据来源与授权、完成任务所需的**最小使用范围**、数据在哪里处理、结果会被发送到哪里，以及出现异常后能否追溯和撤回。\n\n在本地优先工具中，我尽量让数据保留在设备内，并在文件移动或自动处理前保留用户确认；在审计相关原型中，我只使用演示数据，不接触真实客户资料；在 Agent 或知识库流程中，则通过人工确认、引用支持和明确的输出边界降低误用风险。如果某项功能必须依赖更敏感的数据，我会先判断能否通过脱敏、范围缩小或本地处理实现，而不是默认把数据交给模型。\n\n对企业 AI 产品来说，隐私不是上线前补充的一页说明，而是需求范围、交互流程、权限和异常处理共同组成的**产品约束**。",
    details: ["先判断数据能否进入系统", "关注授权、范围、位置和输出", "本地优先与演示数据", "隐私作为产品流程"],
    limitations: "不披露审计客户、底稿、企业机密或未公开个人信息。",
    claimIds: ["C7", "C12"], sourceIds: ["S1", "S2", "S8", "S9"],
    evaluationGoal: "说明可操作的隐私产品原则，而不是复述拒答政策。",
    exclusivePoints: ["先判断数据使用资格", "本地优先和演示数据", "隐私进入产品流程"],
    avoidRepeating: ["完整审计经历", "模型技术细节", "安全认证"],
    responseShape: "direct", targetLength: { min: 300, max: 430 }, preferredStoryIds: ["ST5"],
    followUpQuestions: ["Agent 产品中哪些节点需要人工确认？", "你如何处理模型输出风险？", "本地优先有什么取舍？"],
    closingPurpose: "强调隐私是产品设计约束。",
  }),
  answer({
    id: "A14",
    question: "他的主要短板是什么？",
    matchKeywords: ["短板", "不足", "能力缺口"],
    standardAnswer: "我目前最需要补强的，是把原型阶段的产品判断延伸到真实用户、长期运营和跨团队协作中。现阶段我已经能独立完成问题拆解、方案取舍、原型推进和评测迭代，但还缺少在较长周期里持续观察用户行为、生产稳定性和商业结果的完整经历。\n\n**它对我的影响**：如果只停留在原型阶段，容易高估功能完成度，却低估推广成本、协作阻力和长期维护。因此我会主动区分“功能可用”“用户愿意用”和“业务值得持续投入”，不会把一次演示成功直接等同于产品成功。\n\n**我的补强方式**：进入真实业务团队后，我希望主动参与用户访谈、指标定义、上线复盘和跨职能推进，让每轮需求都能回到行为与结果上验证。同时我现在就能贡献快速拆解复杂问题、建立最小验证方案和用 Bad Case 推动迭代的能力。这个短板说明我的经验边界，也说明我下一阶段的成长方向非常明确。",
    details: ["真实用户结果积累不足", "长期生产稳定性经验不足", "复杂跨团队推进经验仍需补强", "通过真实业务、指标和复盘补强"],
    limitations: "短板来自当前经历阶段，不等于完全不具备相关能力。",
    claimIds: ["C8"], sourceIds: ["S1", "S10"],
    evaluationGoal: "展现自我认知、影响判断和具体补强行动，不自我否定。",
    exclusivePoints: ["真实用户与长期协作积累不足", "原型完成不等于产品成功", "进入真实团队补强"],
    avoidRepeating: ["再次罗列全部优势", "公开证据措辞", "免责声明"],
    responseShape: "shortcoming", targetLength: { min: 330, max: 460 }, preferredStoryIds: [],
    followUpQuestions: ["你准备如何验证真实用户价值？", "你希望入职后优先补哪项能力？", "你如何看待原型和产品成功的差别？"],
    closingPurpose: "把短板转成明确的成长计划和初级岗位价值。",
  }),
  answer({
    id: "A15",
    question: "请讲一个项目挑战或失败案例。",
    matchKeywords: ["面试核实", "追问", "遇到什么困难", "项目困难", "失败案例", "项目挑战", "挑战", "失败"],
    standardAnswer: "RAG 项目中一个很典型的挑战，是我早期把“功能更多”误认为“产品更完整”。混合检索、Rerank、引用和自动评测看起来都值得加入，但它们同时推进后，一旦回答出现 Bad Case，我很难判断问题究竟来自文档摄入、召回排序还是生成环节。功能在增加，学习效率反而下降。\n\n**我的取舍**：当时最重要的不是继续补功能，而是先建立一个可解释、可重复的基线。于是我把方案重新拆成验证顺序，先用 Dense Retrieval 跑通摄入—检索—生成主链路，固定基础流程；再把高级检索和评测能力拆成独立实验，每轮只改变少量变量。\n\n**我的验收**：我不再用功能数量判断进度，而是分别检查召回内容是否相关、回答是否忠于上下文、引用能否支持结论，以及失败样本能否转成下一轮任务。这个调整没有制造一个漂亮的硬指标，但它让项目从“堆能力”转向“积累有效判断”。我由此认识到，AI 产品经理的重要工作是控制变量、管理不确定性，并让团队清楚下一步为什么值得做。",
    details: ["早期把功能数量误认为完整度", "同时推进导致 Bad Case 难定位", "回到 Dense Retrieval 基线并拆分实验", "用召回、忠实度、引用和失败样本验收"],
    limitations: "这是方案取舍与复盘，不虚构线上事故或业务损失。",
    claimIds: ["C2", "C3", "C4", "C8"], sourceIds: ["S1", "S3", "S4", "S10"], relatedProject: "rag-knowledge-base",
    evaluationGoal: "用真实方案调整证明复盘、控制变量和产品取舍能力。",
    exclusivePoints: ["功能堆叠造成问题定位困难", "建立基线并控制变量", "从功能数量转向质量验收"],
    avoidRepeating: ["泛泛谈产品闭环", "重新介绍 RAG 背景", "虚构线上事故"],
    responseShape: "star", targetLength: { min: 420, max: 560 }, preferredStoryIds: ["ST1", "ST8"],
    followUpQuestions: ["你为什么选择先保留 Dense Retrieval？", "如果再次做这个项目会如何规划？", "DeepFlow 中有类似的取舍吗？"],
    closingPurpose: "落到控制变量和明确取舍的产品能力。",
  }),
  answer({
    id: "A16",
    question: "他的教育背景是什么？",
    matchKeywords: ["教育背景", "学校专业", "东北大学"],
    standardAnswer: "我就读于东北大学应用统计学专业，预计 2027 年毕业。\n\n**形成的判断方式**：这个背景对我做 AI 产品最直接的帮助，不只是会处理数据，而是让我习惯先明确问题与评价标准，再选择样本、指标和方法，最后关注误差与结论是否可靠。\n\n**对产品工作的帮助**：概率统计、数据库和编程相关学习，让我能理解评测结果、数据质量以及技术方案的基本约束。面对模型效果时，我不会只看几个表现好的案例，而会进一步追问样本是否有代表性、指标是否对应真实目标、Bad Case 是否暴露了系统性问题。对我来说，应用统计学不是简历上的专业标签，而是我做 AI 产品评测、需求判断和迭代分析的底层训练。",
    details: ["东北大学应用统计学专业", "预计 2027 年毕业", "形成指标和数据判断习惯"],
    limitations: "教育信息以正式学籍或简历为准。",
    claimIds: ["C1"], sourceIds: ["S1"],
    evaluationGoal: "说明教育背景及其对 AI 产品工作的实际帮助。",
    exclusivePoints: ["应用统计学背景", "指标与数据判断习惯", "评测思维基础"],
    avoidRepeating: ["完整自我介绍", "审计经历", "项目技术栈"],
    responseShape: "direct", targetLength: { min: 240, max: 360 }, preferredStoryIds: [],
    followUpQuestions: ["统计学如何帮助你设计评测？", "你最擅长的数据工具是什么？", "为什么从统计学转向 AI 产品？"],
    closingPurpose: "把专业背景落到评测思维。",
  }),
  answer({
    id: "A17",
    question: "他的英语和证书情况如何？",
    matchKeywords: ["英语", "四六级", "acca", "证书"],
    standardAnswer: "我的 CET-4 成绩是 619，CET-6 是 520，并完成了部分 ACCA 科目学习。对我而言，这些经历的价值不在于单纯罗列证书，而在于它们能直接支持 AI 产品工作。\n\n**英语能力**让我可以直接阅读海外模型文档、开源项目说明、AI 产品案例和工程资料，减少经过二手转述后的信息损耗，也便于持续跟踪模型能力与产品范式的变化。**ACCA 和会计学习**则让我更容易理解财务流程、业务指标、控制要求和企业沟通语言。两者结合后，我能更快建立**技术与业务连接**，这也是我进入企业 AI 场景时的一项基础能力。",
    details: ["CET-4 619", "CET-6 520", "部分 ACCA 科目", "支持阅读技术资料和理解企业业务"],
    limitations: "成绩与科目完成情况以正式材料为准。",
    claimIds: ["C1", "C2"], sourceIds: ["S1"],
    evaluationGoal: "说明英语和证书如何支持工作，不罗列无关荣誉。",
    exclusivePoints: ["英语阅读技术资料", "ACCA 支持企业业务理解"],
    avoidRepeating: ["学校背景", "项目经历", "三项个人优势"],
    responseShape: "direct", targetLength: { min: 230, max: 350 }, preferredStoryIds: [],
    followUpQuestions: ["你通常如何跟踪海外 AI 产品？", "财务知识如何帮助你理解 B 端场景？", "你最近在学习什么？"],
    closingPurpose: "落到技术信息获取和企业语境理解。",
  }),
  answer({
    id: "A18",
    question: "Ask Me 项目体现了什么能力？",
    matchKeywords: ["ask me能力", "数字分身", "本项目能力"],
    standardAnswer: "Ask Me 最能体现的是我如何把一个模糊的求职目标，拆成一套完整的 AI 产品闭环，而不是只做一个聊天页面。传统简历的信息密度有限、不能继续追问，候选人的项目判断和个人贡献也很难在短时间内讲清楚。因此我先从招聘方的决策过程出发，明确产品要帮助对方完成“快速了解—重点追问—判断是否进入下一轮—查看简历或联系”的路径。\n\n**回答层**：我把个人经历、项目和 STAR 故事整理为结构化知识，并设计核心问题、上下文指代、事实门禁和稳定回退，让数字分身既敢于表达，也不虚构一问即穿的结果。\n\n**工程与迭代层**：我接入模型、限流、预算、匿名事件和固定简历入口，再通过自动评测和模拟面试持续发现回答重复、过度保守或重点不清的问题。我也会根据不同提问意图重新分配内容，避免每个答案都重复三项优势。这个项目体现的不只是实现能力，更是我从用户决策出发定义产品、平衡表现力与可信度，并持续验收体验的能力。",
    details: ["从招聘决策路径定义产品", "结构化知识、稳定回答和事实门禁", "模型、限流、分析与简历链路", "通过评测持续修正回答体验"],
    limitations: "项目仍需真人招聘者验证实际面试转化价值。",
    claimIds: ["C12"], sourceIds: ["S2"], relatedProject: "ask-me",
    evaluationGoal: "证明从招聘问题到 AI 产品闭环的完整设计能力。",
    exclusivePoints: ["招聘决策路径", "回答、工程和转化三层设计", "根据评测修正产品方向"],
    avoidRepeating: ["完整自我介绍", "RAG 项目细节", "无关技术栈"],
    responseShape: "project_arc", targetLength: { min: 380, max: 520 }, preferredStoryIds: ["ST3", "ST8"],
    followUpQuestions: ["你为什么要做这个项目？", "你如何判断回答质量？", "这个项目目前最大的不足是什么？"],
    closingPurpose: "落到需求洞察、产品取舍和持续验收。",
  }),
  answer({
    id: "A19",
    question: "公开项目是否有真实用户增长数据？",
    matchKeywords: ["用户增长", "用户规模", "真实用户", "用户测试", "满意度", "服务什么用户", "什么用户", "业务价值", "解决什么业务问题", "目前有什么价值", "留存数据", "结果如何", "项目结果", "生产状态"],
    standardAnswer: "目前我的公开项目主要完成了问题定义、核心流程和可演示原型，还没有形成可以公开说明的用户增长、留存、满意度或商业化数据。已经完成并可以展示的，是 RAG 的文档摄入—检索—生成主链路、DeepFlow 的研究工作台 MVP，以及多个本地优先工具从输入到输出的完整使用流程。\n\n**当前产品价值**：这些成果证明我能够把一个业务观察转成明确方案，完成关键取舍，并把方案推进到可运行、可检查的阶段；但这还不能替代真实市场验证。\n\n**下一步如何验证**：我会先选择目标用户和高频任务，让他们在尽量少解释的情况下独立完成流程，再记录任务完成情况、关键阻力、重复使用意愿和 Bad Case。之后根据结果判断是优化核心路径、收缩需求，还是继续投入高级能力。相比提前包装增长故事，我更希望用真实行为完成从“原型可用”到“产品值得用”的验证。",
    details: ["已形成问题定义、核心流程和可演示原型", "没有公开的大规模增长或留存数据", "下一步通过真实任务和反馈验证"],
    limitations: "公开证据不足不代表项目没有任何使用者。",
    claimIds: ["C3", "C4", "C5", "C8"], sourceIds: ["S1", "S3", "S4", "S5", "S6", "S7", "S10"],
    evaluationGoal: "清楚区分原型成果与市场结果，并给出下一步验证方法。",
    exclusivePoints: ["当前成果是产品闭环和原型", "尚无公开规模数据", "下一步验证真实任务和重复使用"],
    avoidRepeating: ["重新罗列个人优势", "免责声明", "虚构用户反馈"],
    responseShape: "shortcoming", targetLength: { min: 340, max: 480 }, preferredStoryIds: [],
    followUpQuestions: ["你会如何设计第一轮用户测试？", "你最希望验证哪个项目？", "原型成功和产品成功有什么差别？"],
    closingPurpose: "区分已经证明的能力和下一阶段产品验证。",
  }),
  answer({
    id: "A20",
    question: "可以根据这些材料直接给出录用结论吗？",
    matchKeywords: ["录用结论", "是否录用", "值得录用", "进入下一轮", "继续面试", "建议进入下一轮"],
    standardAnswer: "我认为自己值得进入下一轮。理由不是我已经具备成熟 AI 产品经理的全部经验，而是我作为应届候选人，已经展示了三项值得继续验证的组合能力：能用数据和评测思维定义 AI 效果，能理解企业流程、证据链和数据边界，也能把产品判断推进成可运行、可验收的原型。这种复合背景，是我在初级 AI 产品岗位上的核心价值。\n\n**下一轮最值得验证两件事**：第一，让我现场拆解一次 RAG 或 Agent 项目的关键取舍，讲清楚用户问题、方案选择、本人判断、AI 工具协作和验收标准；第二，给我一个新的企业 AI 场景，看我如何定义目标用户、核心任务、风险边界和最小验证方案。这样比继续罗列技术栈，更能判断我的思考是否可以迁移。\n\n如果我能在这些追问中保持当前材料里的判断深度，就说明我不仅能快速学习和做出原型，也具备在真实团队中承担需求分析、方案推进和效果验证的潜力。因此我的建议是进入下一轮，再通过现场问题验证上限，而不是仅凭材料直接给出录用结论。",
    details: ["建议进入下一轮", "应届阶段已展示评测、业务和落地潜力", "下一轮验证项目取舍与职责分工", "用新场景验证迁移能力"],
    limitations: "进入下一轮建议不等于直接录用结论。",
    claimIds: ["C2", "C3", "C4", "C6", "C8", "C12"], sourceIds: ["S1", "S2", "S3", "S4", "S10"],
    evaluationGoal: "给出明确招聘建议，并告诉面试官下一轮最值得验证什么。",
    exclusivePoints: ["明确建议进入下一轮", "判断依据是应届阶段潜力", "给出项目取舍和新场景两类验证"],
    avoidRepeating: ["完整自我介绍", "再次逐项介绍所有项目", "机械免责声明"],
    responseShape: "recommendation", targetLength: { min: 360, max: 500 }, preferredStoryIds: [],
    followUpQuestions: ["请现场拆解一次最关键的产品取舍。", "给你一个新的企业 AI 场景，你会如何定义 MVP？", "你希望下一轮重点展示哪项能力？"],
    closingPurpose: "明确下一轮验证方向和候选人培养潜力。",
  }),
  answer({
    id: "A21",
    question: "他对企业级 AI 场景有哪些理解？",
    matchKeywords: ["企业级ai场景", "企业ai场景", "企业级ai理解", "企业ai理解", "企业场景理解"],
    standardAnswer: "我对企业级 AI 的理解，核心不是“把模型接进系统”，而是让它在真实流程里同时做到有价值、可控、可验证。审计经历让我看到，企业场景中的难点往往不只是生成答案，而是数据从哪里来、结论能否复核、异常由谁处理，以及新工具是否真的降低一线执行成本。\n\n**先判断流程价值**：我会从高频任务、信息断点和重复确认入手，判断问题更适合规则、检索、模型还是流程改造，而不是为了使用 AI 强行寻找场景。\n\n**再设计责任边界**：低风险、可回退的步骤可以自动化；方向性、高成本或涉及敏感数据的节点保留人工确认。RAG 的引用支持和 DeepFlow 的人审节点，都是这种思路的体现。\n\n**最后建立验证闭环**：先用轻量方案跑通核心任务，再通过评测集、Bad Case 和流程反馈决定下一轮投入。对我来说，企业 AI 产品的竞争力不只来自模型能力，更来自业务理解、可控流程和持续验证三者的结合。",
    details: ["企业 AI 先判断真实流程价值", "按风险与责任设计自动化和人审边界", "以评测集和 Bad Case 建立迭代闭环", "审计、RAG 与 DeepFlow 提供场景实践"],
    limitations: "不把原型阶段的企业场景理解描述为大规模生产经验。",
    claimIds: ["C3", "C4", "C6", "C7"], sourceIds: ["S1", "S3", "S4", "S8", "S9"],
    evaluationGoal: "展示对企业 AI 价值、责任边界和验证方式的系统理解，而不是重复项目介绍。",
    exclusivePoints: ["从流程价值而非模型能力出发", "自动化与人工确认的责任边界", "轻量验证后再逐步升级"],
    mustInclude: ["流程价值", "责任边界", "轻量方案"],
    avoidRepeating: ["完整审计经历", "逐项罗列 RAG 技术栈", "再次复述三项个人优势"],
    responseShape: "fit_mapping", targetLength: { min: 390, max: 520 }, preferredStoryIds: ["ST6", "ST7"],
    followUpQuestions: ["你如何判断一个企业流程值得被 AI 改造？", "哪些 Agent 节点必须保留人工确认？", "你会如何设计企业 AI 的第一轮验证？"],
    closingPurpose: "落到企业 AI 产品的价值、控制与验证三项判断。",
  }),
  answer({
    id: "A22",
    question: "他如何把业务问题转化为 AI 产品方案？",
    matchKeywords: ["业务问题转化为ai产品", "业务问题转化", "转化为ai产品方案", "业务转产品方案", "形成ai产品方案"],
    standardAnswer: "我把业务问题转化为 AI 产品方案时，不会先列模型能力，而是先把“谁在什么流程里遇到什么阻力”说清楚，再决定 AI 应该介入哪一步。审计资料整理、专业文档问答和复杂研究任务虽然不同，但我的转化方法基本一致。\n\n**第一步是定义问题**：拆出目标用户、核心任务、现有处理方式和真正的高成本环节。例如资料分散、上下文缺失、重复核对或结论难以追溯，分别对应不同的产品切入点。\n\n**第二步是划分方案边界**：稳定规则交给确定性流程，语义理解和内容生成交给模型，高风险判断保留人工确认；再把输入、关键状态、异常路径和输出资产设计完整。\n\n**第三步是建立验证闭环**：先用最小链路验证任务能否完成，再检查检索质量、回答忠实度、引用支持、流程阻力和 Bad Case。只有核心问题被验证后，我才会继续增加 Rerank、多 Agent 或更复杂的自动化能力。这样做能让技术选择始终服务于业务问题，也让每一轮迭代都有明确理由。",
    details: ["从用户、任务和流程阻力定义问题", "区分规则、模型和人工确认的职责", "用最小链路与 Bad Case 验证", "验证后再增加复杂能力"],
    limitations: "方法来自已公开的审计、RAG、DeepFlow 与工具项目，不虚构正式商业交付。",
    claimIds: ["C3", "C4", "C6", "C7", "C12"], sourceIds: ["S1", "S2", "S3", "S4", "S8", "S9"],
    evaluationGoal: "讲清从业务洞察到 AI 方案、责任边界和验证闭环的完整方法。",
    exclusivePoints: ["先定义用户任务和流程阻力", "划分规则、模型与人工责任", "最小链路验证后再升级"],
    avoidRepeating: ["只罗列项目名称", "从技术栈开始回答", "泛泛强调产品闭环"],
    responseShape: "project_arc", targetLength: { min: 400, max: 540 }, preferredStoryIds: ["ST1", "ST7"],
    followUpQuestions: ["请用 RAG 项目具体演示这套方法。", "你如何选择规则、模型和人工确认？", "最小验证方案应该包含哪些指标？"],
    closingPurpose: "体现从业务问题到可验证 AI 产品的结构化转化能力。",
  }),
  answer({
    id: "A23",
    question: "他在数据分析与 AI 评测方面有哪些实践？",
    matchKeywords: ["数据分析与ai评测", "数据分析实践", "ai评测实践", "评测方面的实践", "数据评测实践"],
    standardAnswer: "我在数据分析与 AI 评测上的实践，重点不是展示一组工具名，而是用数据帮助产品做判断：先定义什么叫有效，再选择指标和样本，最后把失败案例转成下一轮迭代任务。\n\n**数据分析基础**：应用统计学训练让我习惯关注样本、指标、误差和结论可靠性；项目中可以使用 SQL、Python 处理数据、检查质量并理解指标变化。我不会只看平均结果，也会关注哪些类型的问题持续失败。\n\n**AI 评测实践**：在 RAG 项目中，我把效果拆成召回内容是否相关、回答是否忠于上下文、引用能否支持结论，并结合 RAGAS 等方法组织评测；在 DeepFlow 中，我更关注任务过程是否可见、关键节点是否经过确认、最终报告能否追溯到研究过程。\n\n**迭代方式**：先建立 Dense Retrieval 等可重复检查的基线，再逐项验证混合检索、Rerank 或自动评测，避免多个变量同时变化。对我来说，评测不是上线前的一次打分，而是连接问题定位、产品取舍和版本优先级的持续机制。",
    details: ["统计学形成样本、指标和误差意识", "SQL 与 Python 支持数据处理和质量检查", "RAG 关注召回、忠实度、引用和 RAGAS", "以基线和 Bad Case 驱动迭代"],
    limitations: "不补充未记录的评测集规模、准确率提升或业务结果数字。",
    claimIds: ["C1", "C2", "C3", "C4"], sourceIds: ["S1", "S3", "S4"],
    evaluationGoal: "证明数据分析和 AI 评测如何实际支持产品判断与迭代。",
    exclusivePoints: ["从指标、样本和误差定义效果", "拆解 RAG 与 Agent 的评测对象", "用基线和 Bad Case 推动迭代"],
    avoidRepeating: ["完整学校介绍", "只罗列 SQL 和 Python", "虚构评测提升数字"],
    responseShape: "fit_mapping", targetLength: { min: 390, max: 520 }, preferredStoryIds: ["ST1", "ST8"],
    followUpQuestions: ["你会如何建立第一版 RAG 评测集？", "Bad Case 如何转成产品优先级？", "你如何避免评测指标和用户价值脱节？"],
    closingPurpose: "落到用数据和评测支持产品取舍的能力。",
  }),
  answer({
    id: "A24",
    question: "RAG 项目的引用准确率提升了多少？",
    matchKeywords: ["引用准确率", "准确率提升", "评测提升数字", "提升了多少", "效果提升数字"],
    standardAnswer: "目前没有可以公开、复现的引用准确率提升数字，这一点需要直接说清楚。现有材料能确认的是 RAG 已形成 Dense Retrieval 主链路，并把引用支持和自动评测纳入产品方案；但没有一组使用同一数据集、同一基线和同一口径完成的前后对照结果，所以我不会把方案设计包装成已经取得的准确率提升。\n\n**已经做到的部分**：我把回答质量拆成召回内容是否相关、回答是否忠于上下文、引用能否支持结论，并通过 Bad Case 观察问题来自摄入、召回、排序还是生成。\n\n**如何得到可信数字**：下一步应固定评测问题和标准证据，先记录 Dense Retrieval 基线，再一次只改变一个变量，分别比较召回命中、引用支持和回答忠实度。只有评测集、口径和结果都能复现后，我才会对外说明提升幅度。对我来说，评测数字的价值不是让项目看起来更漂亮，而是帮助产品判断下一轮投入是否有效。",
    details: ["没有公开且可复现的引用准确率提升数字", "当前支持 Dense Retrieval 主链路与引用评测方案", "应使用固定评测集、基线和单变量对照"],
    limitations: "不补充未记录的准确率、提升比例或评测集规模。",
    claimIds: ["C3"], sourceIds: ["S1", "S3"], verification: "externally_verified", relatedProject: "rag-knowledge-base",
    evaluationGoal: "直接回答数字边界，并证明候选人知道如何建立可信、可复现的 RAG 评测。",
    exclusivePoints: ["当前没有公开提升数字", "区分现有主链路与评测结果", "用固定基线和单变量对照验证"],
    mustInclude: ["没有可以公开、复现的引用准确率提升数字", "Dense Retrieval 主链路", "固定评测问题和标准证据"],
    avoidRepeating: ["重新介绍整个 RAG 项目", "虚构准确率或提升比例", "泛泛强调持续优化"],
    responseShape: "shortcoming", targetLength: { min: 330, max: 470 }, preferredStoryIds: ["ST1"],
    followUpQuestions: ["你会如何建立第一版 RAG 评测集？", "引用支持应该如何人工抽检？", "Bad Case 如何转成下一轮优先级？"],
    closingPurpose: "落到用可复现评测支持产品取舍。",
  }),
] as const;

export const faqContent = stableAnswerContent.slice(0, 15).map((item, index) => ({
  ...publicActive,
  id: `F${String(index + 1).padStart(2, "0")}`,
  question: item.question,
  answerId: item.id,
  keywords: item.matchKeywords,
  verification: item.verification,
  relatedProject: item.relatedProject,
  supportsClaimIds: item.requiredClaimIds,
}));
