const updated = "2026-08-13";

const publicActive = {
  visibility: "public",
  status: "active",
  lastUpdated: updated,
} as const;

export const sourceContent = [
  { ...publicActive, id: "S1", title: "最新版个人简历（2026-07-23）", sourceType: "document", url: "https://ask-me-career-agent.vercel.app/resume", public: true, lastChecked: "2026-07-23", verification: "self_attested", supportsClaimIds: ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11", "C13", "C14", "C15", "C16"], supports: "教育、技能、百度与审计经历、项目角色及公开成果陈述。", limitations: "由候选人提供并授权公开；学历、任职、贡献范围与结果仍应通过正式材料或面试核实。" },
  { ...publicActive, id: "S2", title: "Ask Me 产品需求文档 v1.1", sourceType: "document", public: true, lastChecked: updated, verification: "self_attested", projectStatus: "in_progress", relatedProject: "ask-me", supportsClaimIds: ["C12"], supports: "Ask Me 的需求、信息架构、可信回答与评测设计。", limitations: "可以证明产品设计过程，不能证明真实用户效果。" },
  { ...publicActive, id: "S3", title: "RAG Knowledge Base System", sourceType: "repository", url: "https://github.com/ZackZhang-AI/RAG-Knowledge-Base-System", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "in_progress", relatedProject: "rag-knowledge-base", supportsClaimIds: ["C2", "C3", "C18", "C20"], supports: "公开仓库展示医疗 RAG 脱敏 Demo 的代码与文档，可用于核验知识入库、检索问答、来源返回和评测等公开实现。", limitations: "公开仓库是实习业务场景的脱敏重构，不是百川智能生产代码；具体功能状态以代码与运行结果为准，不能据此推断生产规模或真实客户效果。" },
  { ...publicActive, id: "S4", title: "DeepFlow", sourceType: "repository", url: "https://github.com/ZackZhang-AI/DeepFlow", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "in_progress", relatedProject: "deepflow", supportsClaimIds: ["C2", "C4"], supports: "公开仓库及 README 展示多 Agent 研究流程、联网检索、报告生成与可演示 MVP 的产物。", limitations: "不能据此推断生产并发、权限审计、持久化工具状态、真实用户效果或全部功能均由本人独立实现。" },
  { ...publicActive, id: "S5", title: "Thirty-Minute Brain", sourceType: "repository", url: "https://github.com/ZackZhang-AI/thirty-minute-brain", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "completed", relatedProject: "thirty-minute-brain", supportsClaimIds: ["C5"], supports: "公开仓库展示 Tauri、React、Rust 与本地数据设计。", limitations: "实际用户规模与长期使用效果尚无外部数据。" },
  { ...publicActive, id: "S6", title: "Read-Later Regret", sourceType: "repository", url: "https://github.com/ZackZhang-AI/read-later-regret", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "completed", relatedProject: "read-later-regret", supportsClaimIds: ["C5"], supports: "公开 Chrome 扩展仓库展示信息债分类与本地数据管理实现。", limitations: "推荐效果和使用价值主要来自候选人自测。" },
  { ...publicActive, id: "S7", title: "Downloads Butler", sourceType: "repository", url: "https://github.com/ZackZhang-AI/downloads-butler", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "completed", relatedProject: "downloads-butler", supportsClaimIds: ["C5"], supports: "公开桌面工具仓库展示文件分类、移动建议与安全操作设计。", limitations: "仓库存在不等同于大规模用户验证。" },
  { ...publicActive, id: "S8", title: "审计资料智能归档助手", sourceType: "repository", url: "https://github.com/ZackZhang-AI/audit-intern-assistant", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "completed", relatedProject: "audit-intern-assistant", supportsClaimIds: ["C7"], supports: "公开仓库展示审计资料字段抽取、归档与辅助生成方案。", limitations: "不包含真实客户数据，业务提效结果未经过第三方测量。" },
  { ...publicActive, id: "S9", title: "IT 审计日志抽查助手", sourceType: "repository", url: "https://github.com/ZackZhang-AI/it-audit-log-sampling-assistant", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "completed", relatedProject: "it-audit-log-sampling", supportsClaimIds: ["C7"], supports: "公开仓库展示日志规则检查和审计关注点输出。", limitations: "使用公开演示数据，不代表企业生产环境验证。" },
  { ...publicActive, id: "S10", title: "ZackZhang-AI GitHub 主页", sourceType: "repository", url: "https://github.com/ZackZhang-AI", public: true, lastChecked: updated, verification: "externally_verified", supportsClaimIds: ["C3", "C4", "C5", "C7", "C8"], supports: "公开账号与项目索引。", limitations: "只能验证公开活动与仓库，不能验证非公开工作经历。" },
  { ...publicActive, id: "S11", title: "百度 AI 产品经理实习公开事实摘要", sourceType: "self_report", public: true, lastChecked: "2026-07-27", verification: "self_attested", projectStatus: "in_progress", relatedProject: "baidu-ai-coding-evaluation", supportsClaimIds: ["C13", "C14", "C15", "C16"], supports: "模型评测与 Bad Case 归因、AI Coding 七维指标与 Gate、Evaluator Agent MVP、单样例结果及 Benchmark 调研。", limitations: "仅使用候选人明确确认的公开口径；团队分工、工程参与比例、成本效率和人机一致性仍需面试核实。" },
  { ...publicActive, id: "S12", title: "百川智能医疗 RAG 实习公开事实摘要", sourceType: "self_report", public: true, lastChecked: updated, verification: "self_attested", projectStatus: "in_progress", relatedProject: "rag-knowledge-base", supportsClaimIds: ["C17", "C18", "C19", "C20", "C21"], supports: "百川智能实习顺序、医疗 RAG 项目背景、候选人职责、公开 Demo 与内部系统的关系、当前实现和未完成边界。", limitations: "仅使用候选人本轮明确确认及面试题库中的可公开口径；不公开客户身份、内部模型、生产代码或敏感数据，不把公司案例、规划功能和未经充分验证的指标归为个人成果。" },
] as const;

export const claimContent = [
  { ...publicActive, id: "C1", statement: "张倬玮就读于东北大学应用统计学专业，预计 2027 年毕业。", claimType: "background", evidenceBasis: "user_statement", candidateContribution: "本人提供并授权公开。", aiAssistance: "无。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1"], limitations: "需以学籍或正式简历核实。" },
  { ...publicActive, id: "C2", statement: "具备 SQL、Python、FastAPI、Milvus、RAGAS 与 AI 产品评测相关实践。", claimType: "skill", evidenceBasis: "user_statement", candidateContribution: "本人提供技能陈述，公开项目佐证部分技术实践。", aiAssistance: "AI 工具参与开发与资料整理。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1", "S3", "S4"], limitations: "熟练程度需通过面试或现场任务核实。" },
  { ...publicActive, id: "C3", statement: "公开仓库展示了医疗 RAG 脱敏 Demo 的知识入库、稠密向量召回、Rerank、来源片段返回、短期记忆、多助手基础配置和自动评测链路。", claimType: "project", evidenceBasis: "source_view", relatedProject: "rag-knowledge-base", candidateContribution: "候选人参与需求定义、方案取舍、端到端功能设计、检索与记忆规则、评测验收和公开重构推进。", aiAssistance: "AI 编程工具辅助公开 Demo 的实现、调试与文档整理。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S3", "S12"], limitations: "公开 Demo 不是公司生产代码；BM25 混合检索、长期记忆、完整 Agent、持久化版本对比、专门 Bad Case 平台和生产级 RBAC 尚未完整落地，生产规模与真实客户效果未公开。" },
  { ...publicActive, id: "C4", statement: "公开仓库展示了 DeepFlow 多 Agent 研究流程和可演示 MVP 产物。", claimType: "project", evidenceBasis: "source_view", relatedProject: "deepflow", candidateContribution: "候选人材料称其负责 Agent 分工、研究流程、观测字段和成果物链路设计。", aiAssistance: "模型承担研究生成，AI 编程工具辅助工程实现。", verification: "externally_verified", supportsClaimIds: [], sourceIds: ["S1", "S4"], limitations: "真实用户、生产并发、权限审计、工具状态持久化、时延和成本尚未形成独立验证。" },
  { ...publicActive, id: "C5", statement: "构建了本地优先或浏览器效率工具，覆盖上下文恢复、信息债和文件整理。", claimType: "project", evidenceBasis: "source_view", relatedProject: "local-first-tools", candidateContribution: "负责产品定义、安全规则、数据模型与原型实现。", aiAssistance: "AI 编程工具参与开发。", verification: "externally_verified", supportsClaimIds: [], sourceIds: ["S1", "S5", "S6", "S7"], limitations: "用户规模、留存和长期价值数据尚未公开。" },
  { ...publicActive, id: "C6", statement: "具备财务审计、IT 审计和校园大使经历。", claimType: "experience", evidenceBasis: "user_statement", candidateContribution: "本人提供经历与工作内容。", aiAssistance: "无。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1"], limitations: "企业任职与工作结果需正式材料或面试核实。" },
  { ...publicActive, id: "C7", statement: "将审计业务痛点转化为公开的资料归档与日志抽查工具。", claimType: "project", evidenceBasis: "source_view", relatedProject: "audit-tools", candidateContribution: "负责场景抽象、规则设计、原型实现与测试。", aiAssistance: "OCR、LLM 与 AI 编程工具参与实现。", verification: "externally_verified", supportsClaimIds: [], sourceIds: ["S1", "S8", "S9"], limitations: "未使用或公开企业客户敏感数据，提效结果无第三方测量。" },
  { ...publicActive, id: "C8", statement: "当前公开证据不足以证明大规模线上 AI 产品商业化、真实用户增长和长期团队管理经验。", claimType: "boundary", evidenceBasis: "inference", candidateContribution: "候选人确认当前公开能力边界。", aiAssistance: "无。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1", "S10"], limitations: "能力边界会随实习和项目进展更新。" },
  { ...publicActive, id: "C9", statement: "2026 年 1 月至 4 月参与德勤 IT 审计实习，工作涉及 IPE 与日志核查。", claimType: "experience", evidenceBasis: "user_statement", candidateContribution: "本人提供任职时间与职责描述。", aiAssistance: "无。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1"], limitations: "不公开客户、底稿或企业机密，任职信息需正式材料核实。" },
  { ...publicActive, id: "C10", statement: "2025 年 1 月至 3 月参与容诚财务审计实习，工作涉及底稿、函证与盘点。", claimType: "experience", evidenceBasis: "user_statement", candidateContribution: "本人提供任职时间与职责描述。", aiAssistance: "无。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1"], limitations: "不公开客户、底稿或企业机密，任职信息需正式材料核实。" },
  { ...publicActive, id: "C11", statement: "曾担任德勤校园大使，参与流程主持与校招推广。", claimType: "experience", evidenceBasis: "user_statement", candidateContribution: "本人提供经历与职责描述。", aiAssistance: "无。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1"], limitations: "活动范围与效果需面试核实。" },
  { ...publicActive, id: "C12", statement: "Ask Me 采用 Claim-Source 证据模型与受约束回答设计服务 AI 产品招聘场景。", claimType: "project", evidenceBasis: "source_view", relatedProject: "ask-me", candidateContribution: "负责需求、PRD、信息架构、证据模型、安全边界和工程验收。", aiAssistance: "AI 编程 Agent 参与资料整理、代码生成和测试。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S2"], limitations: "项目仍在更新，暂无招聘转化或大规模使用数据。" },
  { ...publicActive, id: "C13", statement: "在百川智能医疗 RAG 实习之后参与百度 AI 产品经理实习，工作主线包括模型效果评测、Bad Case 归因、策略建议与行业研究。", claimType: "experience", evidenceBasis: "user_statement", relatedProject: "baidu-ai-coding-evaluation", candidateContribution: "参与版本测试、结果记录、问题分类与评测材料沉淀。", aiAssistance: "模型与自动化工具是评测对象和执行工具，不替代候选人的产品判断。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1", "S11", "S12"], limitations: "本轮只确认经历先后顺序，不据此推断百川或百度的精确起止日期；不公开具体业务线、模型版本、内部数据和保密材料。" },
  { ...publicActive, id: "C14", statement: "参与 AI Coding Web 开发端到端评测方案，覆盖七维指标、硬门槛与 11 阶段 Evaluator Agent MVP 链路。", claimType: "project", evidenceBasis: "user_statement", relatedProject: "baidu-ai-coding-evaluation", candidateContribution: "参与 Benchmark 调研、指标与 Gate 设计、MVP 实现验证、样例测试及交付材料整理。", aiAssistance: "确定性工具负责运行与证据采集，LLM Judge 负责开放维度，人工负责校准和争议判断。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1", "S11"], limitations: "当前是单样例 MVP，不表述为独立搭建生产平台或完成大规模模型比较。" },
  { ...publicActive, id: "C15", statement: "Dashboard 单样例跑通 Evaluator Agent 全链路，Final Score 90.9、Auto Score 99.2、Judge Score 76.0，20 项工程测试通过并生成三视口截图与结构化报告。", claimType: "project", evidenceBasis: "user_statement", relatedProject: "baidu-ai-coding-evaluation", candidateContribution: "参与样例运行、结果复核和交付材料整理。", aiAssistance: "自动化检查和 LLM Judge 共同生成分项结果，最终结论保留人工校准边界。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1", "S11"], limitations: "这些数字只代表当前规则下的单次样例结果；不能推出模型效果、用户满意度或业务效率提升。" },
  { ...publicActive, id: "C16", statement: "调研 HumanEval、SWE-bench、Web-Bench、WebDevJudge 等 13 项 Coding Benchmark，并按任务形态与能力对象分类。", claimType: "skill", evidenceBasis: "user_statement", relatedProject: "baidu-ai-coding-evaluation", candidateContribution: "整理 Benchmark 的任务、指标、环境与可迁移方法，为业务评测方案提供参考。", aiAssistance: "AI 可辅助资料整理，但分类、取舍和业务映射由候选人完成。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1", "S11"], limitations: "Benchmark 仅作为方法参考，不等同于业务评测结果；具体阅读深度以面试说明为准。" },
  { ...publicActive, id: "C17", statement: "在德勤 IT 审计之后、百度实习之前，参与百川智能 AI 产品部门的医疗 RAG 实习。", claimType: "experience", evidenceBasis: "user_statement", relatedProject: "rag-knowledge-base", candidateContribution: "本人确认任职顺序和实习方向。", aiAssistance: "无。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S12"], limitations: "未确认精确起止日期、汇报关系和任职证明信息，不进行推断。" },
  { ...publicActive, id: "C18", statement: "RAG Knowledge Base System 是百川智能医疗 RAG 实习的主要产出；公开仓库是对实习业务场景的脱敏重构，不是公司生产代码。", claimType: "project", evidenceBasis: "user_statement", relatedProject: "rag-knowledge-base", candidateContribution: "参与将医疗私有文档的检索、问答、来源返回和评测需求转成产品链路，并在公开环境完成脱敏重构。", aiAssistance: "公开 Demo 使用外部模型与 AI 编程工具辅助实现，不代表公司内部模型或代码。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S3", "S12"], limitations: "不能把公开 Demo 的技术栈等同于百川内部实现，也不披露内部模型、客户数据或生产代码。" },
  { ...publicActive, id: "C19", statement: "在医疗 RAG 项目中，候选人主要参与需求与 MVP 梳理、知识入库和检索问答等功能设计，以及 QA 数据集和四维 LLM-as-Judge 评测闭环。", claimType: "experience", evidenceBasis: "user_statement", relatedProject: "rag-knowledge-base", candidateContribution: "围绕知识库管理、幻觉风险、答案溯源和评测验收，与算法和研发协作定义流程、配置边界与验收标准。", aiAssistance: "模型用于问答和评测，AI 编程工具用于公开 Demo 重构；候选人负责产品判断与边界。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S12"], limitations: "不声称独立实现检索算法、底层模型或全部工程代码；PRD、原型等具体交付物只在能够现场出示时说明。" },
  { ...publicActive, id: "C20", statement: "当前公开项目已跑通知识入库、稠密向量召回与 Rerank、来源片段返回、Redis 短期记忆、多助手基础配置和四维自动评测。", claimType: "project", evidenceBasis: "user_statement", relatedProject: "rag-knowledge-base", candidateContribution: "参与功能设计、参数与异常边界、评测流程和结果验收。", aiAssistance: "公开 Demo 使用 Qwen/DashScope 等外部能力完成脱敏重构。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S3", "S12"], limitations: "BM25 混合检索、长期记忆、完整 Agent、持久化版本对比、专门 Bad Case 平台和生产级 RBAC 尚未完整落地。" },
  { ...publicActive, id: "C21", statement: "医疗 RAG 当前四维自动评测为 Faithfulness、Relevancy、Context Precision 和 Accuracy，用于低成本回归和发现趋势。", claimType: "skill", evidenceBasis: "user_statement", relatedProject: "rag-knowledge-base", candidateContribution: "参与 QA 数据生成或导入、人工编辑、批量运行、分维打分和报告输出的产品闭环。", aiAssistance: "LLM-as-Judge 输出分数和理由，不能替代人工校准。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S12"], limitations: "四维不是绝对真值；需固定 Judge、Prompt、温度和数据集版本并结合人工审核，不把初步 95% 或 85% 表述为线上准确率。" },
] as const;
