const updated = "2026-07-15";

const publicActive = {
  visibility: "public",
  status: "active",
  lastUpdated: updated,
} as const;

export const sourceContent = [
  { ...publicActive, id: "S1", title: "个人能力汇总（候选人维护）", sourceType: "self_report", public: true, lastChecked: updated, verification: "self_attested", supportsClaimIds: ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11"], supports: "教育、技能、经历、项目角色与个人贡献陈述。", limitations: "由候选人维护；学历、任职、贡献范围与结果仍应通过正式材料或面试核实。" },
  { ...publicActive, id: "S2", title: "Ask Me 产品需求文档 v1.1", sourceType: "document", public: true, lastChecked: updated, verification: "self_attested", projectStatus: "in_progress", relatedProject: "ask-me", supportsClaimIds: ["C12"], supports: "Ask Me 的需求、信息架构、可信回答与评测设计。", limitations: "可以证明产品设计过程，不能证明真实用户效果。" },
  { ...publicActive, id: "S3", title: "RAG Knowledge Base System", sourceType: "repository", url: "https://github.com/ZackZhang-AI/RAG-Knowledge-Base-System", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "completed", relatedProject: "rag-knowledge-base", supportsClaimIds: ["C2", "C3"], supports: "公开仓库及 README 展示文档解析、混合检索、引用溯源和评测设计。", limitations: "仓库可验证代码与设计存在，本人独立贡献比例与生产规模仍需核实。" },
  { ...publicActive, id: "S4", title: "DeepFlow", sourceType: "repository", url: "https://github.com/ZackZhang-AI/DeepFlow", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "completed", relatedProject: "deepflow", supportsClaimIds: ["C2", "C4"], supports: "公开仓库及 README 展示多 Agent 研究流程、联网检索与报告生成。", limitations: "不能据此推断生产规模、长期稳定性或全部功能均由本人独立实现。" },
  { ...publicActive, id: "S5", title: "Thirty-Minute Brain", sourceType: "repository", url: "https://github.com/ZackZhang-AI/thirty-minute-brain", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "completed", relatedProject: "thirty-minute-brain", supportsClaimIds: ["C5"], supports: "公开仓库展示 Tauri、React、Rust 与本地数据设计。", limitations: "实际用户规模与长期使用效果尚无外部数据。" },
  { ...publicActive, id: "S6", title: "Read-Later Regret", sourceType: "repository", url: "https://github.com/ZackZhang-AI/read-later-regret", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "completed", relatedProject: "read-later-regret", supportsClaimIds: ["C5"], supports: "公开 Chrome 扩展仓库展示信息债分类与本地数据管理实现。", limitations: "推荐效果和使用价值主要来自候选人自测。" },
  { ...publicActive, id: "S7", title: "Downloads Butler", sourceType: "repository", url: "https://github.com/ZackZhang-AI/downloads-butler", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "completed", relatedProject: "downloads-butler", supportsClaimIds: ["C5"], supports: "公开桌面工具仓库展示文件分类、移动建议与安全操作设计。", limitations: "仓库存在不等同于大规模用户验证。" },
  { ...publicActive, id: "S8", title: "审计资料智能归档助手", sourceType: "repository", url: "https://github.com/ZackZhang-AI/audit-intern-assistant", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "completed", relatedProject: "audit-intern-assistant", supportsClaimIds: ["C7"], supports: "公开仓库展示审计资料字段抽取、归档与辅助生成方案。", limitations: "不包含真实客户数据，业务提效结果未经过第三方测量。" },
  { ...publicActive, id: "S9", title: "IT 审计日志抽查助手", sourceType: "repository", url: "https://github.com/ZackZhang-AI/it-audit-log-sampling-assistant", public: true, lastChecked: updated, verification: "externally_verified", projectStatus: "completed", relatedProject: "it-audit-log-sampling", supportsClaimIds: ["C7"], supports: "公开仓库展示日志规则检查和审计关注点输出。", limitations: "使用公开演示数据，不代表企业生产环境验证。" },
  { ...publicActive, id: "S10", title: "ZackZhang-AI GitHub 主页", sourceType: "repository", url: "https://github.com/ZackZhang-AI", public: true, lastChecked: updated, verification: "externally_verified", supportsClaimIds: ["C3", "C4", "C5", "C7", "C8"], supports: "公开账号与项目索引。", limitations: "只能验证公开活动与仓库，不能验证非公开工作经历。" },
] as const;

export const claimContent = [
  { ...publicActive, id: "C1", statement: "张倬玮就读于东北大学应用统计学专业，预计 2027 年毕业。", claimType: "background", candidateContribution: "本人提供并授权公开。", aiAssistance: "无。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1"], limitations: "需以学籍或正式简历核实。" },
  { ...publicActive, id: "C2", statement: "具备 SQL、Python、FastAPI、Milvus、RAGAS 与 AI 产品评测相关实践。", claimType: "skill", candidateContribution: "本人提供技能陈述，公开项目佐证部分技术实践。", aiAssistance: "AI 工具参与开发与资料整理。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1", "S3", "S4"], limitations: "熟练程度需通过面试或现场任务核实。" },
  { ...publicActive, id: "C3", statement: "公开实现了具备文档解析、混合检索、引用溯源和自动评测设计的 RAG 系统。", claimType: "project", relatedProject: "rag-knowledge-base", candidateContribution: "主导产品定位、检索策略、评测设计与全栈落地。", aiAssistance: "AI 编程工具辅助实现、调试与文档整理。", verification: "externally_verified", supportsClaimIds: [], sourceIds: ["S1", "S3"], limitations: "长期记忆仍是规划项；生产规模和独立贡献比例需进一步核实。" },
  { ...publicActive, id: "C4", statement: "公开实现了多 Agent 深度研究工作台 DeepFlow。", claimType: "project", relatedProject: "deepflow", candidateContribution: "设计 Agent 分工、研究流程、观测字段和成果物链路。", aiAssistance: "模型承担研究生成，AI 编程工具辅助工程实现。", verification: "externally_verified", supportsClaimIds: [], sourceIds: ["S1", "S4"], limitations: "真实引用数量、时延和成本随任务变化。" },
  { ...publicActive, id: "C5", statement: "构建了本地优先或浏览器效率工具，覆盖上下文恢复、信息债和文件整理。", claimType: "project", relatedProject: "local-first-tools", candidateContribution: "负责产品定义、安全规则、数据模型与原型实现。", aiAssistance: "AI 编程工具参与开发。", verification: "externally_verified", supportsClaimIds: [], sourceIds: ["S1", "S5", "S6", "S7"], limitations: "用户规模、留存和长期价值数据尚未公开。" },
  { ...publicActive, id: "C6", statement: "具备财务审计、IT 审计和校园大使经历。", claimType: "experience", candidateContribution: "本人提供经历与工作内容。", aiAssistance: "无。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1"], limitations: "企业任职与工作结果需正式材料或面试核实。" },
  { ...publicActive, id: "C7", statement: "将审计业务痛点转化为公开的资料归档与日志抽查工具。", claimType: "project", relatedProject: "audit-tools", candidateContribution: "负责场景抽象、规则设计、原型实现与测试。", aiAssistance: "OCR、LLM 与 AI 编程工具参与实现。", verification: "externally_verified", supportsClaimIds: [], sourceIds: ["S1", "S8", "S9"], limitations: "未使用或公开企业客户敏感数据，提效结果无第三方测量。" },
  { ...publicActive, id: "C8", statement: "当前公开证据不足以证明大规模线上 AI 产品商业化、真实用户增长和长期团队管理经验。", claimType: "boundary", candidateContribution: "候选人确认当前公开能力边界。", aiAssistance: "无。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1", "S10"], limitations: "能力边界会随实习和项目进展更新。" },
  { ...publicActive, id: "C9", statement: "2026 年 1 月至 4 月参与德勤 IT 审计实习，工作涉及 IPE 与日志核查。", claimType: "experience", candidateContribution: "本人提供任职时间与职责描述。", aiAssistance: "无。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1"], limitations: "不公开客户、底稿或企业机密，任职信息需正式材料核实。" },
  { ...publicActive, id: "C10", statement: "2025 年 1 月至 3 月参与容诚财务审计实习，工作涉及底稿、函证与盘点。", claimType: "experience", candidateContribution: "本人提供任职时间与职责描述。", aiAssistance: "无。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1"], limitations: "不公开客户、底稿或企业机密，任职信息需正式材料核实。" },
  { ...publicActive, id: "C11", statement: "曾担任德勤校园大使，参与流程主持与校招推广。", claimType: "experience", candidateContribution: "本人提供经历与职责描述。", aiAssistance: "无。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S1"], limitations: "活动范围与效果需面试核实。" },
  { ...publicActive, id: "C12", statement: "Ask Me 采用 Claim-Source 证据模型与受约束回答设计服务 AI 产品招聘场景。", claimType: "project", relatedProject: "ask-me", candidateContribution: "负责需求、PRD、信息架构、证据模型、安全边界和工程验收。", aiAssistance: "AI 编程 Agent 参与资料整理、代码生成和测试。", verification: "self_attested", supportsClaimIds: [], sourceIds: ["S2"], limitations: "项目仍在更新，暂无招聘转化或大规模使用数据。" },
] as const;
