const confirmed = {
  visibility: "public",
  status: "active",
  verification: "self_attested",
  lastUpdated: "2026-07-17",
} as const;

export const starStoryContent = [
  {
    ...confirmed,
    id: "ST1",
    title: "RAG 项目从功能堆叠回到质量基线",
    relatedProject: "rag-knowledge-base",
    competency: "产品取舍与评测设计",
    interviewUse: ["项目挑战", "失败复盘", "RAG 评测", "代表项目"],
    situation: "RAG 项目早期同时存在混合检索、Rerank、引用和自动评测等多个值得推进的方向，功能越多却越难定位 Bad Case 来自哪个环节。",
    task: "我需要重新建立清晰的验证顺序，让每次迭代都能回答一个明确问题。",
    action: "我把方案收敛到文档摄入、Dense Retrieval 和回答生成主链路，先建立可重复检查的基线，再把高级检索、引用和评测拆成独立实验，用召回相关性、上下文忠实度和失败样本判断下一步。",
    result: "项目从展示功能数量转向验证检索与回答质量，我也形成了先建立基线、再控制变量推进 AI 产品迭代的方法。",
    limitations: "这是产品方案调整，不代表已获得企业生产规模或真实用户效果数据。",
    claimIds: ["C3"], supportsClaimIds: ["C3"], sourceIds: ["S1", "S3"],
  },
  {
    ...confirmed,
    id: "ST2",
    title: "DeepFlow 在 Agent 自主性与可控性之间取舍",
    relatedProject: "deepflow",
    competency: "Agent 工作流与风险控制",
    interviewUse: ["DeepFlow 挑战", "Agent 产品设计", "方案取舍"],
    situation: "复杂研究任务如果一次性交给模型，虽然看起来自动化程度高，但计划可能跑偏，过程和证据也很难追踪。",
    task: "我需要在 Agent 自主执行和用户控制之间找到适合研究场景的平衡。",
    action: "我把任务拆成计划、检索、分析和报告等角色与阶段，在研究计划等高成本节点加入人工确认，并设计过程事件和引用，让使用者能够判断任务是否继续。",
    result: "DeepFlow 形成了从任务澄清到报告输出的可演示 MVP，也明确了哪些环节适合自动化、哪些环节必须保留人的判断。",
    limitations: "真实用户规模、生产并发、权限审计、时延和成本尚未获得独立验证。",
    claimIds: ["C4"], supportsClaimIds: ["C4"], sourceIds: ["S1", "S4"],
  },
  {
    ...confirmed,
    id: "ST3",
    title: "用质量门禁验收 AI 编程结果",
    relatedProject: "ask-me",
    competency: "AI 协作与工程验收",
    interviewUse: ["AI 写了多少", "如何验收", "AI 生成失败"],
    situation: "AI 编程工具可以很快生成代码，但代码能够运行并不代表它符合招聘场景、事实约束和已有接口。",
    task: "我需要提高实现速度，同时保证产品判断和最终质量不被生成速度取代。",
    action: "我先明确需求、接口和验收标准，再让 AI 协助实现；关键改动必须经过自动测试、Lint、Build、事实门禁和真实问答流程检查，不符合目标时回到问题定义重新拆解。",
    result: "Ask Me 保留了快速迭代速度，也建立了模型生成、受约束重写和稳定回退的质量链路，最终责任始终由我承担。",
    limitations: "不同任务的 AI 参与程度不同，不虚构统一的代码贡献比例。",
    claimIds: ["C12"], supportsClaimIds: ["C12"], sourceIds: ["S2"],
  },
  {
    ...confirmed,
    id: "ST4",
    title: "把审计现场问题转成公开产品原型",
    relatedProject: "audit-tools",
    competency: "业务抽象与机会识别",
    interviewUse: ["审计如何帮助产品", "业务问题转产品", "企业场景"],
    situation: "审计资料整理和日志核查包含大量字段、规则和重复操作，但真实客户资料不能直接用于公开产品开发。",
    task: "我希望保留业务问题的关键结构，同时避免接触或泄露真实企业数据。",
    action: "我把场景拆成字段提取、归档建议、异常规则和人工复核等通用环节，使用公开演示数据完成资料归档助手与日志抽查助手原型。",
    result: "我验证了从一线流程中识别产品机会、抽象通用规则并形成公开工具的路径。",
    limitations: "项目未使用真实客户数据，规则覆盖度和实际提效没有第三方测量。",
    claimIds: ["C7"], supportsClaimIds: ["C7"], sourceIds: ["S1", "S8", "S9"],
  },
  {
    ...confirmed,
    id: "ST5",
    title: "本地优先工具把隐私写进产品流程",
    relatedProject: "thirty-minute-brain",
    competency: "隐私默认设计",
    interviewUse: ["隐私", "本地优先", "产品边界"],
    situation: "上下文恢复工具需要处理剪贴板、文件和近期工作记录，这些数据有帮助，但也天然敏感。",
    task: "我需要验证工作上下文检索价值，同时避免为了便利把所有数据上传到云端。",
    action: "我采用本地持久化和本地搜索，把来源控制、敏感内容过滤、去重、过期清理和用户确认纳入数据摄取流程。",
    result: "我完成了可公开检查的桌面原型，也形成了先确定数据边界、再讨论智能能力的产品习惯。",
    limitations: "目前主要是原型和个人使用场景，尚无长期使用或外部用户验证数据。",
    claimIds: ["C5"], supportsClaimIds: ["C5"], sourceIds: ["S1", "S5"],
  },
  {
    ...confirmed,
    id: "ST6",
    title: "IT 审计中的证据核查与口径确认",
    competency: "严谨执行与风险意识",
    interviewUse: ["德勤实习", "企业业务理解", "可靠性"],
    situation: "IT 审计需要围绕系统输出和日志形成可以复核的记录，资料不一致时不能凭经验直接下结论。",
    task: "我参与 IPE 与日志核查，需要按审计程序完成资料核对并处理不确定项。",
    action: "我检查资料与记录的一致性，在不确定处及时确认口径，并整理能够被后续复核的工作记录。",
    result: "我完成了职责范围内的核查，也更具体地理解了企业系统中的数据来源、流程控制和证据链。",
    limitations: "仅公开职责和能力总结，不披露客户、系统明细、底稿或其他受限信息。",
    claimIds: ["C9"], supportsClaimIds: ["C9"], sourceIds: ["S1"],
  },
  {
    ...confirmed,
    id: "ST7",
    title: "校园招聘流程中的现场协调",
    competency: "沟通协作与现场推进",
    interviewUse: ["团队协作", "沟通协调", "非技术经历"],
    situation: "校园招聘活动需要在固定时间内协调候选人、流程和现场信息，任何遗漏都会直接影响参与者体验。",
    task: "我作为德勤校园大使参与流程主持与校招推广，需要确保信息传递和现场衔接顺畅。",
    action: "我提前梳理流程和关键联系人，现场根据进度同步信息，并在出现变化时优先保证候选人与面试安排顺利衔接。",
    result: "我完成了职责范围内的流程支持，也积累了面对多方信息和现场变化时保持节奏的经验。",
    limitations: "不公开未确认的活动数字或效果，活动范围以正式材料和面试说明为准。",
    claimIds: ["C11"], supportsClaimIds: ["C11"], sourceIds: ["S1"],
  },
  {
    ...confirmed,
    id: "ST8",
    title: "Ask Me 从证据展示转向面试转化",
    relatedProject: "ask-me",
    competency: "用户反馈与产品方向修正",
    interviewUse: ["失败复盘", "Ask Me 项目", "产品迭代"],
    situation: "Ask Me 早期版本过度强调 Claim、Source 和限制说明，事实更安全，但回答像审计报告，不像真实面试，也会重复同一套优势。",
    task: "我需要在事实安全和面试说服力之间重新建立产品目标。",
    action: "我把证据继续保留在系统元数据中，正文改为第一人称面试表达；重新设计候选人叙事、问题独立任务、自适应长度和多轮去重，并用模拟面试与真人测试指标评价转化。",
    result: "产品方向从“证明每句话”调整为“让面试官更快形成清晰、可信、愿意追问的候选人判断”，同时继续保留内部事实门禁。",
    limitations: "产品方向调整已经发生，但最终招聘转化仍需真人软测试验证。",
    claimIds: ["C12"], supportsClaimIds: ["C12"], sourceIds: ["S2"],
  },
] as const;
