const confirmed = {
  visibility: "public",
  status: "active",
  verification: "self_attested",
  lastUpdated: "2026-08-23",
} as const;

export const starStoryContent = [
  {
    ...confirmed,
    id: "ST1",
    title: "用评测定位医疗 RAG 的多跳短板",
    relatedProject: "rag-knowledge-base",
    competency: "产品取舍与评测设计",
    interviewUse: ["项目挑战", "失败复盘", "RAG 评测", "代表项目"],
    situation: "医疗 RAG 三轮评测中，一轮单跳题均分 9.71，而多跳题均分只有 4.38，说明系统能回答直接问题，但跨段证据组合可能是高风险弱项。",
    task: "我需要避免把低分简单归因给模型，并把风险拆成团队可以逐项验证的问题。",
    action: "我先检查 Judge、问题与参考答案是否合理，再沿文档摄入、Dense 召回、Rerank、问题分解、子问题证据和最终生成逐层排查；同时把代表性多跳样例固化到回归集，后续用固定问题和单变量对照验证。",
    result: "这次分析没有被包装成已经完成的效果提升，但明确暴露了多跳问答的优先级，也形成了从指标信号到 Bad Case、根因假设和回归任务的产品闭环。",
    limitations: "多跳样本仅 2 个，是风险信号而不是稳定结论；不能声称某项优化已使指标提升。",
    claimIds: ["C3", "C20", "C21", "C26", "C27"], supportsClaimIds: ["C3", "C20", "C21", "C26", "C27"], sourceIds: ["S3", "S12"],
  },
  {
    ...confirmed,
    id: "ST2",
    title: "DeepFlow 在 Agent 自主性与可控性之间取舍",
    relatedProject: "deepflow",
    competency: "Agent 工作流与风险控制",
    interviewUse: ["DeepFlow 挑战", "Agent 产品设计", "方案取舍"],
    situation: "复杂研究任务如果一次性交给模型，虽然看起来自动化程度高，但需求、计划、检索、分析和成果之间容易脱节，过程与证据也很难追踪。",
    task: "我需要在 Agent 自主执行和用户控制之间找到适合研究场景的平衡。",
    action: "我把任务拆成需求澄清、计划确认、资料检索、分析生成和成果导出，用多 Agent 分工与私域 RAG 组织流程，在高成本节点加入人工确认，并通过 Hybrid 检索、引用溯源、结构化输出和 Agent Trace 保留过程证据。",
    result: "DeepFlow 形成了从需求澄清到成果导出的可演示闭环，也明确了哪些环节适合自动化、哪些环节必须保留人的判断。",
    limitations: "真实用户规模、生产并发、权限审计、时延和成本尚未获得独立验证。",
    claimIds: ["C4"], supportsClaimIds: ["C4"], sourceIds: ["S1", "S4"],
  },
  {
    ...confirmed,
    id: "ST3",
    title: "用质量门禁验收 AI 编程结果",
    relatedProject: "ask-me",
    competency: "AI 协作与工程验收",
    interviewUse: ["AI 写了多少", "如何验收", "AI 生成失败"],
    situation: "AI 编程工具可以很快生成代码，但代码能够运行并不代表数字分身符合招聘场景、事实约束和已有接口。",
    task: "我需要提高实现速度，同时保证产品判断和最终质量不被生成速度取代。",
    action: "我先明确需求、接口和验收标准，再让 AI 协助实现；关键改动必须经过自动测试、Lint、Build、事实门禁和真实问答流程检查，不符合目标时回到问题定义重新拆解。",
    result: "Ask Me 保留了快速迭代速度，也建立了模型生成、受约束重写和稳定回退的质量链路；最新版简历记录 163 项自动化测试和 48 个 AI 面试用例，最终责任始终由我承担。",
    limitations: "测试数量代表回归覆盖，不代表真人招聘转化；不同任务的 AI 参与程度不同，不虚构统一的代码贡献比例。",
    claimIds: ["C12", "C28"], supportsClaimIds: ["C12", "C28"], sourceIds: ["S1", "S2"],
  },
  {
    ...confirmed,
    id: "ST4",
    title: "把审计现场问题转成公开产品原型",
    relatedProject: "audit-tools",
    competency: "业务抽象与机会识别",
    interviewUse: ["审计如何帮助产品", "业务问题转产品", "企业场景"],
    situation: "德勤 IT 审计中，我参与操作系统与 APP 层面 30 余份底稿编制和复核，资料整理、日志核查与数据脱敏包含大量字段、规则和重复操作，但真实客户资料不能用于公开产品开发。",
    task: "我希望保留业务问题的关键结构，同时避免接触或泄露真实企业数据。",
    action: "我把场景拆成字段提取、归档建议、异常规则和人工复核等通用环节，使用公开演示数据完成资料归档助手与日志抽查助手原型。",
    result: "我验证了从一线流程中识别产品机会、抽象通用规则并形成公开工具的路径；简历中记录的 Prompt 脱敏流程提效也让我更具体地看到 AI 在明确流程中的价值。",
    limitations: "项目未使用真实客户数据；耗时降低 80%、效率提升 400% 是候选人流程口径，不是第三方 A/B。",
    claimIds: ["C7", "C9"], supportsClaimIds: ["C7", "C9"], sourceIds: ["S1", "S8", "S9"],
  },
  {
    ...confirmed,
    id: "ST5",
    title: "本地优先工具把隐私写进产品流程",
    relatedProject: "thirty-minute-brain",
    competency: "隐私默认设计",
    interviewUse: ["隐私", "本地优先", "产品边界"],
    situation: "上下文恢复工具需要处理剪贴板、文件和近期工作记录，这些数据有帮助，但也天然敏感。",
    task: "我需要验证工作上下文检索价值，同时避免为了便利把所有数据上传到云端。",
    action: "我采用本地持久化和本地搜索，把来源控制、敏感内容过滤、去重、过期清理和用户确认纳入数据摄取流程。",
    result: "我完成了可公开检查的桌面原型，也形成了先确定数据边界、再讨论智能能力的产品习惯。",
    limitations: "目前主要是原型和个人使用场景，尚无长期使用或外部用户验证数据。",
    claimIds: ["C5"], supportsClaimIds: ["C5"], sourceIds: ["S1", "S5"],
  },
  {
    ...confirmed,
    id: "ST6",
    title: "IT 审计中的证据核查与口径确认",
    competency: "严谨执行与风险意识",
    interviewUse: ["德勤实习", "企业业务理解", "可靠性"],
    situation: "IT 审计需要围绕系统输出和日志形成可以复核的记录，资料不一致时不能凭经验直接下结论。",
    task: "我参与 IPE 与日志核查，需要按审计程序完成资料核对并处理不确定项。",
    action: "我检查资料与记录的一致性，在不确定处及时确认口径，并整理能够被后续复核的工作记录。",
    result: "我完成了职责范围内的核查，也更具体地理解了企业系统中的数据来源、流程控制和证据链。",
    limitations: "仅公开职责和能力总结，不披露客户、系统明细、底稿或其他受限信息。",
    claimIds: ["C9"], supportsClaimIds: ["C9"], sourceIds: ["S1"],
  },
  {
    ...confirmed,
    id: "ST7",
    title: "校园招聘流程中的现场协调",
    competency: "沟通协作与现场推进",
    interviewUse: ["团队协作", "沟通协调", "非技术经历"],
    situation: "校园招聘活动需要在固定时间内协调候选人、流程和现场信息，任何遗漏都会直接影响参与者体验。",
    task: "我作为德勤校园大使参与流程主持与校招推广，需要确保信息传递和现场衔接顺畅。",
    action: "我提前梳理流程和关键联系人，现场根据进度同步信息，并在出现变化时优先保证候选人与面试安排顺利衔接。",
    result: "我完成了职责范围内的流程支持，也积累了面对多方信息和现场变化时保持节奏的经验。",
    limitations: "不公开未确认的活动数字或效果，活动范围以正式材料和面试说明为准。",
    claimIds: ["C11"], supportsClaimIds: ["C11"], sourceIds: ["S1"],
  },
  {
    ...confirmed,
    id: "ST8",
    title: "Ask Me 从证据展示转向面试转化",
    relatedProject: "ask-me",
    competency: "用户反馈与产品方向修正",
    interviewUse: ["失败复盘", "Ask Me 项目", "产品迭代"],
    situation: "Ask Me 早期版本过度强调 Claim、Source 和限制说明，事实更安全，但回答像审计报告，不像真实面试，也会重复同一套优势。",
    task: "我需要在事实安全和面试说服力之间重新建立产品目标。",
    action: "我把证据继续保留在系统元数据中，正文改为第一人称面试表达；重新设计候选人叙事、问题独立任务、自适应长度和多轮去重，并用模拟面试与真人测试指标评价转化。",
    result: "产品方向从“证明每句话”调整为“让面试官更快形成清晰、可信、愿意追问的候选人判断”，同时继续保留内部事实门禁。",
    limitations: "产品方向调整已经发生，但最终招聘转化仍需真人软测试验证。",
    claimIds: ["C12"], supportsClaimIds: ["C12"], sourceIds: ["S2"],
  },
  {
    ...confirmed,
    id: "ST9",
    title: "把 AI Coding 评测方案推进到多模型 Pilot",
    relatedProject: "baidu-ai-coding-evaluation",
    competency: "模型评测与产品验收",
    interviewUse: ["百度实习", "Evaluator Agent", "代表项目", "AI Coding 评测", "项目挑战"],
    situation: "AI Coding Web 项目既要检查能否构建和完成核心流程，也要判断视觉、交互和移动端体验；如果只看单元测试或一次主观打分，结论很难支持模型选型和版本验收。",
    task: "在导师确定的方向下，我需要参与把评测对象、任务、指标、证据和人工校准组织成一套可执行、可解释的 Pilot。",
    action: "我从 13 项 Benchmark 调研出发，参与设计六类 Web 任务、七维指标与 Gate；把构建、探活、核心流程、多视口和可访问性交给确定性工具，把开放体验交给 Judge，并用 Gold、缺陷注入、重复检查和人工盲评校准评测器。",
    result: "正式 Pilot 覆盖 6 个模型、6 类任务和 36 次运行，完成 18 份盲评。结果没有被压成一个排行榜，而是形成了不同任务类型的模型优势、共同弱项和下一步优化建议。",
    limitations: "每个模型任务组合只运行一次，人工盲评由一人且抽样不均；结论只适用于本次冻结版本与任务集，不表述为行业排名或生产平台成果。",
    claimIds: ["C14", "C15", "C16", "C22", "C23"], supportsClaimIds: ["C14", "C15", "C16", "C22", "C23"], sourceIds: ["S1", "S11"],
  },
  {
    ...confirmed,
    id: "ST10",
    title: "百川医疗 RAG 从业务需求到可信问答闭环",
    relatedProject: "rag-knowledge-base",
    competency: "需求拆解与跨角色产品推进",
    interviewUse: ["百川实习", "RAG 项目介绍", "个人贡献", "医疗 AI"],
    situation: "医疗私有文档分散、持续更新且有较高的事实风险，使用者既需要快速获得答案，也需要核验答案依据。",
    task: "我需要协助把抽象的医疗知识问答需求收敛成可实现、可验收且不替代诊断的 MVP。",
    action: "我参与梳理知识库管理、幻觉风险和来源核验需求，将产品拆成文档处理、知识库管理、检索问答和评测四层，并与算法和研发对齐召回、Rerank、来源片段、短期记忆、多助手配置及 QA 四维评测的规则和验收边界。",
    result: "项目形成了知识入库、Dense 加 Rerank、来源片段、Redis 短期记忆、多助手基础配置和自动评测的闭环，并完成三轮累计 30 次 QA 执行，能够发现多跳问答等弱场景。",
    limitations: "公开项目不是百川生产代码；30 次是 3 份报告各 10 次运行，不是客户验收或 30 个独立真实医疗问题，也不把规划功能描述为已完成。",
    claimIds: ["C17", "C18", "C19", "C20", "C21", "C26", "C27"], supportsClaimIds: ["C17", "C18", "C19", "C20", "C21", "C26", "C27"], sourceIds: ["S3", "S12"],
  },
  {
    ...confirmed,
    id: "ST11",
    title: "把不同项目串成同一条 AI 产品能力主线",
    competency: "持续学习与能力迁移",
    interviewUse: ["自我介绍", "项目串联", "成长主线", "为什么适合 AI 产品"],
    situation: "我的经历横跨统计、审计、医疗 RAG、模型评测和多个 Agent 产品，如果只逐项罗列，很容易显得方向分散。",
    task: "我需要证明这些经历不是项目堆叠，而是围绕同一种问题解决能力逐步深入。",
    action: "我把每段经历沉淀成下一段的输入：审计训练流程、证据和风险；百川把它迁移到 RAG 的来源与评测；百度把质量判断升级为多模型 E2E 评测与归因；Ask Me 和 DeepFlow 再把可信回答与可控执行落到招聘和研究场景；其他小工具用于快速验证更具体的高频问题。",
    result: "最终形成了“发现问题—定义方案—快速验证—评测归因—持续迭代”的稳定方法，也让我的学习能力和产品落地能力能够被不同项目相互印证。",
    limitations: "项目成熟度不同，不能把原型数量等同于真实用户规模、商业化结果或全部能力都达到生产级。",
    claimIds: ["C4", "C5", "C7", "C9", "C12", "C13", "C17", "C28", "C29"], supportsClaimIds: ["C4", "C5", "C7", "C9", "C12", "C13", "C17", "C28", "C29"], sourceIds: ["S1", "S2", "S3", "S4", "S8", "S9", "S10", "S11", "S12"],
  },
] as const;
